SongCreation.NoteDisplayContainer Class Reference
Public Member Functions
void AddNote (int aMelodyVelocity, Music.NOTE_LENGTH aLength, Music.PITCH[] aPitches, int aDrumVelocity, Music.DRUM[] aDrumHits, Music.NOTE_LENGTH aOffsetFromPrevNote)
MeasureDisplayPanel GetCurrentMeasureObject ()
Sprite [] GetSprites ()
void HandleFullMeasure (MeasureDisplayPanel aFullMeasure, float aSpillover, int aMelodyVelocity, Music.NOTE_LENGTH aLength, Music.PITCH[] aPitches, int aDrumVelocity, Music.DRUM[] aDrumHits, Music.NOTE_LENGTH aOffsetFromPrevNote)
void HandleMeasureDeleted (MeasureDisplayPanel aMeasure)
void HandleMeasureToggled (MeasureDisplayPanel aMeasure)
void OnRemoveNote ()
Private Member Functions
void Awake ()
Private Attributes
int mNumNotes = 0
int mCurrentMeasure = 0
List< MeasureDisplayPanel > mMeasures = null
Sprite [] mSprites = null
Detailed Description
Definition at line 491 of file SongCreation.cs.
Member Function Documentation
AddNote()
void SongCreation.NoteDisplayContainer.AddNote (int aMelodyVelocity, Music.NOTE_LENGTH aLength, Music.PITCH [] aPitches, int aDrumVelocity, Music.DRUM [] aDrumHits, Music.NOTE_LENGTH aOffsetFromPrevNote)
Definition at line 534 of file SongCreation.cs.
Referenced by SongCreation.OnCreateNote().
        {
            mMeasures[mCurrentMeasure].AddNote(
      mNumNotes, aMelodyVelocity, aLength, aPitches, aDrumVelocity, aDrumHits, aOffsetFromPrevNote);
            mNumNotes++;
        }
Awake()
void SongCreation.NoteDisplayContainer.Awake () [private]
Definition at line 504 of file SongCreation.cs.
        {
            // Set up the measures.
            mMeasures = new List<MeasureDisplayPanel>();
            mMeasures.Add(gameObject.transform.GetChild(0).gameObject.AddComponent<
      MeasureDisplayPanel>());
            mMeasures[0].SetIsFirstOverallNote(true);
            mMeasures[0].SetParentContainer(this);
            // Load the note length/offset images
            mSprites = new Sprite[13];
            mSprites[0] = Resources.Load<Sprite>("Audio/Images/32nd");
            mSprites[1] = Resources.Load<Sprite>("Audio/Images/dotted32nd");
            mSprites[2] = Resources.Load<Sprite>("Audio/Images/16th");
            mSprites[3] = Resources.Load<Sprite>("Audio/Images/dotted16th");
            mSprites[4] = Resources.Load<Sprite>("Audio/Images/eighth");
            mSprites[5] = Resources.Load<Sprite>("Audio/Images/dottedEighth");
            mSprites[6] = Resources.Load<Sprite>("Audio/Images/quarter");
            mSprites[7] = Resources.Load<Sprite>("Audio/Images/dottedQuarter");
            mSprites[8] = Resources.Load<Sprite>("Audio/Images/half");
            mSprites[9] = Resources.Load<Sprite>("Audio/Images/dottedHalf");
            mSprites[10] = Resources.Load<Sprite>("Audio/Images/whole");
            mSprites[11] = Resources.Load<Sprite>("Audio/Images/dottedWhole");
            mSprites[12] = null;
        }
GetCurrentMeasureObject()
MeasureDisplayPanel SongCreation.NoteDisplayContainer.GetCurrentMeasureObject ()
Definition at line 541 of file SongCreation.cs.
Referenced by SongCreation.MeasureDisplayPanel.AddNote().
        {
            return mMeasures[mCurrentMeasure];
        }
GetSprites()
Sprite [] SongCreation.NoteDisplayContainer.GetSprites ()
Definition at line 547 of file SongCreation.cs.
Referenced by SongCreation.MeasureDisplayPanel.AddNote(), and SongCreation.OnModifyNote().
        {
            return mSprites;
        }
HandleFullMeasure()
void SongCreation.NoteDisplayContainer.HandleFullMeasure (MeasureDisplayPanel aFullMeasure, float aSpillover, int aMelodyVelocity, Music.NOTE_LENGTH aLength, Music.PITCH [] aPitches, int aDrumVelocity, Music.DRUM [] aDrumHits, Music.NOTE_LENGTH aOffsetFromPrevNote)
Definition at line 557 of file SongCreation.cs.
Referenced by SongCreation.MeasureDisplayPanel.AddNote().
        {
            // Create a new measure toggle.
            GameObject clone = Instantiate(mMeasures[0].gameObject);
            mMeasures.Add(clone.GetComponent<MeasureDisplayPanel>());
            // Increase the current measure.
            mCurrentMeasure++;
            // Set the values for the new measure toggle.
            mMeasures[mCurrentMeasure].transform.GetChild(0).GetChild(1).
      GetComponent<Text>().text = "Measure " + (mCurrentMeasure + 1).ToString();
            mMeasures[mCurrentMeasure].SetIsFirstOverallNote(false);
            mMeasures[mCurrentMeasure].transform.SetParent(gameObject.transform);
            mMeasures[mCurrentMeasure].SetParentContainer(this);
            mMeasures[mCurrentMeasure].transform.localScale =
      mMeasures[0].transform.localScale;
            mMeasures[mCurrentMeasure].SetToggle(true);
            // Handle Spillover from the previous measure.
            mMeasures[mCurrentMeasure].SetPercentageUsed(0f - aSpillover);
            // Add the note to the new measure.
            mMeasures[mCurrentMeasure].AddNote(
      mNumNotes, aMelodyVelocity, aLength, aPitches, aDrumVelocity, aDrumHits, aOffsetFromPrevNote);
            // Make only the new measure be shown.
            HandleMeasureToggled(mMeasures[
      mCurrentMeasure]);
        }
HandleMeasureDeleted()
void SongCreation.NoteDisplayContainer.HandleMeasureDeleted (MeasureDisplayPanel aMeasure)
Definition at line 587 of file SongCreation.cs.
Referenced by SongCreation.MeasureDisplayPanel.RemoveNote().
        {
            // Find the measure that is deleted.
            int index = mMeasures.IndexOf(aMeasure);
            mCurrentMeasure--;
            // Remove the measure and show the previous one.
            if(index >= 0)
            {
                mMeasures.RemoveAt(index);
                mMeasures[index - 1].SetToggle(true);
            }
            else
            {
                mMeasures.RemoveAt(index);
                mMeasures[index].SetToggle(true);
            }
            // Delete the measure.
            DestroyImmediate(aMeasure.gameObject, false);
        }
HandleMeasureToggled()
void SongCreation.NoteDisplayContainer.HandleMeasureToggled (MeasureDisplayPanel aMeasure)
Definition at line 610 of file SongCreation.cs.
References SongCreation.MeasureDisplayPanel.SetToggle().
Referenced by SongCreation.MeasureDisplayPanel.OnShowToggle().
        {
            // Set that only the toggled measure should be shown.
            foreach(MeasureDisplayPanel measure in mMeasures)
            {
                if(aMeasure != measure)
                {
                    measure.SetToggle(false);
                }
                else
                {
                    measure.SetToggle(true);
                }
            }
        }
OnRemoveNote()
void SongCreation.NoteDisplayContainer.OnRemoveNote ()
Definition at line 627 of file SongCreation.cs.
Referenced by SongCreation.MeasureDisplayPanel.RemoveNote().
        {
            mNumNotes--;
        }
Member Data Documentation
mCurrentMeasure
int SongCreation.NoteDisplayContainer.mCurrentMeasure = 0 [private]
Definition at line 497 of file SongCreation.cs.
mMeasures
List<MeasureDisplayPanel> SongCreation.NoteDisplayContainer.mMeasures = null [private]
Definition at line 498 of file SongCreation.cs.
mNumNotes
int SongCreation.NoteDisplayContainer.mNumNotes = 0 [private]
Definition at line 496 of file SongCreation.cs.
mSprites
Sprite [] SongCreation.NoteDisplayContainer.mSprites = null [private]
Definition at line 499 of file SongCreation.cs.
The documentation for this class was generated from the following file:
VRPianoProject/Assets/Scripts/Audio/Testing/SongCreation.cs