SongCreation.NoteDisplayPanel Class Reference
Public Member Functions
Sprite GetLengthImage ()
MeasureDisplayPanel GetMeasurePanel ()
int GetNoteIndex ()
Music.NOTE_LENGTH GetOffset ()
void SetDrums (string aDrumString)
void SetLengthImage (Sprite aImage)
void SetOffset (Music.NOTE_LENGTH aOffset)
void SetOffsetImage (Sprite aImage)
void SetParentContainer (MeasureDisplayPanel aParent)
void SetNoteIndex (int aIndex)
void SetPitches (string aPitchString)
void SetVelocity (string aVelocityString)
void StopEditing ()
void OnRemoveButtonClicked ()
Private Member Functions
void Awake ()
void TriggerEditEvent (PointerEventData data)
Private Attributes
Button mRemoveNoteButton = null
EventTrigger mEditTrigger = null
Image mLengthImage = null
Image mOffsetImage = null
int mNoteIndex = 0
MeasureDisplayPanel mParent = null
Music.NOTE_LENGTH mOffset = Music.NOTE_LENGTH.NONE
SongCreation mSongCreationHandler = null
Text mDrums = null
Text mPitches = null
Text mVelocity = null
Detailed Description
Definition at line 27 of file SongCreation.cs.
Member Function Documentation
Awake()
void SongCreation.NoteDisplayPanel.Awake () [private]
Definition at line 49 of file SongCreation.cs.
References SongCreation.NoteDisplayPanel.OnRemoveButtonClicked(), and SongCreation.NoteDisplayPanel.TriggerEditEvent().
        {
            // Set the private variables.
            mSongCreationHandler = GameObject.Find("SongCreationCanvas").GetComponent
      <SongCreation>();
            // Set up the OnClick trigger.
            mEditTrigger = gameObject.AddComponent<EventTrigger>();
            EventTrigger.Entry click = new EventTrigger.Entry();
            click.eventID = EventTriggerType.PointerClick;
            click.callback.AddListener((data) => { TriggerEditEvent((PointerEventData)
      data); });
            mEditTrigger.triggers.Add(click);
            // Setup the children objects.
            mLengthImage = gameObject.transform.GetChild(3).GetChild(1).GetComponent<Image>
      ();
            mOffsetImage = gameObject.transform.GetChild(2).GetChild(1).GetComponent<Image>
      ();
            mPitches = gameObject.transform.GetChild(1).GetChild(0).GetComponent<Text>();
            mVelocity = gameObject.transform.GetChild(4).GetChild(0).GetComponent<Text>();
            mRemoveNoteButton = gameObject.transform.GetChild(0).gameObject.GetComponent
      <Button>();
            mRemoveNoteButton.onClick.AddListener(OnRemoveButtonClicked);
            mDrums = gameObject.transform.GetChild(5).GetChild(0).GetComponent<Text>();
        }
GetLengthImage()
Sprite SongCreation.NoteDisplayPanel.GetLengthImage ()
Definition at line 76 of file SongCreation.cs.
        {
            return mLengthImage.sprite;
        }
GetMeasurePanel()
MeasureDisplayPanel SongCreation.NoteDisplayPanel.GetMeasurePanel ()
Definition at line 82 of file SongCreation.cs.
References SongCreation.NoteDisplayPanel.mParent.
        {
            return mParent;
        }
GetNoteIndex()
int SongCreation.NoteDisplayPanel.GetNoteIndex ()
Definition at line 88 of file SongCreation.cs.
References SongCreation.NoteDisplayPanel.mNoteIndex.
Referenced by SongCreation.OnModifyNote().
        {
            return mNoteIndex;
        }
GetOffset()
Music.NOTE_LENGTH SongCreation.NoteDisplayPanel.GetOffset ()
Definition at line 94 of file SongCreation.cs.
References SongCreation.NoteDisplayPanel.mOffset.
Referenced by SongCreation.MeasureDisplayPanel.RemoveNote().
        {
            return mOffset;
        }
OnRemoveButtonClicked()
void SongCreation.NoteDisplayPanel.OnRemoveButtonClicked ()
Definition at line 176 of file SongCreation.cs.
References SongCreation.NoteDisplayPanel.mNoteIndex, SongCreation.OnRemoveNote(), SongCreation.MeasureDisplayPanel.RemoveNote(), and SongCreation.NoteDisplayPanel.SetNoteIndex().
Referenced by SongCreation.NoteDisplayPanel.Awake().
        {
            // Set the note index for all notes after this one
            int sib = transform.GetSiblingIndex() + 1;
            int index = mNoteIndex;
            while(sib < transform.parent.childCount)
            {
                if(transform.parent.GetChild(sib).GetComponent<NoteDisplayPanel>() != null)
                {
                    transform.parent.GetChild(sib).GetComponent<NoteDisplayPanel>().
      SetNoteIndex(index);
                    index++;
                }
                sib++;
            }
            // Signal that this note display should be removed.
            mParent.RemoveNote(this);
            // Signal that this note should be removed from the song.
            GameObject.Find("SongCreationCanvas").GetComponent<SongCreation>().
      OnRemoveNote(mNoteIndex);
        }
SetDrums()
void SongCreation.NoteDisplayPanel.SetDrums (string aDrumString)
Definition at line 100 of file SongCreation.cs.
Referenced by SongCreation.MeasureDisplayPanel.AddNote(), and SongCreation.OnModifyNote().
        {
            mDrums.text = aDrumString;
        }
SetLengthImage()
void SongCreation.NoteDisplayPanel.SetLengthImage (Sprite aImage)
Definition at line 106 of file SongCreation.cs.
Referenced by SongCreation.MeasureDisplayPanel.AddNote(), and SongCreation.OnModifyNote().
        {
            if(aImage == null)
            {
                mLengthImage.color = new Color32(255, 255, 255, 0);
            }
            else
            {
                mLengthImage.sprite = aImage;
                mLengthImage.color = new Color32(255, 255, 255, 255);
            }
        }
SetNoteIndex()
void SongCreation.NoteDisplayPanel.SetNoteIndex (int aIndex)
Definition at line 147 of file SongCreation.cs.
Referenced by SongCreation.MeasureDisplayPanel.AddNote(), and SongCreation.NoteDisplayPanel.OnRemoveButtonClicked().
        {
            mNoteIndex = aIndex;
        }
SetOffset()
void SongCreation.NoteDisplayPanel.SetOffset (Music.NOTE_LENGTH aOffset)
Definition at line 120 of file SongCreation.cs.
References SongCreation.NoteDisplayPanel.mOffset.
Referenced by SongCreation.MeasureDisplayPanel.AddNote(), and SongCreation.OnModifyNote().
        {
            mOffset = aOffset;
        }
SetOffsetImage()
void SongCreation.NoteDisplayPanel.SetOffsetImage (Sprite aImage)
Definition at line 126 of file SongCreation.cs.
Referenced by SongCreation.MeasureDisplayPanel.AddNote(), and SongCreation.OnModifyNote().
        {
            if(aImage == null)
            {
                mOffsetImage.color = new Color32(255, 255, 255, 0);
            }
            else
            {
                mOffsetImage.sprite = aImage;
                mOffsetImage.color = new Color32(255, 255, 255, 255);
            }
        }
SetParentContainer()
void SongCreation.NoteDisplayPanel.SetParentContainer (MeasureDisplayPanel aParent)
Definition at line 141 of file SongCreation.cs.
Referenced by SongCreation.MeasureDisplayPanel.AddNote().
        {
            mParent = aParent;
        }
SetPitches()
void SongCreation.NoteDisplayPanel.SetPitches (string aPitchString)
Definition at line 153 of file SongCreation.cs.
Referenced by SongCreation.MeasureDisplayPanel.AddNote(), and SongCreation.OnModifyNote().
        {
            mPitches.text = aPitchString;
        }
SetVelocity()
void SongCreation.NoteDisplayPanel.SetVelocity (string aVelocityString)
Definition at line 159 of file SongCreation.cs.
Referenced by SongCreation.MeasureDisplayPanel.AddNote(), and SongCreation.OnModifyNote().
        {
            mVelocity.text = aVelocityString;
        }
StopEditing()
void SongCreation.NoteDisplayPanel.StopEditing ()
Definition at line 165 of file SongCreation.cs.
Referenced by SongCreation.OnEditEvent(), and SongCreation.OnModifyNote().
        {
            // Change the panel background color back to its original color.
            gameObject.GetComponent<Image>().color = new Color32(58, 58, 58, 255);
        }
TriggerEditEvent()
void SongCreation.NoteDisplayPanel.TriggerEditEvent (PointerEventData data) [private]
Definition at line 200 of file SongCreation.cs.
References SongCreation.OnEditEvent().
Referenced by SongCreation.NoteDisplayPanel.Awake().
        {
            if(data.button == PointerEventData.InputButton.Left)
            {
                // Change the color of the background panel to show that we're editing the note that it
                // represents.
                gameObject.GetComponent<Image>().color = new Color32(116, 116, 116, 255);
                // Send the event to the song creation handler.
                mSongCreationHandler.OnEditEvent(this);
            }
        }
Member Data Documentation
mDrums
Text SongCreation.NoteDisplayPanel.mDrums = null [private]
Definition at line 40 of file SongCreation.cs.
mEditTrigger
EventTrigger SongCreation.NoteDisplayPanel.mEditTrigger = null [private]
Definition at line 33 of file SongCreation.cs.
mLengthImage
Image SongCreation.NoteDisplayPanel.mLengthImage = null [private]
Definition at line 34 of file SongCreation.cs.
mNoteIndex
int SongCreation.NoteDisplayPanel.mNoteIndex = 0 [private]
Definition at line 36 of file SongCreation.cs.
Referenced by SongCreation.NoteDisplayPanel.GetNoteIndex(), and SongCreation.NoteDisplayPanel.OnRemoveButtonClicked().
mOffset
Music.NOTE_LENGTH SongCreation.NoteDisplayPanel.mOffset = Music.NOTE_LENGTH.NONE [private]
Definition at line 38 of file SongCreation.cs.
Referenced by SongCreation.NoteDisplayPanel.GetOffset(), and SongCreation.NoteDisplayPanel.SetOffset().
mOffsetImage
Image SongCreation.NoteDisplayPanel.mOffsetImage = null [private]
Definition at line 35 of file SongCreation.cs.
mParent
MeasureDisplayPanel SongCreation.NoteDisplayPanel.mParent = null [private]
Definition at line 37 of file SongCreation.cs.
Referenced by SongCreation.NoteDisplayPanel.GetMeasurePanel().
mPitches
Text SongCreation.NoteDisplayPanel.mPitches = null [private]
Definition at line 41 of file SongCreation.cs.
mRemoveNoteButton
Button SongCreation.NoteDisplayPanel.mRemoveNoteButton = null [private]
Definition at line 32 of file SongCreation.cs.
mSongCreationHandler
SongCreation SongCreation.NoteDisplayPanel.mSongCreationHandler = null [private]
Definition at line 39 of file SongCreation.cs.
mVelocity
Text SongCreation.NoteDisplayPanel.mVelocity = null [private]
Definition at line 42 of file SongCreation.cs.
The documentation for this class was generated from the following file:
VRPianoProject/Assets/Scripts/Audio/Testing/SongCreation.cs