ATI_NoteRangeSelectionHandler Class Reference
Protected Member Functions
override void HandleNoteRangeChange (bool aEndDrag)
Private Member Functions
new void Start ()
void Update ()
void HandleInstrumentLoaded ()
Additional Inherited Members
Detailed Description
Definition at line 15 of file ATI_NoteRangeSelectionHandler.cs.
Member Function Documentation
HandleInstrumentLoaded()
void ATI_NoteRangeSelectionHandler.HandleInstrumentLoaded () [private]
Definition at line 69 of file ATI_NoteRangeSelectionHandler.cs.
References VirtualInstrumentManager.GetHighestSupportedNote(), VirtualInstrumentManager.GetLowestActiveNote(), VirtualInstrumentManager.GetLowestSupportedNote(), VirtualInstrumentManager.GetNumActiveNotes(), ATI.SliderHandler.mSliders, ATI.SliderHandler.mVIM, and Music.NoteToString().
Referenced by Start().
    {
        // Update the slider.
        mSliders[0].minValue = (float)mVIM.GetLowestSupportedNote();
        mSliders[0].maxValue = (float)(mVIM.GetHighestSupportedNote() -
       mVIM.GetNumActiveNotes() + 1);
        mSliders[0].value = (float)mVIM.GetLowestActiveNote();
        // Update the slider text.
        // Set the text.
        gameObject.transform.GetChild(3).GetComponent<Text>().text = "Range: " +
      Music.NoteToString((int)mSliders[0].value)
            + " to " + Music.NoteToString((int)mSliders[0].value +
      mVIM.GetNumActiveNotes() - 1);
    }
HandleNoteRangeChange()
override void ATI_NoteRangeSelectionHandler.HandleNoteRangeChange (bool aEndDrag) [protected], [virtual]
Reimplemented from ATI.SliderHandler.
Definition at line 56 of file ATI_NoteRangeSelectionHandler.cs.
References VirtualInstrumentManager.ChangeNoteRange, VirtualInstrumentManager.GetNumActiveNotes(), ATI.SliderHandler.mSliders, ATI.SliderHandler.mVIM, and Music.NoteToString().
    {
        // Set the text.
        gameObject.transform.GetChild(3).GetComponent<Text>().text = "Range: " +
      Music.NoteToString((int)mSliders[0].value)
            + " to " + Music.NoteToString((int)mSliders[0].value +
      mVIM.GetNumActiveNotes() - 1);
        // If the value has been set, then invoke the virtual instrument manager's ChangeNoteRange event.
        if(aEndDrag)
        {
            mVIM.ChangeNoteRange.Invoke((Music.PITCH)mSliders[0].value);
        }
    }
Start()
new void ATI_NoteRangeSelectionHandler.Start () [private]
Definition at line 23 of file ATI_NoteRangeSelectionHandler.cs.
References HandleInstrumentLoaded(), VirtualInstrumentManager.InstrumentLoaded, ATI.SliderHandler.mSliders, ATI.SliderHandler.mVIM, and ATI.SliderTrigger.SetHandler().
    {
#if DEBUG && DEBUG_MUSICAL_TYPING
        // Call the base start function.
        base.Start();
        // Get the slider and set up its trigger
        ATI.SliderTrigger st = null;
        mSliders = new Slider[1];
        mSliders[0] = gameObject.transform.GetComponent<Slider>();
        st = mSliders[0].gameObject.AddComponent<ATI.SliderTrigger>();
        st.SetHandler(this);
        st.SetType(ATI.SliderType.NoteRange);
        mVIM.InstrumentLoaded.AddListener(
      HandleInstrumentLoaded);
#endif
    }
Update()
void ATI_NoteRangeSelectionHandler.Update () [private]
Definition at line 45 of file ATI_NoteRangeSelectionHandler.cs.
    {
    }
The documentation for this class was generated from the following file:
D:/Documents/School Documents/2017Spring/EECS542/VRPianoProject/Assets/Scripts/Audio/Testing/ATI_NoteRangeSelectionHandler.cs