ATI_ReverbFilterHandler Class Reference
Protected Member Functions
override void SetDefaultParameters ()
override void SendParametersToVIM ()
override void TurnOnEffect ()
override void TurnOffEffect ()
override void HandleSceneLoad ()
override void HandleDryLevelChange (float aValue)
override void HandleRoomChange (float aValue)
override void HandleRoomHFChange (float aValue)
override void HandleDecayTimeChange (float aValue)
override void HandleDecayHFRatioChange (float aValue)
override void HandleReflectionsChange (float aValue)
override void HandleReflectDelayChange (float aValue)
override void HandleReverbChange (float aValue)
override void HandleReverbDelayChange (float aValue)
override void HandleDiffusionChange (float aValue)
override void HandleDensityChange (float aValue)
override void HandleHFReferenceChange (float aValue)
override void HandleRoomLFChange (float aValue)
override void HandleLFReferenceChange (float aValue)
Private Member Functions
new void Start ()
Private Attributes
GameObject mDryLevelContainer = null
GameObject mRoomContainer = null
GameObject mRoomHFContainer = null
GameObject mDecayTimeContainer = null
GameObject mDecayHFRatioContainer = null
GameObject mReflectionsContainer = null
GameObject mReflectDelayContainer = null
GameObject mReverbContainer = null
GameObject mReverbDelayContainer = null
GameObject mDiffusionContainer = null
GameObject mDensityContainer = null
GameObject mHFReferenceContainer = null
GameObject mRoomLFContainer = null
GameObject mLFReferenceContainer = null
VirtualInstrumentManager.ReverbFilterParameters mParams
Additional Inherited Members
Detailed Description
Definition at line 16 of file ATI_ReverbFilterHandler.cs.
Member Function Documentation
HandleDecayHFRatioChange()
override void ATI_ReverbFilterHandler.HandleDecayHFRatioChange (float aValue) [protected], [virtual]
Reimplemented from ATI.AudioEffectHandler.
Definition at line 295 of file ATI_ReverbFilterHandler.cs.
References mParams, and SendParametersToVIM().
    {
        mParams.DecayHFRatio = aValue;
        SendParametersToVIM();
    }
HandleDecayTimeChange()
override void ATI_ReverbFilterHandler.HandleDecayTimeChange (float aValue) [protected], [virtual]
Reimplemented from ATI.AudioEffectHandler.
Definition at line 287 of file ATI_ReverbFilterHandler.cs.
References mParams, and SendParametersToVIM().
    {
        mParams.DecayTime = aValue;
        SendParametersToVIM();
    }
HandleDensityChange()
override void ATI_ReverbFilterHandler.HandleDensityChange (float aValue) [protected], [virtual]
Reimplemented from ATI.AudioEffectHandler.
Definition at line 343 of file ATI_ReverbFilterHandler.cs.
References mParams, and SendParametersToVIM().
    {
        mParams.Density = aValue;
        SendParametersToVIM();
    }
HandleDiffusionChange()
override void ATI_ReverbFilterHandler.HandleDiffusionChange (float aValue) [protected], [virtual]
Reimplemented from ATI.AudioEffectHandler.
Definition at line 335 of file ATI_ReverbFilterHandler.cs.
References mParams, and SendParametersToVIM().
    {
        mParams.Diffusion = aValue;
        SendParametersToVIM();
    }
HandleDryLevelChange()
override void ATI_ReverbFilterHandler.HandleDryLevelChange (float aValue) [protected], [virtual]
Reimplemented from ATI.AudioEffectHandler.
Definition at line 263 of file ATI_ReverbFilterHandler.cs.
References mParams, and SendParametersToVIM().
    {
        mParams.DryLevel = aValue;
        SendParametersToVIM();
    }
HandleHFReferenceChange()
override void ATI_ReverbFilterHandler.HandleHFReferenceChange (float aValue) [protected], [virtual]
Reimplemented from ATI.AudioEffectHandler.
Definition at line 351 of file ATI_ReverbFilterHandler.cs.
References mParams, and SendParametersToVIM().
    {
        mParams.HFReference = aValue;
        SendParametersToVIM();
    }
HandleLFReferenceChange()
override void ATI_ReverbFilterHandler.HandleLFReferenceChange (float aValue) [protected], [virtual]
Reimplemented from ATI.AudioEffectHandler.
Definition at line 367 of file ATI_ReverbFilterHandler.cs.
References mParams, and SendParametersToVIM().
    {
        mParams.LFReference = aValue;
        SendParametersToVIM();
    }
HandleReflectDelayChange()
override void ATI_ReverbFilterHandler.HandleReflectDelayChange (float aValue) [protected], [virtual]
Reimplemented from ATI.AudioEffectHandler.
Definition at line 311 of file ATI_ReverbFilterHandler.cs.
References mParams, and SendParametersToVIM().
    {
        mParams.ReflectDelay = aValue;
        SendParametersToVIM();
    }
HandleReflectionsChange()
override void ATI_ReverbFilterHandler.HandleReflectionsChange (float aValue) [protected], [virtual]
Reimplemented from ATI.AudioEffectHandler.
Definition at line 303 of file ATI_ReverbFilterHandler.cs.
References mParams, and SendParametersToVIM().
    {
        mParams.Reflections = aValue;
        SendParametersToVIM();
    }
HandleReverbChange()
override void ATI_ReverbFilterHandler.HandleReverbChange (float aValue) [protected], [virtual]
Reimplemented from ATI.AudioEffectHandler.
Definition at line 319 of file ATI_ReverbFilterHandler.cs.
References mParams, and SendParametersToVIM().
    {
        mParams.Reverb = aValue;
        SendParametersToVIM();
    }
HandleReverbDelayChange()
override void ATI_ReverbFilterHandler.HandleReverbDelayChange (float aValue) [protected], [virtual]
Reimplemented from ATI.AudioEffectHandler.
Definition at line 327 of file ATI_ReverbFilterHandler.cs.
References mParams, and SendParametersToVIM().
    {
        mParams.ReverbDelay = aValue;
        SendParametersToVIM();
    }
HandleRoomChange()
override void ATI_ReverbFilterHandler.HandleRoomChange (float aValue) [protected], [virtual]
Reimplemented from ATI.AudioEffectHandler.
Definition at line 271 of file ATI_ReverbFilterHandler.cs.
References mParams, and SendParametersToVIM().
    {
        mParams.Room = aValue;
        SendParametersToVIM();
    }
HandleRoomHFChange()
override void ATI_ReverbFilterHandler.HandleRoomHFChange (float aValue) [protected], [virtual]
Reimplemented from ATI.AudioEffectHandler.
Definition at line 279 of file ATI_ReverbFilterHandler.cs.
References mParams, and SendParametersToVIM().
    {
        mParams.RoomHF = aValue;
        SendParametersToVIM();
    }
HandleRoomLFChange()
override void ATI_ReverbFilterHandler.HandleRoomLFChange (float aValue) [protected], [virtual]
Reimplemented from ATI.AudioEffectHandler.
Definition at line 359 of file ATI_ReverbFilterHandler.cs.
References mParams, and SendParametersToVIM().
    {
        mParams.RoomLF = aValue;
        SendParametersToVIM();
    }
HandleSceneLoad()
override void ATI_ReverbFilterHandler.HandleSceneLoad () [protected], [virtual]
Reimplemented from ATI.AudioEffectHandler.
Definition at line 139 of file ATI_ReverbFilterHandler.cs.
References ATI.AudioEffectHandler.mParamObject, mParams, ATI.AudioEffectHandler.mTriggers, ATI.AudioEffectParameterTrigger.SetHandler(), ATI.AudioEffectParameterTrigger.SetRange(), ATI.AudioEffectParameterTrigger.SetType(), and ATI.AudioEffectParameterTrigger.SetValue().
    {
        // Initialize the array of AudioEffectParameterTriggers.
        mTriggers = new ATI.AudioEffectParameterTrigger[14];
        // Get the dry level parameter object and set its values.
        mDryLevelContainer = mParamObject.transform.GetChild(0).GetChild(0
       ).GetChild(0).gameObject;
        mTriggers[0] = mDryLevelContainer.AddComponent<
      ATI.AudioEffectParameterTrigger>();
        mTriggers[0].SetHandler(this);
        mTriggers[0].SetType(ATI.AudioEffectParameterType.
      DryLevel);
        mTriggers[0].SetRange(-10000f, 0f);
        mTriggers[0].SetValue(mParams.DryLevel);
        // Get the room parameter object and set its values.
        mRoomContainer = mParamObject.transform.GetChild(0).GetChild(0).
      GetChild(1).gameObject;
        mTriggers[1] = mRoomContainer.AddComponent<ATI.
      AudioEffectParameterTrigger>();
        mTriggers[1].SetHandler(this);
        mTriggers[1].SetType(ATI.AudioEffectParameterType.Room
      );
        mTriggers[1].SetRange(-10000f, 0f);
        mTriggers[1].SetValue(mParams.Room);
        // Get the roomHF parameter object and set its values.
        mRoomHFContainer = mParamObject.transform.GetChild(0).GetChild(0).
      GetChild(2).gameObject;
        mTriggers[2] = mRoomHFContainer.AddComponent<
      ATI.AudioEffectParameterTrigger>();
        mTriggers[2].SetHandler(this);
        mTriggers[2].SetType(ATI.AudioEffectParameterType.
      RoomHF);
        mTriggers[2].SetRange(-10000f, 0f);
        mTriggers[2].SetValue(mParams.RoomHF);
        // Get the decay time parameter object and set its values.
        mDecayTimeContainer = mParamObject.transform.GetChild(0).GetChild(
       0).GetChild(3).gameObject;
        mTriggers[3] = mDecayTimeContainer.AddComponent<
      ATI.AudioEffectParameterTrigger>();
        mTriggers[3].SetHandler(this);
        mTriggers[3].SetType(ATI.AudioEffectParameterType.
      DecayTime);
        mTriggers[3].SetRange(0.1f, 20f);
        mTriggers[3].SetValue(mParams.DecayTime);
        // Get the decayHFRatio parameter object and set its values.
        mDecayHFRatioContainer = mParamObject.transform.GetChild(0).
      GetChild(0).GetChild(4).gameObject;
        mTriggers[4] = mDecayHFRatioContainer.AddComponent<
      ATI.AudioEffectParameterTrigger>();
        mTriggers[4].SetHandler(this);
        mTriggers[4].SetType(ATI.AudioEffectParameterType.
      DecayHFRatio);
        mTriggers[4].SetRange(0.1f, 2f);
        mTriggers[4].SetValue(mParams.DecayHFRatio);
        // Get the reflections parameter object and set its values.
        mReflectionsContainer = mParamObject.transform.GetChild(0).
      GetChild(0).GetChild(5).gameObject;
        mTriggers[5] = mReflectionsContainer.AddComponent<
      ATI.AudioEffectParameterTrigger>();
        mTriggers[5].SetHandler(this);
        mTriggers[5].SetType(ATI.AudioEffectParameterType.
      Reflections);
        mTriggers[5].SetRange(-10000f, 1000f);
        mTriggers[5].SetValue(mParams.Reflections);
        // Get the reflect delay parameter object and set its values.
        mReflectDelayContainer = mParamObject.transform.GetChild(0).
      GetChild(0).GetChild(6).gameObject;
        mTriggers[6] = mReflectDelayContainer.AddComponent<
      ATI.AudioEffectParameterTrigger>();
        mTriggers[6].SetHandler(this);
        mTriggers[6].SetType(ATI.AudioEffectParameterType.
      ReflectDelay);
        mTriggers[6].SetRange(-10000f, 2000f);
        mTriggers[6].SetValue(mParams.ReflectDelay);
        // Get the reverb parameter object and set its values.
        mReverbContainer = mParamObject.transform.GetChild(0).GetChild(0).
      GetChild(7).gameObject;
        mTriggers[7] = mReverbContainer.AddComponent<
      ATI.AudioEffectParameterTrigger>();
        mTriggers[7].SetHandler(this);
        mTriggers[7].SetType(ATI.AudioEffectParameterType.
      Reverb);
        mTriggers[7].SetRange(-10000f, 2000f);
        mTriggers[7].SetValue(mParams.Reverb);
        // Get the reverb delay parameter object and set its values.
        mReverbDelayContainer = mParamObject.transform.GetChild(0).
      GetChild(0).GetChild(8).gameObject;
        mTriggers[8] = mReverbDelayContainer.AddComponent<
      ATI.AudioEffectParameterTrigger>();
        mTriggers[8].SetHandler(this);
        mTriggers[8].SetType(ATI.AudioEffectParameterType.
      ReverbDelay);
        mTriggers[8].SetRange(0f, 0.1f);
        mTriggers[8].SetValue(mParams.ReverbDelay);
        // Get the diffusion parameter object and set its values.
        mDiffusionContainer = mParamObject.transform.GetChild(0).GetChild(
       0).GetChild(9).gameObject;
        mTriggers[9] = mDiffusionContainer.AddComponent<
      ATI.AudioEffectParameterTrigger>();
        mTriggers[9].SetHandler(this);
        mTriggers[9].SetType(ATI.AudioEffectParameterType.
      Diffusion);
        mTriggers[9].SetRange(0f, 100f);
        mTriggers[9].SetValue(mParams.Diffusion);
        // Get the density parameter object and set its values.
        mDensityContainer = mParamObject.transform.GetChild(0).GetChild(0)
      .GetChild(10).gameObject;
        mTriggers[10] = mDensityContainer.AddComponent<
      ATI.AudioEffectParameterTrigger>();
        mTriggers[10].SetHandler(this);
        mTriggers[10].SetType(ATI.AudioEffectParameterType.
      Density);
        mTriggers[10].SetRange(0f, 100f);
        mTriggers[10].SetValue(mParams.Density);
        // Get the HFReference parameter object and set its values.
        mHFReferenceContainer = mParamObject.transform.GetChild(0).
      GetChild(0).GetChild(11).gameObject;
        mTriggers[11] = mHFReferenceContainer.AddComponent<
      ATI.AudioEffectParameterTrigger>();
        mTriggers[11].SetHandler(this);
        mTriggers[11].SetType(ATI.AudioEffectParameterType.
      HFReference);
        mTriggers[11].SetRange(20f, 20000f);
        mTriggers[11].SetValue(mParams.HFReference);
        // Get the roomLF parameter object and set its values.
        mRoomLFContainer = mParamObject.transform.GetChild(0).GetChild(0).
      GetChild(12).gameObject;
        mTriggers[12] = mRoomLFContainer.AddComponent<
      ATI.AudioEffectParameterTrigger>();
        mTriggers[12].SetHandler(this);
        mTriggers[12].SetType(ATI.AudioEffectParameterType.
      RoomLF);
        mTriggers[12].SetRange(-10000f, 0f);
        mTriggers[12].SetValue(mParams.RoomLF);
        // Get the LFReference parameter object and set its values.
        mLFReferenceContainer = mParamObject.transform.GetChild(0).
      GetChild(0).GetChild(13).gameObject;
        mTriggers[13] = mLFReferenceContainer.AddComponent<
      ATI.AudioEffectParameterTrigger>();
        mTriggers[13].SetHandler(this);
        mTriggers[13].SetType(ATI.AudioEffectParameterType.
      LFReference);
        mTriggers[13].SetRange(20f, 1000f);
        mTriggers[13].SetValue(mParams.LFReference);
    }
SendParametersToVIM()
override void ATI_ReverbFilterHandler.SendParametersToVIM () [protected], [virtual]
Reimplemented from ATI.AudioEffectHandler.
Definition at line 88 of file ATI_ReverbFilterHandler.cs.
References VirtualInstrumentManager.ModifyReverbFilter, mParams, and ATI.AudioEffectHandler.mVIM.
Referenced by HandleDecayHFRatioChange(), HandleDecayTimeChange(), HandleDensityChange(), HandleDiffusionChange(), HandleDryLevelChange(), HandleHFReferenceChange(), HandleLFReferenceChange(), HandleReflectDelayChange(), HandleReflectionsChange(), HandleReverbChange(), HandleReverbDelayChange(), HandleRoomChange(), HandleRoomHFChange(), HandleRoomLFChange(), and TurnOnEffect().
    {
        // Invoke the Virtual Instrument Manager's ModifyReverbFiler event.
        mVIM.ModifyReverbFilter.Invoke(mParams);
    }
SetDefaultParameters()
override void ATI_ReverbFilterHandler.SetDefaultParameters () [protected], [virtual]
Reimplemented from ATI.AudioEffectHandler.
Definition at line 67 of file ATI_ReverbFilterHandler.cs.
References mParams.
    {
        // Set the default parameters.
        mParams.Active = false;
        mParams.DryLevel = 0f;
        mParams.Room = -10000f;
        mParams.RoomHF = 0f;
        mParams.DecayTime = 1f;
        mParams.DecayHFRatio = .5f;
        mParams.Reflections = -10000f;
        mParams.ReflectDelay = 0.02f;
        mParams.Reverb = 0f;
        mParams.ReverbDelay = 0.04f;
        mParams.Diffusion = 100f;
        mParams.Density = 100f;
        mParams.HFReference = 5000f;
        mParams.RoomLF = 0f;
        mParams.LFReference = 250f;
    }
Start()
new void ATI_ReverbFilterHandler.Start () [private]
Definition at line 47 of file ATI_ReverbFilterHandler.cs.
References ATI.AudioEffectHandler.mParamSceneName.
    {
#if DEBUG && DEBUG_MUSICAL_TYPING
        // Call the base start function.
        base.Start();
        // Set the scene name.
        mParamSceneName = "ReverbFilterParametersScene";
#endif
    }
TurnOffEffect()
override void ATI_ReverbFilterHandler.TurnOffEffect () [protected], [virtual]
Reimplemented from ATI.AudioEffectHandler.
Definition at line 109 of file ATI_ReverbFilterHandler.cs.
References ATI.AudioEffectHandler.mButtonImages, ATI.AudioEffectHandler.mEnabled, ATI.AudioEffectHandler.mParamObject, mParams, ATI.AudioEffectHandler.mToggleImage, and ATI.AudioEffectHandler.mTriggers.
    {
        // Set that the filter is off.
        mEnabled = false;
        mParams.Active = false;
        // Change the button image.
        mToggleImage.sprite = mButtonImages[0];
        // Reset the containers and arrays.
        mParamObject = null;
        mDryLevelContainer = null;
        mRoomContainer = null;
        mRoomHFContainer = null;
        mDecayTimeContainer = null;
        mDecayHFRatioContainer = null;
        mReflectionsContainer = null;
        mReflectDelayContainer = null;
        mReverbContainer = null;
        mReverbDelayContainer = null;
        mDiffusionContainer = null;
        mDensityContainer = null;
        mHFReferenceContainer = null;
        mRoomLFContainer = null;
        mLFReferenceContainer = null;
        mTriggers = null;
    }
TurnOnEffect()
override void ATI_ReverbFilterHandler.TurnOnEffect () [protected], [virtual]
Reimplemented from ATI.AudioEffectHandler.
Definition at line 95 of file ATI_ReverbFilterHandler.cs.
References ATI.AudioEffectHandler.mButtonImages, ATI.AudioEffectHandler.mEnabled, mParams, ATI.AudioEffectHandler.mToggleImage, and SendParametersToVIM().
    {
        // Set that the filter is active.
        mEnabled = true;
        mParams.Active = true;
        // Change the button image.
        mToggleImage.sprite = mButtonImages[1];
        // Send the parameters to the virtual instrument manager.
        SendParametersToVIM();
    }
Member Data Documentation
mDecayHFRatioContainer
GameObject ATI_ReverbFilterHandler.mDecayHFRatioContainer = null [private]
Definition at line 28 of file ATI_ReverbFilterHandler.cs.
mDecayTimeContainer
GameObject ATI_ReverbFilterHandler.mDecayTimeContainer = null [private]
Definition at line 27 of file ATI_ReverbFilterHandler.cs.
mDensityContainer
GameObject ATI_ReverbFilterHandler.mDensityContainer = null [private]
Definition at line 34 of file ATI_ReverbFilterHandler.cs.
mDiffusionContainer
GameObject ATI_ReverbFilterHandler.mDiffusionContainer = null [private]
Definition at line 33 of file ATI_ReverbFilterHandler.cs.
mDryLevelContainer
GameObject ATI_ReverbFilterHandler.mDryLevelContainer = null [private]
Definition at line 24 of file ATI_ReverbFilterHandler.cs.
mHFReferenceContainer
GameObject ATI_ReverbFilterHandler.mHFReferenceContainer = null [private]
Definition at line 35 of file ATI_ReverbFilterHandler.cs.
mLFReferenceContainer
GameObject ATI_ReverbFilterHandler.mLFReferenceContainer = null [private]
Definition at line 37 of file ATI_ReverbFilterHandler.cs.
mParams
VirtualInstrumentManager.ReverbFilterParameters ATI_ReverbFilterHandler.mParams [private]
Definition at line 38 of file ATI_ReverbFilterHandler.cs.
Referenced by HandleDecayHFRatioChange(), HandleDecayTimeChange(), HandleDensityChange(), HandleDiffusionChange(), HandleDryLevelChange(), HandleHFReferenceChange(), HandleLFReferenceChange(), HandleReflectDelayChange(), HandleReflectionsChange(), HandleReverbChange(), HandleReverbDelayChange(), HandleRoomChange(), HandleRoomHFChange(), HandleRoomLFChange(), HandleSceneLoad(), SendParametersToVIM(), SetDefaultParameters(), TurnOffEffect(), and TurnOnEffect().
mReflectDelayContainer
GameObject ATI_ReverbFilterHandler.mReflectDelayContainer = null [private]
Definition at line 30 of file ATI_ReverbFilterHandler.cs.
mReflectionsContainer
GameObject ATI_ReverbFilterHandler.mReflectionsContainer = null [private]
Definition at line 29 of file ATI_ReverbFilterHandler.cs.
mReverbContainer
GameObject ATI_ReverbFilterHandler.mReverbContainer = null [private]
Definition at line 31 of file ATI_ReverbFilterHandler.cs.
mReverbDelayContainer
GameObject ATI_ReverbFilterHandler.mReverbDelayContainer = null [private]
Definition at line 32 of file ATI_ReverbFilterHandler.cs.
mRoomContainer
GameObject ATI_ReverbFilterHandler.mRoomContainer = null [private]
Definition at line 25 of file ATI_ReverbFilterHandler.cs.
mRoomHFContainer
GameObject ATI_ReverbFilterHandler.mRoomHFContainer = null [private]
Definition at line 26 of file ATI_ReverbFilterHandler.cs.
mRoomLFContainer
GameObject ATI_ReverbFilterHandler.mRoomLFContainer = null [private]
Definition at line 36 of file ATI_ReverbFilterHandler.cs.
The documentation for this class was generated from the following file:
D:/Documents/School Documents/2017Spring/EECS542/VRPianoProject/Assets/Scripts/Audio/Testing/ATI_ReverbFilterHandler.cs