NoteDisplayContainer Class Reference
Public Member Functions
void AddNote (int aMelodyVelocity, Music.NOTE_LENGTH aLength, Music.PITCH[] aPitches, int aDrumVelocity, Music.DRUM[] aDrumHits, Music.NOTE_LENGTH aOffsetFromPrevNote)
void ClearNotes ()
Clears all of the notes.
SC_MeasureDisplayPanel GetCurrentMeasureObject ()
Sprite [] GetSprites ()
void HandleFullMeasure (SC_MeasureDisplayPanel aFullMeasure, float aSpillover, int aMelodyVelocity, Music.NOTE_LENGTH aLength, Music.PITCH[] aPitches, int aDrumVelocity, Music.DRUM[] aDrumHits, Music.NOTE_LENGTH aOffsetFromPrevNote)
void HandleMeasureDeleted (SC_MeasureDisplayPanel aMeasure)
void HandleMeasureToggled (SC_MeasureDisplayPanel aMeasure)
void OnRemoveNote ()
Private Member Functions
void Awake ()
Private Attributes
const string MEASURE_PANEL_PREFAB_PATH = `Audio/Prefabs/SongCreation/MeasurePanelPrefab`
int mNumNotes = 0
int mCurrentMeasure = -1
List< SC_MeasureDisplayPanel > mMeasures = null
Sprite [] mSprites = null
Detailed Description
Definition at line 12 of file NoteDisplayContainer.cs.
Member Function Documentation
AddNote()
void NoteDisplayContainer.AddNote (int aMelodyVelocity, Music.NOTE_LENGTH aLength, Music.PITCH [] aPitches, int aDrumVelocity, Music.DRUM [] aDrumHits, Music.NOTE_LENGTH aOffsetFromPrevNote)
Definition at line 54 of file NoteDisplayContainer.cs.
References mCurrentMeasure.
Referenced by SongCreationManager.OnCreateNote(), and SongCreationManager.OnLoadSong().
    {
        // Create a measure if none are present.
        if(mCurrentMeasure == -1)
        {
            GameObject newMeasure = Instantiate(Resources.Load<GameObject>(
      MEASURE_PANEL_PREFAB_PATH));
            Assert.IsNotNull(newMeasure, "Could not load the MeasurePanel prefab!");
            // Add the measure panel to the list.
            mMeasures.Add(newMeasure.AddComponent<
      SC_MeasureDisplayPanel>());
            // Increase the current measure.
            mCurrentMeasure++;
            // Set the values for the new measure toggle.
            mMeasures[mCurrentMeasure].transform.GetChild(0).GetChild(1).
      GetComponent<Text>().text = "Measure " + (mCurrentMeasure + 1).ToString();
            mMeasures[mCurrentMeasure].transform.SetParent(gameObject.transform);
            mMeasures[mCurrentMeasure].SetParentContainer(this);
            mMeasures[mCurrentMeasure].transform.localScale = Vector3.one;
            mMeasures[mCurrentMeasure].SetToggle(true);
        }
        mMeasures[mCurrentMeasure].AddNote(mNumNotes, aMelodyVelocity,
      aLength, aPitches, aDrumVelocity, aDrumHits, aOffsetFromPrevNote);
        mNumNotes++;
    }
Awake()
void NoteDisplayContainer.Awake () [private]
Definition at line 27 of file NoteDisplayContainer.cs.
    {
        // Set up the measures.
        mMeasures = new List<SC_MeasureDisplayPanel>();
        // Load the note length/offset images
        mSprites = new Sprite[13];
        mSprites[0] = Resources.Load<Sprite>("Audio/Images/32nd");
        mSprites[1] = Resources.Load<Sprite>("Audio/Images/dotted32nd");
        mSprites[2] = Resources.Load<Sprite>("Audio/Images/16th");
        mSprites[3] = Resources.Load<Sprite>("Audio/Images/dotted16th");
        mSprites[4] = Resources.Load<Sprite>("Audio/Images/eighth");
        mSprites[5] = Resources.Load<Sprite>("Audio/Images/dottedEighth");
        mSprites[6] = Resources.Load<Sprite>("Audio/Images/quarter");
        mSprites[7] = Resources.Load<Sprite>("Audio/Images/dottedQuarter");
        mSprites[8] = Resources.Load<Sprite>("Audio/Images/half");
        mSprites[9] = Resources.Load<Sprite>("Audio/Images/dottedHalf");
        mSprites[10] = Resources.Load<Sprite>("Audio/Images/whole");
        mSprites[11] = Resources.Load<Sprite>("Audio/Images/dottedWhole");
        mSprites[12] = null;
    }
ClearNotes()
void NoteDisplayContainer.ClearNotes ()
Clears all of the notes.
Definition at line 82 of file NoteDisplayContainer.cs.
References mCurrentMeasure.
Referenced by SongCreationManager.OnLoadSong().
    {
        while(mCurrentMeasure >= 0)
        {
            mMeasures[mCurrentMeasure].ClearMeasure();
            mMeasures.RemoveAt(mCurrentMeasure);
            mCurrentMeasure--;
        }
        mNumNotes = 0;
    }
GetCurrentMeasureObject()
SC_MeasureDisplayPanel NoteDisplayContainer.GetCurrentMeasureObject ()
Definition at line 94 of file NoteDisplayContainer.cs.
References mCurrentMeasure.
    {
        return mMeasures[mCurrentMeasure];
    }
GetSprites()
Sprite [] NoteDisplayContainer.GetSprites ()
Definition at line 100 of file NoteDisplayContainer.cs.
References mSprites.
Referenced by SC_MeasureDisplayPanel.AddNote(), and SongCreationManager.OnModifyNote().
    {
        return mSprites;
    }
HandleFullMeasure()
void NoteDisplayContainer.HandleFullMeasure (SC_MeasureDisplayPanel aFullMeasure, float aSpillover, int aMelodyVelocity, Music.NOTE_LENGTH aLength, Music.PITCH [] aPitches, int aDrumVelocity, Music.DRUM [] aDrumHits, Music.NOTE_LENGTH aOffsetFromPrevNote)
Definition at line 110 of file NoteDisplayContainer.cs.
References HandleMeasureToggled(), and mCurrentMeasure.
Referenced by SC_MeasureDisplayPanel.AddNote().
    {
        // Create a new measure toggle.
        GameObject clone = Instantiate(Resources.Load<GameObject>(
      MEASURE_PANEL_PREFAB_PATH));
        Assert.IsNotNull(clone, "Could not load the MeasurePanel prefab!");
        // Add the measure panel to the list.
        mMeasures.Add(clone.AddComponent<SC_MeasureDisplayPanel>());
        // Increase the current measure.
        mCurrentMeasure++;
        // Set the values for the new measure toggle.
        mMeasures[mCurrentMeasure].transform.GetChild(0).GetChild(1).
      GetComponent<Text>().text = "Measure " + (mCurrentMeasure + 1).ToString();
        mMeasures[mCurrentMeasure].transform.SetParent(gameObject.transform);
        mMeasures[mCurrentMeasure].SetParentContainer(this);
        mMeasures[mCurrentMeasure].transform.localScale = Vector3.one;
        mMeasures[mCurrentMeasure].SetToggle(true);
        // Handle Spillover from the previous measure.
        mMeasures[mCurrentMeasure].SetPercentageUsed(0f - aSpillover);
        // Add the note to the new measure.
        mMeasures[mCurrentMeasure].AddNote(mNumNotes, aMelodyVelocity,
      aLength, aPitches, aDrumVelocity, aDrumHits, aOffsetFromPrevNote);
        // Make only the new measure be shown.
        HandleMeasureToggled(mMeasures[
      mCurrentMeasure]);
    }
HandleMeasureDeleted()
void NoteDisplayContainer.HandleMeasureDeleted (SC_MeasureDisplayPanel aMeasure)
Definition at line 142 of file NoteDisplayContainer.cs.
Referenced by SC_MeasureDisplayPanel.RemoveNote().
    {
        // Find the measure that is deleted.
        int index = mMeasures.IndexOf(aMeasure);
        mCurrentMeasure--;
        // Remove the measure and show the previous one if there is one.
        mMeasures.RemoveAt(index);
        if(index > 0)
        {
            mMeasures[index - 1].SetToggle(true);
        }
        // Delete the measure.
        DestroyImmediate(aMeasure.gameObject, false);
    }
HandleMeasureToggled()
void NoteDisplayContainer.HandleMeasureToggled (SC_MeasureDisplayPanel aMeasure)
Definition at line 160 of file NoteDisplayContainer.cs.
References SC_MeasureDisplayPanel.SetToggle().
Referenced by HandleFullMeasure(), and SC_MeasureDisplayPanel.OnShowToggle().
    {
        // Set that only the toggled measure should be shown.
        foreach(SC_MeasureDisplayPanel measure in
      mMeasures)
        {
            if(aMeasure != measure)
            {
                measure.SetToggle(false);
            }
            else
            {
                measure.SetToggle(true);
            }
        }
    }
OnRemoveNote()
void NoteDisplayContainer.OnRemoveNote ()
Definition at line 177 of file NoteDisplayContainer.cs.
Referenced by SC_MeasureDisplayPanel.RemoveNote().
    {
        mNumNotes--;
    }
Member Data Documentation
mCurrentMeasure
int NoteDisplayContainer.mCurrentMeasure = -1 [private]
Definition at line 20 of file NoteDisplayContainer.cs.
Referenced by AddNote(), ClearNotes(), GetCurrentMeasureObject(), and HandleFullMeasure().
MEASURE_PANEL_PREFAB_PATH
const string NoteDisplayContainer.MEASURE_PANEL_PREFAB_PATH = `Audio/Prefabs/SongCreation/MeasurePanelPrefab` [private]
Definition at line 14 of file NoteDisplayContainer.cs.
mMeasures
List<SC_MeasureDisplayPanel> NoteDisplayContainer.mMeasures = null [private]
Definition at line 21 of file NoteDisplayContainer.cs.
mNumNotes
int NoteDisplayContainer.mNumNotes = 0 [private]
Definition at line 19 of file NoteDisplayContainer.cs.
mSprites
Sprite [] NoteDisplayContainer.mSprites = null [private]
Definition at line 22 of file NoteDisplayContainer.cs.
Referenced by GetSprites().
The documentation for this class was generated from the following file:
VRPianoProject/Assets/Scripts/Audio/SongCreation/NoteDisplayContainer.cs