ATI_DiagnosticsDemoSongHandler Class Reference
Public Member Functions
void LoadDemoSong (int aIndex)
void ChangeBPM (float aBPM)
void OnPlayButtonClicked ()
Private Member Functions
void Start ()
Private Attributes
Button mPlayButton = null
Dropdown mSongSelectionMenu = null
Slider mBPMSlider = null
Song mSong = null
Sprite [] mButtonImages = null
The images for the buttons.
Text mBPMSliderText = null
VirtualInstrumentManager mVIM = null
Detailed Description
Definition at line 16 of file ATI_DiagnosticsDemoSongHandler.cs.
Member Function Documentation
ChangeBPM()
void ATI_DiagnosticsDemoSongHandler.ChangeBPM (float aBPM)
Definition at line 86 of file ATI_DiagnosticsDemoSongHandler.cs.
References Song.SetBPM().
Referenced by Start().
    {
        // Update the BPM slider's label.
        mBPMSliderText.text = "BPM: " + aBPM.ToString();
        // Update the loaded song.
        mSong.SetBPM(aBPM);
    }
LoadDemoSong()
void ATI_DiagnosticsDemoSongHandler.LoadDemoSong (int aIndex)
Definition at line 74 of file ATI_DiagnosticsDemoSongHandler.cs.
References Song.GetBPM(), SongManagerClass.GetSongByName(), and VirtualInstrumentManager.SongManager.
Referenced by Start().
    {
        mSong = null;
        mSong = mVIM.SongManager.GetSongByName(
      mSongSelectionMenu.options[aIndex].text);
        mBPMSlider.value = mSong.GetBPM();
    }
OnPlayButtonClicked()
void ATI_DiagnosticsDemoSongHandler.OnPlayButtonClicked ()
Definition at line 96 of file ATI_DiagnosticsDemoSongHandler.cs.
References VirtualInstrumentManager.PlaySong.
Referenced by Start().
    {
        mVIM.PlaySong.Invoke(mSong);
    }
Start()
void ATI_DiagnosticsDemoSongHandler.Start () [private]
Definition at line 32 of file ATI_DiagnosticsDemoSongHandler.cs.
References ChangeBPM(), Song.GetBPM(), LoadDemoSong(), and OnPlayButtonClicked().
    {
        // Get the button images.
        mButtonImages = new Sprite[3];
        mButtonImages[0] = Resources.Load<Sprite>("Audio/Images/play_button");
        mButtonImages[1] = Resources.Load<Sprite>("Audio/Images/pause_button");
        mButtonImages[2] = Resources.Load<Sprite>("Audio/Images/stop_button");
        // Get the virtual instrument manager.
        mVIM = GameObject.Find("VirtualInstrumentManager").GetComponent<
      VirtualInstrumentManager>();
        // Set up the selection menu.
        mSongSelectionMenu = gameObject.GetComponent<Dropdown>();
        mSongSelectionMenu.options.Clear();
        mSongSelectionMenu.AddOptions(mVIM.SongManager.GetCombinedSongNames());
        mSongSelectionMenu.AddOptions(mVIM.SongManager.GetMelodyNames());
        mSongSelectionMenu.onValueChanged.AddListener(LoadDemoSong);
        // Load the default demo song.
        mSong = mVIM.SongManager.GetSongs()[0];
        // Set up the play button
        mPlayButton = transform.GetChild(5).GetComponent<Button>();
        mPlayButton.onClick.AddListener(OnPlayButtonClicked);
        // Set up the BPM slider.
        mBPMSlider = gameObject.transform.GetChild(4).GetComponent<Slider>();
        mBPMSlider.value = mSong.GetBPM();
        mBPMSlider.onValueChanged.AddListener(ChangeBPM);
        // Set up the BPM slider's label.
        mBPMSliderText = mBPMSlider.transform.GetChild(3).GetComponent<Text>();
        mBPMSliderText.text = "BPM: " + mSong.GetBPM().ToString();
    }
Member Data Documentation
mBPMSlider
Slider ATI_DiagnosticsDemoSongHandler.mBPMSlider = null [private]
Definition at line 23 of file ATI_DiagnosticsDemoSongHandler.cs.
mBPMSliderText
Text ATI_DiagnosticsDemoSongHandler.mBPMSliderText = null [private]
Definition at line 26 of file ATI_DiagnosticsDemoSongHandler.cs.
mButtonImages
Sprite [] ATI_DiagnosticsDemoSongHandler.mButtonImages = null [private]
The images for the buttons.
Definition at line 25 of file ATI_DiagnosticsDemoSongHandler.cs.
mPlayButton
Button ATI_DiagnosticsDemoSongHandler.mPlayButton = null [private]
Definition at line 21 of file ATI_DiagnosticsDemoSongHandler.cs.
mSong
Song ATI_DiagnosticsDemoSongHandler.mSong = null [private]
Definition at line 24 of file ATI_DiagnosticsDemoSongHandler.cs.
mSongSelectionMenu
Dropdown ATI_DiagnosticsDemoSongHandler.mSongSelectionMenu = null [private]
Definition at line 22 of file ATI_DiagnosticsDemoSongHandler.cs.
mVIM
VirtualInstrumentManager ATI_DiagnosticsDemoSongHandler.mVIM = null [private]
Definition at line 27 of file ATI_DiagnosticsDemoSongHandler.cs.
The documentation for this class was generated from the following file:
D:/Documents/School Documents/2017Spring/EECS542/VRPianoProject/Assets/Scripts/Audio/Testing/ATI_DiagnosticsDemoSongHandler.cs