ATI.SliderTrigger Class Reference
Public Member Functions
void Awake ()
void SetHandler (SliderHandler aHandler)
void SetType (SliderType aType)
void OnDrag (PointerEventData aEventData)
void OnEndDrag (PointerEventData aEventData)
Private Attributes
Slider mSlider
SliderHandler mHandler
SliderType mSliderType
Detailed Description
Definition at line 62 of file ATI.cs.
Member Function Documentation
Awake()
void ATI.SliderTrigger.Awake ()
Definition at line 75 of file ATI.cs.
        {
            mSlider = gameObject.transform.GetComponent<Slider>();
            mHandler = null;
            mSliderType = SliderType.Uninitialized;
        }
OnDrag()
void ATI.SliderTrigger.OnDrag (PointerEventData aEventData)
Definition at line 106 of file ATI.cs.
References ATI.SliderHandler.HandleDrag().
        {
            if(aEventData.dragging)
            {
                mHandler.HandleDrag(mSlider,
      mSliderType);
            }
        }
OnEndDrag()
void ATI.SliderTrigger.OnEndDrag (PointerEventData aEventData)
Definition at line 116 of file ATI.cs.
References ATI.SliderHandler.HandleDragEnd().
        {
            mHandler.HandleDragEnd(mSlider,
      mSliderType);
        }
SetHandler()
void ATI.SliderTrigger.SetHandler (SliderHandler aHandler)
Definition at line 88 of file ATI.cs.
Referenced by ATI.AudioEffectParameterTrigger.Awake(), ATI_NoteRangeSelectionHandler.Start(), and ATI_VelocityHandler.Start().
        {
            mHandler = aHandler;
        }
SetType()
void ATI.SliderTrigger.SetType (SliderType aType)
Definition at line 95 of file ATI.cs.
Referenced by ATI_VelocityHandler.Start().
        {
            mSliderType = aType;
        }
Member Data Documentation
mHandler
SliderHandler ATI.SliderTrigger.mHandler [private]
Definition at line 69 of file ATI.cs.
mSlider
Slider ATI.SliderTrigger.mSlider [private]
Definition at line 68 of file ATI.cs.
mSliderType
SliderType ATI.SliderTrigger.mSliderType [private]
Definition at line 70 of file ATI.cs.
The documentation for this class was generated from the following file:
D:/Documents/School Documents/2017Spring/EECS542/VRPianoProject/Assets/Scripts/Audio/Testing/ATI.cs