ATI.AudioEffectParameterTrigger Class Reference
Public Member Functions
void SetHandler (AudioEffectHandler aHandler)
void SetRange (float aLowest, float aHighest)
void SetType (AudioEffectParameterType aType)
void SetValue (float aValue)
Protected Member Functions
override void SendSliderChangeToHandler ()
Private Member Functions
void Awake ()
void SendInputFieldChangeToHandler (string aNewValue)
Private Attributes
AudioEffectHandler mHandler
AudioEffectParameterType mType = AudioEffectParameterType.Uninitialized
float mValue = 0f
float [] mRange = null
InputField mField = null
Additional Inherited Members
Detailed Description
Definition at line 245 of file ATI.cs.
Member Function Documentation
Awake()
void ATI.AudioEffectParameterTrigger.Awake () [private]
Definition at line 260 of file ATI.cs.
References ATI.SliderTrigger.SetHandler().
        {
            // Get the associated input field and set a handler to handle when
            // editing the field is finished.
            mField = gameObject.transform.GetChild(0).GetComponent<InputField>();
            mField.onEndEdit.AddListener(SendInputFieldChangeToHandler
      );
            // Get the associated slider and add its trigger
            mSliders = new Slider[1];
            mSliderTriggers = new SliderTrigger[1];
            mSliders[0] = gameObject.transform.GetChild(1).GetComponent<Slider>();
            mSliderTriggers[0] = mSliders[0].gameObject.AddComponent<SliderTrigger>(
      );
            // Set the values for the slider trigger.
            mSliderTriggers[0].SetHandler(this);
            mSliderTriggers[0].SetType(SliderType.AudioEffectParameter);
        }
SendInputFieldChangeToHandler()
void ATI.AudioEffectParameterTrigger.SendInputFieldChangeToHandler (string aNewValue) [private]
Definition at line 337 of file ATI.cs.
References ATI.AudioEffectHandler.HandleAudioEffectParameterChange().
        {
            // Get the new value as a float.
            float value = float.Parse(aNewValue);
            // Make sure that we have a range of possible values.
            if(mRange == null)
            {
                Assert.IsTrue(false, "Tried to handle a change in the input field for an audio effect, but
       the trigger's range was uninitialized!");
                return;
            }
            // If the new value is within the range, then update the slider and send the change to the
       handler.
            if(value >= mRange[0] && value <= mRange[1])
            {
                mValue = value;
                mSliders[0].value = value;
                mHandler.HandleAudioEffectParameterChange(
      mType, value);
            }
            // If the new value is not within the range, then reset it.
            else
            {
                mField.text = mValue.ToString("F2");
            }
        }
SendSliderChangeToHandler()
override void ATI.AudioEffectParameterTrigger.SendSliderChangeToHandler () [protected], [virtual]
Reimplemented from ATI.SliderHandler.
Definition at line 365 of file ATI.cs.
References ATI.AudioEffectHandler.HandleAudioEffectParameterChange().
        {
            // Update the member variable, input field, and send the change
            // to the parent handler.
            mValue = mSliders[0].value;
            mField.text = mValue.ToString("F2");
            mHandler.HandleAudioEffectParameterChange(
      mType, mValue);
        }
SetHandler()
void ATI.AudioEffectParameterTrigger.SetHandler (AudioEffectHandler aHandler)
Definition at line 285 of file ATI.cs.
Referenced by ATI_EchoFilterHandler.HandleSceneLoad(), and ATI_ReverbFilterHandler.HandleSceneLoad().
        {
            mHandler = aHandler;
        }
SetRange()
void ATI.AudioEffectParameterTrigger.SetRange (float aLowest, float aHighest)
Definition at line 293 of file ATI.cs.
Referenced by ATI_EchoFilterHandler.HandleSceneLoad(), and ATI_ReverbFilterHandler.HandleSceneLoad().
        {
            // Allocate the range array if needed.
            if(mRange == null)
            {
                mRange = new float[2];
            }
            // Update the member variables
            mRange[0] = aLowest;
            mRange[1] = aHighest;
            // Update the slider.
            mSliders[0].minValue = aLowest;
            mSliders[0].maxValue = aHighest;
        }
SetType()
void ATI.AudioEffectParameterTrigger.SetType (AudioEffectParameterType aType)
Definition at line 312 of file ATI.cs.
Referenced by ATI_EchoFilterHandler.HandleSceneLoad(), and ATI_ReverbFilterHandler.HandleSceneLoad().
        {
            mType = aType;
        }
SetValue()
void ATI.AudioEffectParameterTrigger.SetValue (float aValue)
Definition at line 319 of file ATI.cs.
Referenced by ATI_EchoFilterHandler.HandleSceneLoad(), and ATI_ReverbFilterHandler.HandleSceneLoad().
        {
            // Update the member variable.
            mValue = aValue;
            // Update the slider.
            mSliders[0].value = aValue;
            // Update the input field.
            mField.text = mValue.ToString("F2");
        }
Member Data Documentation
mField
InputField ATI.AudioEffectParameterTrigger.mField = null [private]
Definition at line 254 of file ATI.cs.
mHandler
AudioEffectHandler ATI.AudioEffectParameterTrigger.mHandler [private]
Definition at line 250 of file ATI.cs.
mRange
float [] ATI.AudioEffectParameterTrigger.mRange = null [private]
Definition at line 253 of file ATI.cs.
mType
AudioEffectParameterType ATI.AudioEffectParameterTrigger.mType = AudioEffectParameterType.Uninitialized [private]
Definition at line 251 of file ATI.cs.
mValue
float ATI.AudioEffectParameterTrigger.mValue = 0f [private]
Definition at line 252 of file ATI.cs.
The documentation for this class was generated from the following file:
D:/Documents/School Documents/2017Spring/EECS542/VRPianoProject/Assets/Scripts/Audio/Testing/ATI.cs