ATI_EchoFilterHandler Class Reference
Protected Member Functions
override void SetDefaultParameters ()
override void SendParametersToVIM ()
override void TurnOnEffect ()
override void TurnOffEffect ()
override void HandleDecayChange (float aValue)
override void HandleDelayChange (float aValue)
override void HandleDryMixChange (float aValue)
override void HandleSceneLoad ()
override void HandleWetMixChange (float aValue)
Private Member Functions
new void Start ()
Private Attributes
GameObject mDecayContainer = null
GameObject mDelayContainer = null
GameObject mDryMixContainer = null
GameObject mWetMixContainer = null
VirtualInstrumentManager.EchoFilterParameters mParams
Additional Inherited Members
Detailed Description
Definition at line 16 of file ATI_EchoFilterHandler.cs.
Member Function Documentation
HandleDecayChange()
override void ATI_EchoFilterHandler.HandleDecayChange (float aValue) [protected], [virtual]
Reimplemented from ATI.AudioEffectHandler.
Definition at line 115 of file ATI_EchoFilterHandler.cs.
References mParams, and SendParametersToVIM().
    {
        mParams.Decay = aValue / 100f;
        SendParametersToVIM();
    }
HandleDelayChange()
override void ATI_EchoFilterHandler.HandleDelayChange (float aValue) [protected], [virtual]
Reimplemented from ATI.AudioEffectHandler.
Definition at line 123 of file ATI_EchoFilterHandler.cs.
References mParams, and SendParametersToVIM().
    {
        mParams.Delay = aValue;
        SendParametersToVIM();
    }
HandleDryMixChange()
override void ATI_EchoFilterHandler.HandleDryMixChange (float aValue) [protected], [virtual]
Reimplemented from ATI.AudioEffectHandler.
Definition at line 131 of file ATI_EchoFilterHandler.cs.
References mParams, and SendParametersToVIM().
    {
        mParams.DryMix = aValue / 100f;
        SendParametersToVIM();
    }
HandleSceneLoad()
override void ATI_EchoFilterHandler.HandleSceneLoad () [protected], [virtual]
Reimplemented from ATI.AudioEffectHandler.
Definition at line 138 of file ATI_EchoFilterHandler.cs.
References ATI.AudioEffectHandler.mParamObject, mParams, ATI.AudioEffectHandler.mTriggers, ATI.AudioEffectParameterTrigger.SetHandler(), ATI.AudioEffectParameterTrigger.SetRange(), ATI.AudioEffectParameterTrigger.SetType(), and ATI.AudioEffectParameterTrigger.SetValue().
    {
        // Initialize the AudioEffectParameterTrigger array.
        mTriggers = new ATI.AudioEffectParameterTrigger[4];
        // Get the dry mix parameter object and set its values.
        mDryMixContainer = mParamObject.transform.GetChild(0).GetChild(0).
      GetChild(2).gameObject;
        mTriggers[0] = mDryMixContainer.AddComponent<
      ATI.AudioEffectParameterTrigger>();
        mTriggers[0].SetHandler(this);
        mTriggers[0].SetType(ATI.AudioEffectParameterType.
      DryMix);
        mTriggers[0].SetRange(0f, 100f);
        mTriggers[0].SetValue(mParams.DryMix * 100f);
        // Get the wet mix parameter object and set its values.
        mWetMixContainer = mParamObject.transform.GetChild(0).GetChild(0).
      GetChild(3).gameObject;
        mTriggers[1] = mWetMixContainer.AddComponent<
      ATI.AudioEffectParameterTrigger>();
        mTriggers[1].SetHandler(this);
        mTriggers[1].SetType(ATI.AudioEffectParameterType.
      WetMix);
        mTriggers[1].SetRange(0f, 100f);
        mTriggers[1].SetValue(mParams.WetMix * 100f);
        // Get the delay parameter object and set its values.
        mDelayContainer = mParamObject.transform.GetChild(0).GetChild(0).
      GetChild(0).gameObject;
        mTriggers[2] = mDelayContainer.AddComponent<ATI.
      AudioEffectParameterTrigger>();
        mTriggers[2].SetHandler(this);
        mTriggers[2].SetType(ATI.AudioEffectParameterType.Delay
       );
        mTriggers[2].SetRange(10f, 5000f);
        mTriggers[2].SetValue(mParams.Delay);
        // Get the decay parameter object and set its values.
        mDecayContainer = mParamObject.transform.GetChild(0).GetChild(0).
      GetChild(1).gameObject;
        mTriggers[3] = mDecayContainer.AddComponent<ATI.
      AudioEffectParameterTrigger>();
        mTriggers[3].SetHandler(this);
        mTriggers[3].SetType(ATI.AudioEffectParameterType.Decay
       );
        mTriggers[3].SetRange(0f, 100f);
        mTriggers[3].SetValue(mParams.Decay * 100f);
    }
HandleWetMixChange()
override void ATI_EchoFilterHandler.HandleWetMixChange (float aValue) [protected], [virtual]
Reimplemented from ATI.AudioEffectHandler.
Definition at line 178 of file ATI_EchoFilterHandler.cs.
References mParams, and SendParametersToVIM().
    {
        mParams.WetMix = aValue / 100f;
        SendParametersToVIM();
    }
SendParametersToVIM()
override void ATI_EchoFilterHandler.SendParametersToVIM () [protected], [virtual]
Reimplemented from ATI.AudioEffectHandler.
Definition at line 66 of file ATI_EchoFilterHandler.cs.
References VirtualInstrumentManager.ModifyEchoFilter, mParams, and ATI.AudioEffectHandler.mVIM.
Referenced by HandleDecayChange(), HandleDelayChange(), HandleDryMixChange(), HandleWetMixChange(), TurnOffEffect(), and TurnOnEffect().
    {
        // Invoke the virtual instrument manager's ModifyEchoFilterEvent.
        mVIM.ModifyEchoFilter.Invoke(mParams);
    }
SetDefaultParameters()
override void ATI_EchoFilterHandler.SetDefaultParameters () [protected], [virtual]
Reimplemented from ATI.AudioEffectHandler.
Definition at line 55 of file ATI_EchoFilterHandler.cs.
References mParams.
    {
        // Set the default parameters.
        mParams.Active = false;
        mParams.Decay = 0.25f;
        mParams.Delay = 200f;
        mParams.DryMix = 1f;
        mParams.WetMix = 1f;
    }
Start()
new void ATI_EchoFilterHandler.Start () [private]
Definition at line 37 of file ATI_EchoFilterHandler.cs.
References ATI.AudioEffectHandler.mParamSceneName.
    {
#if DEBUG && DEBUG_MUSICAL_TYPING
        // Call the base start function and set the parameter scene name.
        base.Start();
        mParamSceneName = "EchoFilterParametersScene";
#endif
    }
TurnOffEffect()
override void ATI_EchoFilterHandler.TurnOffEffect () [protected], [virtual]
Reimplemented from ATI.AudioEffectHandler.
Definition at line 87 of file ATI_EchoFilterHandler.cs.
References ATI.AudioEffectHandler.mButtonImages, ATI.AudioEffectHandler.mEnabled, ATI.AudioEffectHandler.mParamObject, mParams, ATI.AudioEffectHandler.mToggleImage, ATI.AudioEffectHandler.mTriggers, and SendParametersToVIM().
    {
        // Mark that the effect is no longer enabled in both the parameters
        // and the member variable.
        mEnabled = false;
        mParams.Active = false;
        // Change the button image.
        mToggleImage.sprite = mButtonImages[0];
        // Set the parameter objects to null.
        mParamObject = null;
        mDryMixContainer = null;
        mWetMixContainer = null;
        mTriggers = null;
        mDecayContainer = null;
        mDelayContainer = null;
        // Send the parameters to the Virtual Instrument Manager.
        SendParametersToVIM();
    }
TurnOnEffect()
override void ATI_EchoFilterHandler.TurnOnEffect () [protected], [virtual]
Reimplemented from ATI.AudioEffectHandler.
Definition at line 73 of file ATI_EchoFilterHandler.cs.
References ATI.AudioEffectHandler.mButtonImages, ATI.AudioEffectHandler.mEnabled, mParams, ATI.AudioEffectHandler.mToggleImage, and SendParametersToVIM().
    {
        // Mark that the effect is enabled in both the parameters and the member variable.
        mEnabled = true;
        mParams.Active = true;
        // Change the button image.
        mToggleImage.sprite = mButtonImages[1];
        // Send the parameters to the Virtual Instrument Manager.
        SendParametersToVIM();
    }
Member Data Documentation
mDecayContainer
GameObject ATI_EchoFilterHandler.mDecayContainer = null [private]
Definition at line 24 of file ATI_EchoFilterHandler.cs.
mDelayContainer
GameObject ATI_EchoFilterHandler.mDelayContainer = null [private]
Definition at line 25 of file ATI_EchoFilterHandler.cs.
mDryMixContainer
GameObject ATI_EchoFilterHandler.mDryMixContainer = null [private]
Definition at line 26 of file ATI_EchoFilterHandler.cs.
mParams
VirtualInstrumentManager.EchoFilterParameters ATI_EchoFilterHandler.mParams [private]
Definition at line 28 of file ATI_EchoFilterHandler.cs.
Referenced by HandleDecayChange(), HandleDelayChange(), HandleDryMixChange(), HandleSceneLoad(), HandleWetMixChange(), SendParametersToVIM(), SetDefaultParameters(), TurnOffEffect(), and TurnOnEffect().
mWetMixContainer
GameObject ATI_EchoFilterHandler.mWetMixContainer = null [private]
Definition at line 27 of file ATI_EchoFilterHandler.cs.
The documentation for this class was generated from the following file:
D:/Documents/School Documents/2017Spring/EECS542/VRPianoProject/Assets/Scripts/Audio/Testing/ATI_EchoFilterHandler.cs