SongCreation.MeasureDisplayPanel Class Reference
Public Member Functions
void AddNote (int aNoteIndex, int aMelodyVelocity, Music.NOTE_LENGTH aLength, Music.PITCH[] aPitches, int aDrumVelocity, Music.DRUM[] aDrumHits, Music.NOTE_LENGTH aOffsetFromPrevNote)
void SetIsFirstOverallNote (bool aFirstOverallNote)
void SetParentContainer (NoteDisplayContainer aParent)
void SetPercentageUsed (float aPercent)
void SetToggle (bool aShowMeasure)
void OnShowToggle (bool aShowMeasure)
void RemoveNote (NoteDisplayPanel aNote)
Private Member Functions
void Awake ()
Private Attributes
bool mFirstOverallNote = false
float mPercentageUsed = 0f
List< NoteDisplayPanel > mNotes = null
NoteDisplayContainer mParent = null
Toggle mShowMeasureToggle = null
Detailed Description
Definition at line 217 of file SongCreation.cs.
Member Function Documentation
AddNote()
void SongCreation.MeasureDisplayPanel.AddNote (int aNoteIndex, int aMelodyVelocity, Music.NOTE_LENGTH aLength, Music.PITCH [] aPitches, int aDrumVelocity, Music.DRUM [] aDrumHits, Music.NOTE_LENGTH aOffsetFromPrevNote)
Definition at line 246 of file SongCreation.cs.
References Music.DrumToString(), SongCreation.NoteDisplayContainer.GetCurrentMeasureObject(), Music.GetNoteLengthRelativeToMeasure(), SongCreation.NoteDisplayContainer.GetSprites(), SongCreation.NoteDisplayContainer.HandleFullMeasure(), Music.NoteToString(), SongCreation.NoteDisplayPanel.SetDrums(), SongCreation.NoteDisplayPanel.SetLengthImage(), SongCreation.NoteDisplayPanel.SetNoteIndex(), SongCreation.NoteDisplayPanel.SetOffset(), SongCreation.NoteDisplayPanel.SetOffsetImage(), SongCreation.NoteDisplayPanel.SetParentContainer(), SongCreation.NoteDisplayPanel.SetPitches(), SongCreation.NoteDisplayPanel.SetVelocity(), and Music.TIME_SIGNATURE_4_4().
        {
            Sprite[] sprites = mParent.GetSprites();
            string pitches = "None";
            string drums = "None";
            // Need special handling for the very first note due to having to use it as a base to copy
       from.
            if(mFirstOverallNote)
            {
                // Mark that we would no longer be adding the very first note.
                mFirstOverallNote = false;
                // Set the pitches if needed.
                if(aPitches != null)
                {
                    pitches = "";
                    foreach(Music.PITCH pitch in aPitches)
                    {
                        if(pitch == Music.PITCH.REST)
                        {
                            pitches += "Rest ";
                        }
                        else
                        {
                            pitches += (Music.NoteToString(pitch) + " ");
                        }
                    }
                }
                // Set the drums if needed.
                if(aDrumHits != null)
                {
                    drums = "";
                    foreach(Music.DRUM drum in aDrumHits)
                    {
                        drums += Music.DrumToString(drum) + " ";
                    }
                }
                mNotes[0].SetPitches(pitches);
                mNotes[0].SetDrums(drums);
                // Set the images.
                mNotes[0].SetLengthImage(sprites[(int)aLength]);
                mNotes[0].SetOffsetImage(null);
                // Set the offset and velocity.
                mNotes[0].SetOffset(aOffsetFromPrevNote);
                mNotes[0].SetVelocity(aMelodyVelocity.ToString());
                mNotes[0].SetNoteIndex(aNoteIndex);
            }
            else
            {
                // If this is not the first overall note, then calculate the percentage used up in the
       measure.
                float newPercentage = mPercentageUsed + Music.
      GetNoteLengthRelativeToMeasure(aOffsetFromPrevNote,
      Music.TIME_SIGNATURE_4_4());
                // If there is no more room in the measure for this note, then send it back to the parent.
                if(newPercentage >= 1f)
                {
                    mParent.HandleFullMeasure(this, newPercentage -
      mPercentageUsed, aMelodyVelocity, aLength, aPitches, aDrumVelocity, aDrumHits,
      aOffsetFromPrevNote);
                }
                // If there is more room, then create the new panel and add it to this measure.
                else
                {
                    // Update the percentage used.
                    mPercentageUsed = newPercentage;
                    // Create a new object and set it as a child. Clone the last note from the previous
       measure if this measure is empty.
                    GameObject clone = null;
                    if(mNotes.Count == 0)
                    {
                        clone = Instantiate(mParent.transform.GetChild(
      mParent.GetCurrentMeasureObject().transform.GetSiblingIndex() - 1).
      gameObject);
                    }
                    // Clone the first note of this measure if the measure is not empty.
                    else
                    {
                        clone = Instantiate(mNotes[0].gameObject);
                    }
                    // Set the values for the note's transform.
                    clone.transform.SetParent(gameObject.transform.parent);
                    clone.transform.localScale = mParent.transform.GetChild(1).localScale;
                    // Set the pitch string if needed.
                    if(aPitches != null)
                    {
                        pitches = "";
                        for(int i = 0; i < aPitches.Length; i++)
                        {
                            if(aPitches[i] == Music.PITCH.REST)
                            {
                                pitches += "Rest ";
                            }
                            else
                            {
                                pitches += (Music.NoteToString(aPitches[i]) + " ");
                            }
                        }
                    }
                    // Set the drum string if needed.
                    if(aDrumHits != null)
                    {
                        drums = "";
                        foreach(Music.DRUM drum in aDrumHits)
                        {
                            drums += Music.DrumToString(drum) + " ";
                        }
                    }
                    // Initialize the cloned panel.
                    NoteDisplayPanel newPanel = clone.GetComponent<NoteDisplayPanel>();
                    newPanel.SetDrums(drums);
                    newPanel.SetPitches(pitches);
                    newPanel.SetLengthImage(sprites[(int)aLength]);
                    newPanel.SetOffsetImage(sprites[(int)aOffsetFromPrevNote]);
                    newPanel.SetOffset(aOffsetFromPrevNote);
                    newPanel.SetVelocity(aMelodyVelocity.ToString());
                    newPanel.SetParentContainer(this);
                    newPanel.SetNoteIndex(aNoteIndex);
                    // Add the panel to the list.
                    mNotes.Add(newPanel);
                }
            }
        }
Awake()
void SongCreation.MeasureDisplayPanel.Awake () [private]
Definition at line 231 of file SongCreation.cs.
        {
            // Set the toggle.
            mShowMeasureToggle = gameObject.transform.GetChild(0).GetComponent<Toggle>(
      );
            mShowMeasureToggle.onValueChanged.AddListener(
      OnShowToggle);
            // Set up the list of note display panels.
            mNotes = new List<NoteDisplayPanel>();
        }
OnShowToggle()
void SongCreation.MeasureDisplayPanel.OnShowToggle (bool aShowMeasure)
Definition at line 423 of file SongCreation.cs.
References SongCreation.NoteDisplayContainer.HandleMeasureToggled().
        {
            mParent.HandleMeasureToggled(this);
        }
RemoveNote()
void SongCreation.MeasureDisplayPanel.RemoveNote (NoteDisplayPanel aNote)
Definition at line 429 of file SongCreation.cs.
References Music.GetNoteLengthRelativeToMeasure(), SongCreation.NoteDisplayPanel.GetOffset(), SongCreation.NoteDisplayContainer.HandleMeasureDeleted(), SongCreation.NoteDisplayContainer.OnRemoveNote(), and Music.TIME_SIGNATURE_4_4().
Referenced by SongCreation.NoteDisplayPanel.OnRemoveButtonClicked().
        {
            // Handle the case where this is the only measure and we're removing the only note.
            if(gameObject.transform.GetChild(0).GetChild(1).GetComponent<Text>().text == "Measure 1"
      && mNotes.Count == 1)
            {
                mFirstOverallNote = true;
            }
            // If there is more than one note in the measure, then just remove it from the measure.
            if(mNotes.Count > 1)
            {
                // Find the note.
                bool found = false;
                int index = 0;
                while(!found && index < mNotes.Count)
                {
                    if(aNote == mNotes[index])
                    {
                        found = true;
                    }
                    else
                    {
                        index++;
                    }
                }
                NoteDisplayPanel temp = mNotes[index];
                // Remove the note from the list.
                mNotes.RemoveAt(index);
                // Update the percentage used.
                mPercentageUsed -= Music.
      GetNoteLengthRelativeToMeasure(temp.GetOffset(),
      Music.TIME_SIGNATURE_4_4());
                // Destroy the note object.
                DestroyImmediate(temp.gameObject, false);
            }
            // Make sure that we don't destroy the only note panel.
            else if(mFirstOverallNote)
            {
                mNotes[0].SetLengthImage(null);
                mNotes[0].SetOffset(Music.NOTE_LENGTH.NONE);
                mNotes[0].SetOffsetImage(null);
                mNotes[0].SetPitches("");
                mNotes[0].SetVelocity("70");
            }
            // If there aren't any notes left, then handle this measure being deleted.
            else
            {
                NoteDisplayPanel temp = mNotes[0];
                mNotes.Clear();
                DestroyImmediate(temp.gameObject, false);
                mParent.HandleMeasureDeleted(this);
            }
            mParent.OnRemoveNote();
        }
SetIsFirstOverallNote()
void SongCreation.MeasureDisplayPanel.SetIsFirstOverallNote (bool aFirstOverallNote)
Definition at line 378 of file SongCreation.cs.
        {
            mFirstOverallNote = aFirstOverallNote;
        }
SetParentContainer()
void SongCreation.MeasureDisplayPanel.SetParentContainer (NoteDisplayContainer aParent)
Definition at line 384 of file SongCreation.cs.
        {
            // Set the parent.
            mParent = aParent;
            // If this is the first measure, then add the existing note panel to the list.
            if(mFirstOverallNote)
            {
                mNotes.Add(gameObject.transform.parent.GetChild(1).gameObject.AddComponent<
      NoteDisplayPanel>());
                mNotes[0].SetParentContainer(this);
            }
        }
SetPercentageUsed()
void SongCreation.MeasureDisplayPanel.SetPercentageUsed (float aPercent)
Definition at line 398 of file SongCreation.cs.
        {
            mPercentageUsed = aPercent;
        }
SetToggle()
void SongCreation.MeasureDisplayPanel.SetToggle (bool aShowMeasure)
Definition at line 404 of file SongCreation.cs.
Referenced by SongCreation.NoteDisplayContainer.HandleMeasureToggled().
        {
            // Show/Hide the notes in the measure depending on the given bool.
            foreach(NoteDisplayPanel note in mNotes)
            {
                note.gameObject.SetActive(aShowMeasure);
            }
            // Update the toggle value.
            mShowMeasureToggle.onValueChanged.RemoveListener(
      OnShowToggle);
            mShowMeasureToggle.isOn = aShowMeasure;
            mShowMeasureToggle.onValueChanged.AddListener(
      OnShowToggle);
        }
Member Data Documentation
mFirstOverallNote
bool SongCreation.MeasureDisplayPanel.mFirstOverallNote = false [private]
Definition at line 222 of file SongCreation.cs.
mNotes
List<NoteDisplayPanel> SongCreation.MeasureDisplayPanel.mNotes = null [private]
Definition at line 224 of file SongCreation.cs.
mParent
NoteDisplayContainer SongCreation.MeasureDisplayPanel.mParent = null [private]
Definition at line 225 of file SongCreation.cs.
mPercentageUsed
float SongCreation.MeasureDisplayPanel.mPercentageUsed = 0f [private]
Definition at line 223 of file SongCreation.cs.
mShowMeasureToggle
Toggle SongCreation.MeasureDisplayPanel.mShowMeasureToggle = null [private]
Definition at line 226 of file SongCreation.cs.
The documentation for this class was generated from the following file:
VRPianoProject/Assets/Scripts/Audio/Testing/SongCreation.cs