SongCreation.PitchSelectionContainer.PitchSelectionTrigger Class Reference
Public Member Functions
void SetHandler (PitchSelectionContainer aHandler)
void SetIndex (int aIndex)
void SetSelection (bool aSelected)
void OnPitchSelected (bool aSelected)
Private Member Functions
void Awake ()
Private Attributes
int mIndex = -1
PitchSelectionContainer mHandler = null
Toggle mToggle
Detailed Description
Definition at line 641 of file SongCreation.cs.
Member Function Documentation
Awake()
void SongCreation.PitchSelectionContainer.PitchSelectionTrigger.Awake () [private]
Definition at line 653 of file SongCreation.cs.
            {
                // Get the toggle and add its listener.
                mToggle = gameObject.GetComponent<Toggle>();
                mToggle.onValueChanged.AddListener(OnPitchSelected);
            }
OnPitchSelected()
void SongCreation.PitchSelectionContainer.PitchSelectionTrigger.OnPitchSelected (bool aSelected)
Definition at line 690 of file SongCreation.cs.
References SongCreation.PitchSelectionContainer.HandlePitchSelection().
            {
                mHandler.HandlePitchSelection(aSelected,
      mIndex);
            }
SetHandler()
void SongCreation.PitchSelectionContainer.PitchSelectionTrigger.SetHandler (PitchSelectionContainer aHandler)
Definition at line 665 of file SongCreation.cs.
Referenced by SongCreation.PitchSelectionContainer.SetUpDrums(), and SongCreation.PitchSelectionContainer.SetUpPitches().
            {
                mHandler = aHandler;
            }
SetIndex()
void SongCreation.PitchSelectionContainer.PitchSelectionTrigger.SetIndex (int aIndex)
Definition at line 671 of file SongCreation.cs.
Referenced by SongCreation.PitchSelectionContainer.SetUpDrums(), and SongCreation.PitchSelectionContainer.SetUpPitches().
            {
                mIndex = aIndex;
            }
SetSelection()
void SongCreation.PitchSelectionContainer.PitchSelectionTrigger.SetSelection (bool aSelected)
Definition at line 677 of file SongCreation.cs.
Referenced by SongCreation.PitchSelectionContainer.HandlePitchSelection(), SongCreation.PitchSelectionContainer.OnRestToggle(), and SongCreation.PitchSelectionContainer.ResetPitches().
            {
                // Update the toggle switch.
                mToggle.onValueChanged.RemoveListener(OnPitchSelected);
                mToggle.isOn = aSelected;
                mToggle.onValueChanged.AddListener(OnPitchSelected);
            }
Member Data Documentation
mHandler
PitchSelectionContainer SongCreation.PitchSelectionContainer.PitchSelectionTrigger.mHandler = null [private]
Definition at line 647 of file SongCreation.cs.
mIndex
int SongCreation.PitchSelectionContainer.PitchSelectionTrigger.mIndex = -1 [private]
Definition at line 646 of file SongCreation.cs.
mToggle
Toggle SongCreation.PitchSelectionContainer.PitchSelectionTrigger.mToggle [private]
Definition at line 648 of file SongCreation.cs.
The documentation for this class was generated from the following file:
VRPianoProject/Assets/Scripts/Audio/Testing/SongCreation.cs