SongCreation.SongCreationSelectionContainer.SongCreationSelectionTrigger Class Reference
Public Member Functions
void SetContainer (SongCreationSelectionContainer aContainer)
void SetSelected (bool aSelected)
void OnSelected (bool aSelected)
Private Member Functions
void Awake ()
void ChangeColor ()
Private Attributes
bool mSelected = false
SongCreationSelectionContainer mContainer = null
Toggle mToggle = null
Detailed Description
Definition at line 920 of file SongCreation.cs.
Member Function Documentation
Awake()
void SongCreation.SongCreationSelectionContainer.SongCreationSelectionTrigger.Awake () [private]
Definition at line 932 of file SongCreation.cs.
            {
                // Get the toggle and set its listener
                mToggle = gameObject.GetComponent<Toggle>();
                mToggle.onValueChanged.AddListener(OnSelected);
            }
ChangeColor()
void SongCreation.SongCreationSelectionContainer.SongCreationSelectionTrigger.ChangeColor () [private]
Definition at line 968 of file SongCreation.cs.
            {
                if(mSelected)
                {
                    mToggle.transform.GetChild(0).GetComponent<Image>().color = new Color32(255,
      255, 255, 118);
                }
                else
                {
                    mToggle.transform.GetChild(0).GetComponent<Image>().color = new Color32(255,
      255, 255, 255);
                }
            }
OnSelected()
void SongCreation.SongCreationSelectionContainer.SongCreationSelectionTrigger.OnSelected (bool aSelected)
Definition at line 986 of file SongCreation.cs.
References SongCreation.SongCreationSelectionContainer.HandleToggle().
            {
                // If this object is now selected, then change the color and send it to the handler.
                if(aSelected)
                {
                    mSelected = aSelected;
                    ChangeColor();
                    mContainer.HandleToggle(this);
                }
                // This object can not be unselected by clicking on it. Set the value back to selected.
                else
                {
                    mToggle.onValueChanged.RemoveListener(OnSelected);
                    mToggle.isOn = true;
                    mToggle.onValueChanged.AddListener(OnSelected);
                }
            }
SetContainer()
void SongCreation.SongCreationSelectionContainer.SongCreationSelectionTrigger.SetContainer (SongCreationSelectionContainer aContainer)
Definition at line 944 of file SongCreation.cs.
Referenced by SongCreation.SongCreationSelectionContainer.Awake().
            {
                mContainer = aContainer;
            }
SetSelected()
void SongCreation.SongCreationSelectionContainer.SongCreationSelectionTrigger.SetSelected (bool aSelected)
Definition at line 950 of file SongCreation.cs.
Referenced by SongCreation.SongCreationSelectionContainer.Awake(), SongCreation.SongCreationSelectionContainer.HandleToggle(), and SongCreation.SongCreationSelectionContainer.SetSelected().
            {
                mSelected = aSelected;
                // Change the color to indicate that this is or isn't the selected object
                ChangeColor();
                // Set the value of the toggle.
                mToggle.onValueChanged.RemoveListener(OnSelected);
                mToggle.isOn = aSelected;
                mToggle.onValueChanged.AddListener(OnSelected);
            }
Member Data Documentation
mContainer
SongCreationSelectionContainer SongCreation.SongCreationSelectionContainer.SongCreationSelectionTrigger.mContainer = null [private]
Definition at line 926 of file SongCreation.cs.
mSelected
bool SongCreation.SongCreationSelectionContainer.SongCreationSelectionTrigger.mSelected = false [private]
Definition at line 925 of file SongCreation.cs.
mToggle
Toggle SongCreation.SongCreationSelectionContainer.SongCreationSelectionTrigger.mToggle = null [private]
Definition at line 927 of file SongCreation.cs.
The documentation for this class was generated from the following file:
VRPianoProject/Assets/Scripts/Audio/Testing/SongCreation.cs