ATI_VelocityHandler Class Reference
Public Member Functions
void OnRandomizeVelocitySwitch (bool aSwitch)
Protected Member Functions
override void HandleHighestRandomVelocityChange (bool aEndDrag)
override void HandleLowestRandomVelocityChange (bool aEndDrag)
override void HandleMusicalTypingKeyVelocityChange (int aSliderIndex)
Private Member Functions
new void Start ()
void Update ()
void RandomizeKeyVelocities ()
Private Attributes
string [] keys
ATI.SliderTrigger mHighestRandomSliderTrigger = null
ATI.SliderTrigger mLowestRandomSliderTrigger = null
bool mRandomize = false
Slider mLowestRandomSlider = null
Slider mHighestRandomSlider = null
Sprite [] mSprites = null
Text [] mText = null
Toggle mRandomToggle = null
Additional Inherited Members
Detailed Description
Definition at line 16 of file ATI_VelocityHandler.cs.
Member Function Documentation
HandleHighestRandomVelocityChange()
override void ATI_VelocityHandler.HandleHighestRandomVelocityChange (bool aEndDrag) [protected], [virtual]
Reimplemented from ATI.SliderHandler.
Definition at line 124 of file ATI_VelocityHandler.cs.
References RandomizeKeyVelocities().
    {
        // Set the text and update the lowest random velocity slider's max value.
        mHighestRandomSlider.transform.GetChild(4).GetComponent<Text>().text = "
      Highest: " + mHighestRandomSlider.value.ToString();
        mLowestRandomSlider.maxValue = mHighestRandomSlider.value;
        // If the value is set, then randomize the velocities for each key.
        if(aEndDrag && mRandomize)
        {
            RandomizeKeyVelocities();
        }
    }
HandleLowestRandomVelocityChange()
override void ATI_VelocityHandler.HandleLowestRandomVelocityChange (bool aEndDrag) [protected], [virtual]
Reimplemented from ATI.SliderHandler.
Definition at line 139 of file ATI_VelocityHandler.cs.
References RandomizeKeyVelocities().
    {
        // Set the text and update the highest random velocity slider's min value.
        mLowestRandomSlider.transform.GetChild(4).GetComponent<Text>().text = "Lowest:
       " + mLowestRandomSlider.value.ToString();
        mHighestRandomSlider.minValue = mLowestRandomSlider.value;
        // If the value is set, then randomize the velocities for each key.
        if(aEndDrag && mRandomize)
        {
            RandomizeKeyVelocities();
        }
    }
HandleMusicalTypingKeyVelocityChange()
override void ATI_VelocityHandler.HandleMusicalTypingKeyVelocityChange (int aSliderIndex) [protected], [virtual]
Reimplemented from ATI.SliderHandler.
Definition at line 154 of file ATI_VelocityHandler.cs.
References VirtualInstrumentManager.GetMusicalTypingHandler(), ATI.SliderHandler.mSliders, ATI.SliderHandler.mVIM, and MusicalTypingHandler.SetKeyVelocity().
    {
        // Change the text and pass the value to the virtual instrument manager.
        mText[aSliderIndex].text = keys[aSliderIndex] + mSliders[aSliderIndex].value.
      ToString();
        mVIM.GetMusicalTypingHandler().SetKeyVelocity(
      aSliderIndex, (int)mSliders[aSliderIndex].value);
    }
OnRandomizeVelocitySwitch()
void ATI_VelocityHandler.OnRandomizeVelocitySwitch (bool aSwitch)
Definition at line 163 of file ATI_VelocityHandler.cs.
References RandomizeKeyVelocities().
Referenced by Start().
    {
        if(aSwitch)
        {
            // If the switch has been turned on, update the image and text and randomize the musical typing
            // key velocities.
            mRandomize = true;
            mRandomToggle.transform.GetChild(1).GetComponent<Image>().sprite =
      mSprites[1];
            mRandomToggle.transform.GetChild(2).GetComponent<Text>().text = "Randomize
       Velocities:\nOn";
            RandomizeKeyVelocities();
        }
        else
        {
            // If the switch has been turned off, then update the image and the text.
            mRandomToggle.transform.GetChild(1).GetComponent<Image>().sprite =
      mSprites[0];
            mRandomToggle.transform.GetChild(2).GetComponent<Text>().text = "Randomize
       Velocities:\nOff";
            mRandomize = false;
        }
    }
RandomizeKeyVelocities()
void ATI_VelocityHandler.RandomizeKeyVelocities () [private]
Definition at line 111 of file ATI_VelocityHandler.cs.
References VirtualInstrumentManager.GetMusicalTypingHandler(), mRandomize, ATI.SliderHandler.mVIM, MusicalTypingHandler.RandomizeVelocities, and MusicalTypingHandler.SetRandomVelocityRange().
Referenced by HandleHighestRandomVelocityChange(), HandleLowestRandomVelocityChange(), and OnRandomizeVelocitySwitch().
    {
        mRandomize = mRandomToggle.enabled;
        mVIM.GetMusicalTypingHandler().
      RandomizeVelocities = mRandomize;
        mVIM.GetMusicalTypingHandler().
      SetRandomVelocityRange((int)mLowestRandomSlider.value, (int)
      mHighestRandomSlider.value);
    }
Start()
new void ATI_VelocityHandler.Start () [private]
Definition at line 46 of file ATI_VelocityHandler.cs.
References mHighestRandomSliderTrigger, mLowestRandomSliderTrigger, ATI.SliderHandler.mNumSliders, ATI.SliderHandler.mSliders, ATI.SliderHandler.mSliderTriggers, OnRandomizeVelocitySwitch(), ATI.SliderTrigger.SetHandler(), and ATI.SliderTrigger.SetType().
    {
#if DEBUG && DEBUG_MUSICAL_TYPING
        // Call the ATI.SliderHandler start function.
        base.Start();
        // Set the images for the randomize musical typing velocities switch.
        mSprites = new Sprite[2];
        mSprites[0] = Resources.Load<Sprite>("Audio/Images/off_button");
        mSprites[1] = Resources.Load<Sprite>("Audio/Images/on_button");
        // Set the toggle switch for randomizing musical typing velocities
        mRandomToggle = gameObject.transform.GetChild(0).GetComponent<Toggle>();
        mRandomToggle.onValueChanged.AddListener(OnRandomizeVelocitySwitch);
        // Set the lowest random value slider.
        mLowestRandomSlider = gameObject.transform.GetChild(1).GetComponent<Slider>();
        mLowestRandomSliderTrigger =
      mLowestRandomSlider.gameObject.AddComponent<ATI.
      SliderTrigger>();
        mLowestRandomSliderTrigger.SetHandler(this);
        mLowestRandomSliderTrigger.SetType(ATI.SliderType.LowestRandomKeyVelocity);
        // Set the highest random value slider.
        mHighestRandomSlider = gameObject.transform.GetChild(2).GetComponent<Slider>(
      );
        mHighestRandomSliderTrigger =
      mHighestRandomSlider.gameObject.AddComponent<ATI.
      SliderTrigger>();
        mHighestRandomSliderTrigger.SetHandler(this);
        mHighestRandomSliderTrigger.SetType(ATI.SliderType.HighestRandomKeyVelocity);
        // Initialize the sliders, their text, and their triggers.
        mNumSliders = 19;
        mSliders = new Slider[mNumSliders];
        mText = new Text[mNumSliders];
        mSliderTriggers = new ATI.SliderTrigger[
      mNumSliders];
        for(int i = 0; i < mNumSliders; i++)
        {
            // For each slider, put it in the array and add the slider trigger.
            mSliders[i] = gameObject.transform.GetChild(i + 3).GetComponent<Slider>();
            mSliderTriggers[i] = mSliders[i].gameObject.AddComponent<
      ATI.SliderTrigger>();
            mSliderTriggers[i].SetType(ATI.SliderType.MusicalTypingKeyVelocity);
            mSliderTriggers[i].SetHandler(this);
            // For each text, put it in the array and set its value
            mText[i] = mSliders[i].gameObject.transform.GetChild(4).GetComponent<Text>();
            mText[i].text = keys[i] + "100";
        }
#endif
    }
Update()
void ATI_VelocityHandler.Update () [private]
Definition at line 99 of file ATI_VelocityHandler.cs.
    {
    }
Member Data Documentation
keys
string [] ATI_VelocityHandler.keys [private]
Initial value:
=
        { "a: ", "w: ", "s: ", "e: ", "d: ", "f: ", "t: ", "g: ", "y: ", "h: ", "u: ", "j: ", "k: ", "o: ",
       "l: ", "p: ", ";: ", "': ", "]: " }
Definition at line 24 of file ATI_VelocityHandler.cs.
mHighestRandomSlider
Slider ATI_VelocityHandler.mHighestRandomSlider = null [private]
Definition at line 34 of file ATI_VelocityHandler.cs.
mHighestRandomSliderTrigger
ATI.SliderTrigger ATI_VelocityHandler.mHighestRandomSliderTrigger = null [private]
Definition at line 30 of file ATI_VelocityHandler.cs.
Referenced by Start().
mLowestRandomSlider
Slider ATI_VelocityHandler.mLowestRandomSlider = null [private]
Definition at line 33 of file ATI_VelocityHandler.cs.
mLowestRandomSliderTrigger
ATI.SliderTrigger ATI_VelocityHandler.mLowestRandomSliderTrigger = null [private]
Definition at line 31 of file ATI_VelocityHandler.cs.
Referenced by Start().
mRandomize
bool ATI_VelocityHandler.mRandomize = false [private]
Definition at line 32 of file ATI_VelocityHandler.cs.
Referenced by RandomizeKeyVelocities().
mRandomToggle
Toggle ATI_VelocityHandler.mRandomToggle = null [private]
Definition at line 37 of file ATI_VelocityHandler.cs.
mSprites
Sprite [] ATI_VelocityHandler.mSprites = null [private]
Definition at line 35 of file ATI_VelocityHandler.cs.
mText
Text [] ATI_VelocityHandler.mText = null [private]
Definition at line 36 of file ATI_VelocityHandler.cs.
The documentation for this class was generated from the following file:
D:/Documents/School Documents/2017Spring/EECS542/VRPianoProject/Assets/Scripts/Audio/Testing/ATI_VelocityHandler.cs