DrumKit Class Reference
Public Member Functions
DrumKit (VirtualInstrumentManager aParent)
Protected Member Functions
override void InitializeBuiltInDynamics ()
Initializes variables related to Built-In Dynamics.
override void CreateFilenames ()
Creates the filenames for the sample files.
Additional Inherited Members
Detailed Description
Definition at line 16 of file DrumKit.cs.
Constructor & Destructor Documentation
DrumKit()
DrumKit.DrumKit (VirtualInstrumentManager aParent)
Definition at line 26 of file DrumKit.cs.
References CreateFilenames(), InitializeBuiltInDynamics(), VirtualInstrument.mHighestSupportedPitch, VirtualInstrument.mIsDrum, VirtualInstrument.mLoaded, VirtualInstrument.mLowestSupportedPitch, VirtualInstrument.mNumSupportedPitches, VirtualInstrument.mSampleInterval, and VirtualInstrument.mSampleRate.
                                                       : base(aParent)
    {
        // Set default values
        mIsDrum = true;
        mLowestSupportedPitch = Music.PITCH.C0;
        mHighestSupportedPitch = Music.PITCH.F1;
        mNumSupportedPitches = 18;
        mSampleRate = 44100;
        mSampleInterval = 1f / mSampleRate;
        // Call functions to set the values relating to built-in dynamics and create the filenames for each
       sample.
        InitializeBuiltInDynamics();
        CreateFilenames();
        // Set that this instrument is loaded.
        mLoaded = true;
    }
Member Function Documentation
CreateFilenames()
override void DrumKit.CreateFilenames () [protected], [virtual]
Creates the filenames for the sample files.
Reimplemented from VirtualInstrument.
Definition at line 64 of file DrumKit.cs.
References Music.DrumToString(), VirtualInstrument.mFilenames, VirtualInstrument.mFilepath, VirtualInstrument.mHighestSupportedPitch, VirtualInstrument.mLowestSupportedPitch, and VirtualInstrument.mNumFiles.
Referenced by DrumKit().
    {
        // Set the base filepath and number of files.
        mFilepath = "Audio/VirtualInstrument/DrumKit/Samples/";
        mNumFiles = 18;
        // Initialize the array of filenames.
        mFilenames = new string[mNumFiles];
        // Iterate through each dynamics value and create filenames for each supported note.
        int index = 0;
        for(int i = (int)mLowestSupportedPitch; i <= (int)
      mHighestSupportedPitch; i++)
        {
            mFilenames[index] = mFilepath + Music.
      DrumToString(i);
            index++;
        }
    }
InitializeBuiltInDynamics()
override void DrumKit.InitializeBuiltInDynamics () [protected], [virtual]
Initializes variables related to Built-In Dynamics.
Reimplemented from VirtualInstrument.
Definition at line 51 of file DrumKit.cs.
References VirtualInstrument.mAudioData, Music.MAX_SUPPORTED_DRUMS, VirtualInstrument.mBuiltInDynamics, VirtualInstrument.mBuiltInDynamicsThresholds, and VirtualInstrument.mNumBuiltInDynamics.
Referenced by DrumKit().
    {
        // There are no built-in dynamics for the drum kit (yet).
        mNumBuiltInDynamics = 0;
        mBuiltInDynamics = null;
        mBuiltInDynamicsThresholds = null;
        // Allocate the audio data container.
        mAudioData = new float[1][][];
        mAudioData[0] = new float[Music.MAX_SUPPORTED_DRUMS][];
    }
The documentation for this class was generated from the following file:
D:/Documents/School Documents/2017Spring/EECS542/VRPianoProject/Assets/Scripts/Audio/VirtualInstrument/DrumKit.cs