ATI_DemoSongButtonHandler Class Reference
Public Member Functions
void LoadDemoSong (int aIndex)
void ChangeBPM (float aBPM)
void HandleInstrumentChange (Music.INSTRUMENT_TYPE aType)
void OnPlayPauseButtonClicked ()
void OnStopButtonClicked ()
void SetFinished ()
Public Attributes
bool DrumLoopSelector = false
Private Member Functions
void Start ()
void Update ()
Private Attributes
bool mActive = true
bool mFinished = false
Is the song finished?
bool mPaused = false
Is the song paused?
bool mPlaying = false
Is the song playing?
Button mPlayPauseButton = null
Button mStopButton = null
The button to stop the song.
Dropdown mSongSelectionMenu = null
Slider mBPMSlider = null
Song mSong = null
Sprite [] mButtonImages = null
The images for the buttons.
Text mBPMSliderText = null
VirtualInstrumentManager mVIM = null
Detailed Description
Definition at line 16 of file ATI_DemoSongButtonHandler.cs.
Member Function Documentation
ChangeBPM()
void ATI_DemoSongButtonHandler.ChangeBPM (float aBPM)
Definition at line 132 of file ATI_DemoSongButtonHandler.cs.
References Song.SetBPM().
Referenced by Start().
    {
        // Update the BPM slider's label.
        mBPMSliderText.text = "BPM: " + aBPM.ToString();
        // Update the loaded song.
        mSong.SetBPM(aBPM);
    }
HandleInstrumentChange()
void ATI_DemoSongButtonHandler.HandleInstrumentChange (Music.INSTRUMENT_TYPE aType)
Definition at line 142 of file ATI_DemoSongButtonHandler.cs.
Referenced by Start().
    {
        if(aType == Music.INSTRUMENT_TYPE.DRUM_KIT && !
      DrumLoopSelector)
        {
            mActive = false;
            mBPMSlider.gameObject.SetActive(false);
            mPlayPauseButton.transform.parent.gameObject.SetActive(false);
            mStopButton.transform.parent.gameObject.SetActive(false);
            mSongSelectionMenu.gameObject.SetActive(false);
        }
        else if(!mActive)
        {
            mActive = true;
            mBPMSlider.gameObject.SetActive(true);
            mPlayPauseButton.transform.parent.gameObject.SetActive(true);
            mSongSelectionMenu.gameObject.SetActive(true);
        }
    }
LoadDemoSong()
void ATI_DemoSongButtonHandler.LoadDemoSong (int aIndex)
Definition at line 120 of file ATI_DemoSongButtonHandler.cs.
References Song.GetBPM(), SongManagerClass.GetSongByName(), and VirtualInstrumentManager.SongManager.
Referenced by Start().
    {
        mSong = null;
        mSong = mVIM.SongManager.GetSongByName(
      mSongSelectionMenu.options[aIndex].text);
        mBPMSlider.value = mSong.GetBPM();
    }
OnPlayPauseButtonClicked()
void ATI_DemoSongButtonHandler.OnPlayPauseButtonClicked ()
Definition at line 162 of file ATI_DemoSongButtonHandler.cs.
References VirtualInstrumentManager.PauseDrumLoop, VirtualInstrumentManager.PauseSong, VirtualInstrumentManager.PlayDrumLoop, VirtualInstrumentManager.PlaySong, VirtualInstrumentManager.ResumeDrumLoop, and VirtualInstrumentManager.ResumeSong.
Referenced by Start().
    {
        if(DrumLoopSelector)
        {
            if(mPlaying && !mPaused)
            {
                mVIM.PauseDrumLoop.Invoke();
                mPlayPauseButton.image.sprite = mButtonImages[0];
                mPaused = true;
            }
            else if(mPaused)
            {
                mVIM.ResumeDrumLoop.Invoke();
                mPlayPauseButton.image.sprite = mButtonImages[1];
                mPaused = false;
                mPlaying = true;
            }
            else
            {
                mVIM.PlayDrumLoop.Invoke(mSong);
                mStopButton.transform.parent.gameObject.SetActive(true);
                mPlayPauseButton.image.sprite = mButtonImages[1];
                mPlaying = true;
            }
        }
        else
        {
            if(mPlaying && !mPaused)
            {
                mVIM.PauseSong.Invoke();
                mPlayPauseButton.image.sprite = mButtonImages[0];
                mPaused = true;
            }
            else if(mPaused)
            {
                mVIM.ResumeSong.Invoke();
                mPlayPauseButton.image.sprite = mButtonImages[1];
                mPaused = false;
                mPlaying = true;
            }
            else
            {
                mVIM.PlaySong.Invoke(mSong);
                mStopButton.transform.parent.gameObject.SetActive(true);
                mPlayPauseButton.image.sprite = mButtonImages[1];
                mPlaying = true;
            }
        }
    }
OnStopButtonClicked()
void ATI_DemoSongButtonHandler.OnStopButtonClicked ()
Definition at line 212 of file ATI_DemoSongButtonHandler.cs.
References VirtualInstrumentManager.StopDrumLoop, and VirtualInstrumentManager.StopSong.
Referenced by Start().
    {
        Assert.IsTrue(mPlaying || mPaused, "Somehow we tried to stop a song that wasn't
       playing.");
        mStopButton.transform.parent.gameObject.SetActive(false);
        mPlaying = false;
        mPaused = false;
        mPlayPauseButton.image.sprite = mButtonImages[0];
        if(DrumLoopSelector)
        {
            mVIM.StopDrumLoop.Invoke();
        }
        else
        {
            mVIM.StopSong.Invoke();
        }
    }
SetFinished()
void ATI_DemoSongButtonHandler.SetFinished ()
Definition at line 231 of file ATI_DemoSongButtonHandler.cs.
Referenced by Start().
    {
        mFinished = true;
    }
Start()
void ATI_DemoSongButtonHandler.Start () [private]
Definition at line 40 of file ATI_DemoSongButtonHandler.cs.
References ChangeBPM(), VirtualInstrumentManager.ChangeInstrument, Song.GetBPM(), HandleInstrumentChange(), LoadDemoSong(), OnPlayPauseButtonClicked(), OnStopButtonClicked(), and SetFinished().
    {
        // Get the button images.
        mButtonImages = new Sprite[3];
        mButtonImages[0] = Resources.Load<Sprite>("Audio/Images/play_button");
        mButtonImages[1] = Resources.Load<Sprite>("Audio/Images/pause_button");
        mButtonImages[2] = Resources.Load<Sprite>("Audio/Images/stop_button");
        // Get the virtual instrument manager.
        mVIM = GameObject.Find("VirtualInstrumentManager").GetComponent<
      VirtualInstrumentManager>();
        // Account for the VIM changing instruments.
        mVIM.ChangeInstrument.AddListener(
      HandleInstrumentChange);
        // Set up the selection menu.
        mSongSelectionMenu = gameObject.GetComponent<Dropdown>();
        mSongSelectionMenu.options.Clear();
        if(!DrumLoopSelector)
        {
            mSongSelectionMenu.AddOptions(mVIM.SongManager.GetCombinedSongNames());
            mSongSelectionMenu.AddOptions(mVIM.SongManager.GetMelodyNames());
            mSongSelectionMenu.onValueChanged.AddListener(
      LoadDemoSong);
            // Load the default demo song.
            mSong = mVIM.SongManager.GetCombinedSongs()[0];
        }
        else
        {
            mSongSelectionMenu.AddOptions(mVIM.SongManager.GetDrumLoopNames());
            mSongSelectionMenu.onValueChanged.AddListener(
      LoadDemoSong);
            mSong = mVIM.SongManager.GetDrumLoops()[0];
        }
        // Set up the play button.
        mPlayPauseButton = gameObject.transform.GetChild(5).GetChild(0).GetComponent<
      Button>();
        mPlayPauseButton.onClick.AddListener(
      OnPlayPauseButtonClicked);
        // Set up the stop button
        mStopButton = gameObject.transform.GetChild(6).GetChild(0).GetComponent<Button>();
        mStopButton.onClick.AddListener(OnStopButtonClicked);
        mStopButton.transform.parent.gameObject.SetActive(false);
        // Set up the BPM slider.
        mBPMSlider = gameObject.transform.GetChild(4).GetComponent<Slider>();
        mBPMSlider.value = mSong.GetBPM();
        mBPMSlider.onValueChanged.AddListener(ChangeBPM);
        // Set up the BPM slider's label.
        mBPMSliderText = mBPMSlider.transform.GetChild(3).GetComponent<Text>();
        mBPMSliderText.text = "BPM: " + mSong.GetBPM().ToString();
        
        // Add a listener for when the song is finished if needed.
        if(!DrumLoopSelector)
        {
            mVIM.AudioFinished.AddListener(SetFinished);
        }
    }
Update()
void ATI_DemoSongButtonHandler.Update () [private]
Definition at line 102 of file ATI_DemoSongButtonHandler.cs.
    {
        if(mFinished)
        {
            mFinished = false;
            mStopButton.transform.parent.gameObject.SetActive(false);
            mPlaying = false;
            mPaused = false;
            mPlayPauseButton.image.sprite = mButtonImages[0];
        }
    }
Member Data Documentation
DrumLoopSelector
bool ATI_DemoSongButtonHandler.DrumLoopSelector = false
Definition at line 19 of file ATI_DemoSongButtonHandler.cs.
mActive
bool ATI_DemoSongButtonHandler.mActive = true [private]
Definition at line 24 of file ATI_DemoSongButtonHandler.cs.
mBPMSlider
Slider ATI_DemoSongButtonHandler.mBPMSlider = null [private]
Definition at line 31 of file ATI_DemoSongButtonHandler.cs.
mBPMSliderText
Text ATI_DemoSongButtonHandler.mBPMSliderText = null [private]
Definition at line 34 of file ATI_DemoSongButtonHandler.cs.
mButtonImages
Sprite [] ATI_DemoSongButtonHandler.mButtonImages = null [private]
The images for the buttons.
Definition at line 33 of file ATI_DemoSongButtonHandler.cs.
mFinished
bool ATI_DemoSongButtonHandler.mFinished = false [private]
Is the song finished?
Definition at line 25 of file ATI_DemoSongButtonHandler.cs.
mPaused
bool ATI_DemoSongButtonHandler.mPaused = false [private]
Is the song paused?
Definition at line 26 of file ATI_DemoSongButtonHandler.cs.
mPlaying
bool ATI_DemoSongButtonHandler.mPlaying = false [private]
Is the song playing?
Definition at line 27 of file ATI_DemoSongButtonHandler.cs.
mPlayPauseButton
Button ATI_DemoSongButtonHandler.mPlayPauseButton = null [private]
Definition at line 28 of file ATI_DemoSongButtonHandler.cs.
mSong
Song ATI_DemoSongButtonHandler.mSong = null [private]
Definition at line 32 of file ATI_DemoSongButtonHandler.cs.
mSongSelectionMenu
Dropdown ATI_DemoSongButtonHandler.mSongSelectionMenu = null [private]
Definition at line 30 of file ATI_DemoSongButtonHandler.cs.
mStopButton
Button ATI_DemoSongButtonHandler.mStopButton = null [private]
The button to stop the song.
Definition at line 29 of file ATI_DemoSongButtonHandler.cs.
mVIM
VirtualInstrumentManager ATI_DemoSongButtonHandler.mVIM = null [private]
Definition at line 35 of file ATI_DemoSongButtonHandler.cs.
The documentation for this class was generated from the following file:
D:/Documents/School Documents/2017Spring/EECS542/VRPianoProject/Assets/Scripts/Audio/Testing/ATI_DemoSongButtonHandler.cs