Private Functions
Functions
void Song.LoadSongFromFile (string aSongFilePath)
Loads a Song file and uses it to set the values for this Song.
Music.DRUM [] Song.ParseDrums (string aStringFromFile)
Parses the drums from a string in a Song file.
Music.PITCH [] Song.ParsePitches (string aStringFromFile)
Parses the pitches from a string in a Song file.
void Song.SearchForHighestPitch ()
Searches through the notes for the highest pitch.
void Song.SearchForLowestPitch ()
Searches through the notes for the lowest pitch.
void Song.UpdateSongType ()
Updates the type of song that the Song is.
Detailed Description
Functions used internally by the Song.
Function Documentation
LoadSongFromFile()
void Song.LoadSongFromFile (string aSongFilePath) [private]
Loads a Song file and uses it to set the values for this Song.
Parameters
in aSongFilePath The path to the Song file.
See also
Song File Format
Definition at line 613 of file Song.cs.
References Song.AddNote(), Music.CreateNote(), Song.mTimeSignature, Song.ParseDrums(), and Song.ParsePitches().
Referenced by Song.Song().
    {
        // Create some variables for parsing the file.
        Music.PITCH[] curNotePitches = null;
        Music.DRUM[] curNoteDrums = null;
        Music.NOTE_LENGTH curNoteLength = Music.NOTE_LENGTH.NONE;
        int splitLineIndex = 0;
        int curNoteMelodyVelocity = 0;
        int curNoteDrumVelocity = 0;
        // Open the file stream.
        StreamReader parser = new StreamReader(aSongFilePath);
        // Get the name of the song
        string curLine = parser.ReadLine();
        mName = curLine;
        // Get the song type.
        curLine = parser.ReadLine();
        string[] splitLine = curLine.Split(';');
        mType = (SongType)int.Parse(splitLine[0]);
        // Get the default BPM
        mBPM = int.Parse(splitLine[1]);
        // Get the time signature
        mTimeSignature.BeatsPerMeasure = int.Parse(splitLine[2]);
        mTimeSignature.BaseBeat = (Music.NOTE_LENGTH)int.Parse(splitLine[3]
      );
        // Get the notes of the song.
        curLine = parser.ReadLine();
        while(curLine != null)
        {
            // Get the line and reset the split line index.
            splitLine = curLine.Split(';');
            splitLineIndex = 0;
            // Get the pitches for the note if needed.
            if(mType != SongType.DrumLoop)
            {
                curNotePitches = ParsePitches(splitLine[splitLineIndex]);
            }
            // Get the drums for the note if needed.
            if(mType != SongType.Melody)
            {
                curNoteDrums = ParseDrums(splitLine[splitLineIndex]);
            }
            // Go to the next section of the line.
            splitLineIndex++;
            // If needed, get the melody note length.
            if(mType != SongType.DrumLoop)
            {
                curNoteLength = (Music.NOTE_LENGTH)int.Parse(splitLine[splitLineIndex]);
                splitLineIndex++;
            }
            // Get the offset from the previous note.
            Music.NOTE_LENGTH offset = (Music.NOTE_LENGTH)int.Parse(
      splitLine[splitLineIndex]);
            splitLineIndex++;
            // Get the velocity/velocities of the note.
            if(mType == SongType.CombinedMelodyAndPercussion)
            {
                string[] velocityString = splitLine[splitLineIndex].Split('|');
                curNoteMelodyVelocity = int.Parse(velocityString[0]);
                curNoteDrumVelocity = int.Parse(velocityString[1]);
            }
            else if(mType == SongType.Melody)
            {
                curNoteMelodyVelocity = int.Parse(splitLine[splitLineIndex]);
            }
            else
            {
                curNoteDrumVelocity = int.Parse(splitLine[splitLineIndex]);
            }
            // Add the note.
            AddNote(Music.CreateNote(curNoteMelodyVelocity, curNoteLength,
      curNotePitches, curNoteDrumVelocity, curNoteDrums, offset));
            // Get the next line
            curLine = parser.ReadLine();
        }
    }
ParseDrums()
Music.DRUM [] Song.ParseDrums (string aStringFromFile) [private]
Parses the drums from a string in a Song file.
Parameters
in aStringFromFile The string to parse.
See also
Song File Format
Definition at line 705 of file Song.cs.
Referenced by Song.LoadSongFromFile().
    {
        Music.DRUM[] parsedDrums = null;
        // Get the entire string of drums.
        string drumString = aStringFromFile;
        if(mType == SongType.CombinedMelodyAndPercussion)
        {
            drumString = aStringFromFile.Split('|')[1];
        }
        // If there are drums for the note, then parse each drum.
        if(drumString != "null")
        {
            // Split the string into individual drums.
            string[] drums = drumString.Split(',');
            // Iterate through each drum and parse it.
            parsedDrums = new Music.DRUM[drums.Length];
            for(int i = 0; i < drums.Length; i++)
            {
                parsedDrums[i] = (Music.DRUM)int.Parse(drums[i]);
            }
        }
        // Return the parsed drums.
        return parsedDrums;
    }
ParsePitches()
Music.PITCH [] Song.ParsePitches (string aStringFromFile) [private]
Parses the pitches from a string in a Song file.
Parameters
in aStringFromFile The string to parse.
See also
Song File Format
Definition at line 739 of file Song.cs.
Referenced by Song.LoadSongFromFile().
    {
        Music.PITCH[] parsedPitches = null;
        // Get the entire string of pitches.
        string pitchString = aStringFromFile;
        if(mType == SongType.CombinedMelodyAndPercussion)
        {
            pitchString = aStringFromFile.Split('|')[0];
        }
        // If there are pitches for the note, then parse each pitch.
        if(pitchString != "null")
        {
            // Split the string into individual pitches.
            string[] pitches = pitchString.Split(',');
            // Iterate through each pitch and parse it.
            parsedPitches = new Music.PITCH[pitches.Length];
            for(int i = 0; i < pitches.Length; i++)
            {
                parsedPitches[i] = (Music.PITCH)int.Parse(pitches[i]);
            }
        }
        // Return the parsed pitches.
        return parsedPitches;
    }
SearchForHighestPitch()
void Song.SearchForHighestPitch () [private]
Searches through the notes for the highest pitch.
This function is called when a note that contains the highest pitch in the song is removed or replaced. We have to then find the new highest pitch in the song.
Definition at line 775 of file Song.cs.
References Song.mHighestPitch, and Song.mNotes.
Referenced by Song.RemoveNote(), and Song.ReplaceNote().
    {
        // Look through each note.
        foreach(Music.CombinedNote note in mNotes)
        {
            // If the note has pitches, then see if it has the highest pitch.
            if(note.MusicalNote.Pitches != null)
            {
                // Look through each pitch in the note.
                foreach(Music.PITCH pitch in note.MusicalNote.Pitches)
                {
                    // Update the highest pitch if needed.
                    if(pitch != Music.PITCH.REST && pitch >
      mHighestPitch)
                    {
                        mHighestPitch = pitch;
                    }
                }
            }
        }
    }
SearchForLowestPitch()
void Song.SearchForLowestPitch () [private]
Searches through the notes for the lowest pitch.
This function is called when a note that contains the lowest pitch in the song is removed or replaced. We have to then find the new lowest pitch in the song.
Definition at line 803 of file Song.cs.
References Song.mLowestPitch, and Song.mNotes.
Referenced by Song.RemoveNote(), and Song.ReplaceNote().
    {
        // Look through each note.
        foreach(Music.CombinedNote note in mNotes)
        {
            // If the note has pitches, then see if it has the lowest pitch.
            if(note.MusicalNote.Pitches != null)
            {
                // Look through each pitch in the note.
                foreach(Music.PITCH pitch in note.MusicalNote.Pitches)
                {
                    // Update the lowest pitch if needed.
                    if(pitch != Music.PITCH.REST && pitch <
      mLowestPitch)
                    {
                        mLowestPitch = pitch;
                    }
                }
            }
        }
    }
UpdateSongType()
void Song.UpdateSongType () [private]
Updates the type of song that the Song is.
Definition at line 827 of file Song.cs.
Referenced by Song.AddNote(), Song.RemoveNote(), and Song.ReplaceNote().
    {
        if(mNumDrumNotes > 0 && mNumMusicalNotes > 0)
        {
            mType = SongType.CombinedMelodyAndPercussion;
        }
        else if(mNumMusicalNotes > 0)
        {
            mType = SongType.Melody;
        }
        else if(mNumDrumNotes > 0)
        {
            mType = SongType.DrumLoop;
        }
        else
        {
            mType = SongType.Empty;
        }
    }