Event Handlers
Functions
void SongCreationManager.OnBPMChange (float aBPM)
Handles a change in the song's default BPM.
void SongCreationManager.OnCreateNote ()
Creates a new note in the song.
void SongCreationManager.OnEditEvent (SC_NoteDisplayPanel aPanel)
Handles when a note panel is selected for editing.
void SongCreationManager.OnLoadSongButtonClicked ()
Handles the Load Song button being clicked by loading the Load Song Dialog.
void SongCreationManager.OnLoadSong (Song aSong)
Loads a Song into the Song Creation Interface.
void SongCreationManager.OnModifyNote ()
Modifies a note in the Song.
void SongCreationManager.OnPlaySong ()
Plays the Song being created.
void SongCreationManager.OnRemoveNote (int aIndex)
Removes a note from the Song being created.
void SongCreationManager.OnSaveSong ()
Saves the Song to a file.
void SongCreationManager.OnVelocityChange (float aVelocity)
Handles a change in the velocity for a note in the Song being created.
void SongCreationManager.UnloadSongCreationInterface ()
Goes back to the AudioTestingInterface scene.
Detailed Description
These are functions called by the SongCreationManager to handle events.
Function Documentation
OnBPMChange()
void SongCreationManager.OnBPMChange (float aBPM)
Handles a change in the song's default BPM.
Parameters
in aBPM The new default BPM.
Gets the value from the BPM slider and sends it to the Song.
See also
SongCreationManager::mBPMSlider
Definition at line 318 of file SongCreationManager.cs.
References Song.SetBPM().
Referenced by SongCreationManager.Awake().
    {
        // Update the BPM slider's label.
        mBPMSlider.transform.GetChild(3).GetComponent<Text>().text = "Default BPM: " + aBPM.
      ToString();
        // Update the song.
        mSong.SetBPM((int)aBPM);
    }
OnCreateNote()
void SongCreationManager.OnCreateNote ()
Creates a new note in the song.
Gets the currently selected values from the modules in the scene uses them to create a new note.
The function won't do anything if no pitches or drums are selected.
See also
SongCreationManager::mNewNoteButton
Definition at line 338 of file SongCreationManager.cs.
References SC_NoteDisplayContainer.AddNote(), Song.AddNote(), Music.CreateNote(), Song.GetNumNotes(), SongCreationManager.SongCreationSelectionContainer.GetSelected(), SC_PitchSelectionContainer.GetSelectedPitches(), SongCreationManager.mLastLength, SC_PitchSelectionContainer.ResetPitches(), and SongCreationManager.SongCreationSelectionContainer.SetSelected().
Referenced by SongCreationManager.Awake(), SongCreationManager.OnEditEvent(), and SongCreationManager.OnModifyNote().
    {
        // Sanity check.
        if(mEditing)
        {
            Assert.IsFalse(!mEditing, "Tried to create a note in the song creation interface when
       we should have been editing one!");
            return;
        }
        // Get the selected pitches
        Music.PITCH[] pitches = mPitchSelector.
      GetSelectedPitches();
        // Get the selected drums.
        Music.PITCH[] drums = mDrumSelector.
      GetSelectedPitches();
        // Make sure that some pitches or drums are actually selected.
        if(pitches != null || drums != null)
        {
            // Get the offset and velocity.
            Music.NOTE_LENGTH length = Music.NOTE_LENGTH.NONE;
            mLastLength = mLengthPanel.GetSelected();
            Music.NOTE_LENGTH offset = mOffsetPanel.
      GetSelected();
            int pitchVelocity = 0;
            int drumVelocity = 0;
            // If the song doesn't have any notes, then set the offset of the first note to none.
            if(mSong.GetNumNotes() == 0)
            {
                offset = Music.NOTE_LENGTH.NONE;
            }
            // Convert the selected pitches from the drum selector into actual drum hits.
            Music.DRUM[] Hits = null;
            if(drums != null)
            {
                Hits = new Music.DRUM[drums.Length];
                for(int i = 0; i < drums.Length; i++)
                {
                    Hits[i] = (Music.DRUM)drums[i];
                }
            }
            // Update the velocity/length for the pitches and drums if needed.
            if(pitches != null)
            {
                pitchVelocity = (int)mVelocitySlider.value;
                length = mLengthPanel.GetSelected();
            }
            if(drums != null)
            {
                drumVelocity = (int)mVelocitySlider.value;
            }
            // Add the note to the song.
            mSong.AddNote(Music.CreateNote(pitchVelocity, length, pitches,
      drumVelocity, Hits, offset));
            // Add the note to the note display.
            mNoteDisplay.AddNote(pitchVelocity, length, pitches, drumVelocity, Hits,
      offset);
            // Reset the pitches.
            mPitchSelector.ResetPitches();
            mDrumSelector.ResetPitches();
            // Update the selection of the offset panel since most cases will use the previous length.
            mOffsetPanel.SetSelected(mLengthPanel.
      GetSelected());
        }
    }
OnEditEvent()
void SongCreationManager.OnEditEvent (SC_NoteDisplayPanel aPanel)
Handles when a note panel is selected for editing.
Parameters
in aPanel The panel representing the note that we're editing.
See also
SongCreationManager::OnModifyNote
Definition at line 415 of file SongCreationManager.cs.
References Song.GetNote(), SC_NoteDisplayPanel.GetNoteIndex(), SongCreationManager.OnCreateNote(), SongCreationManager.OnModifyNote(), SC_PitchSelectionContainer.ResetPitches(), SC_PitchSelectionContainer.SetPitches(), SongCreationManager.SongCreationSelectionContainer.SetSelected(), and SC_NoteDisplayPanel.StopEditing().
Referenced by SC_NoteDisplayPanel.TriggerEditEvent().
    {
        // Handle the case where we begin editing a note.
        if(mEditPanel == null || mEditPanel != aPanel)
        {
            // Handle switching from editing one panel to editing a different one.
            if(mEditPanel != null)
            {
                // Stop editing the current note/note panel.
                mEditPanel.StopEditing();
                // Change the note/note panel being edited to the new one.
                mEditPanel = aPanel;
            }
            // Handle when we start editing a panel.
            else
            {
                // Update the new note button to be a modify note button.
                mNewNoteButton.transform.GetChild(0).GetComponent<Text>().text = "Modify
       Note";
                mNewNoteButton.onClick.RemoveListener(
      OnCreateNote);
                mNewNoteButton.onClick.AddListener(OnModifyNote);
                // Set the variables related to editing a note.
                mEditPanel = aPanel;
                mEditing = true;
            }
            // Get the note being modified.
            Music.CombinedNote noteBeingModified = mSong.
      GetNote(aPanel.GetNoteIndex());
            // Set the pitch selector to have the pitches from the note.
            mPitchSelector.SetPitches(noteBeingModified.MusicalNote.Pitches);
            // Set the drum selector to have the drums from the note.
            Music.PITCH[] drumsAsPitches = null;
            if(noteBeingModified.Drums.Hits != null)
            {
                drumsAsPitches = new Music.PITCH[noteBeingModified.Drums.Hits.Length];
                int index = 0;
                foreach(Music.DRUM drum in noteBeingModified.Drums.Hits)
                {
                    drumsAsPitches[index] = (Music.PITCH)drum;
                    index++;
                }
            }
            mDrumSelector.SetPitches(drumsAsPitches);
            mLengthPanel.SetSelected(noteBeingModified.MusicalNote.Length);
            mOffsetPanel.SetSelected(noteBeingModified.OffsetFromPrevNote);
            mVelocitySlider.value = Mathf.Max(noteBeingModified.Drums.Velocity,
      noteBeingModified.MusicalNote.Velocity);
        }
        // Handle the case where we're editing a note/note panel and it calls this
        // event while it's being edited. This means that the edit should be cancelled.
        else
        {
            // Change the new note button back to its original state.
            mNewNoteButton.transform.GetChild(0).GetComponent<Text>().text = "Insert Note";
            mNewNoteButton.onClick.RemoveListener(OnModifyNote);
            mNewNoteButton.onClick.AddListener(OnCreateNote);
            // Mark that the panel is no longer being edited.
            mEditPanel.StopEditing();
            // Reset the variables related to editing a note.
            mLengthPanel.SetSelected(Music.
      NOTE_LENGTH.Q);
            mOffsetPanel.SetSelected(Music.
      NOTE_LENGTH.NONE);
            mVelocitySlider.value = 100;
            mPitchSelector.ResetPitches();
            mDrumSelector.ResetPitches();
            mEditPanel = null;
            mEditing = false;
        }
    }
OnLoadSong()
void SongCreationManager.OnLoadSong (Song aSong) [private]
Loads a Song into the Song Creation Interface.
Parameters
in aSong The song to load.
See also
LoadSongDialog
Definition at line 513 of file SongCreationManager.cs.
References SC_NoteDisplayContainer.AddNote(), SC_NoteDisplayContainer.ClearNotes(), and Song.GetAllNotes().
Referenced by SongCreationManager.OnLoadSongButtonClicked().
    {
        // Set mSong
        mSong = aSong;
        // Clear the notes.
        mNoteDisplay.ClearNotes();
        // Add the notes of the song to the Note Display Panel.
        List<Music.CombinedNote> notes = mSong.GetAllNotes();
        foreach(Music.CombinedNote note in notes)
        {
            mNoteDisplay.AddNote(note.MusicalNote.Velocity, note.MusicalNote.Length,
      note.MusicalNote.Pitches, note.Drums.Velocity,
                note.Drums.Hits, note.OffsetFromPrevNote);
        }
    }
OnLoadSongButtonClicked()
void SongCreationManager.OnLoadSongButtonClicked () [private]
Handles the Load Song button being clicked by loading the Load Song Dialog.
Definition at line 491 of file SongCreationManager.cs.
References SongCreationManager.OnLoadSong(), and SC_LoadSongDialog.SongSelected.
Referenced by SongCreationManager.Awake().
    {
        // Load prefab.
        GameObject dialogObject = Instantiate(Resources.Load<GameObject>(
      LOAD_SONG_DIALOG_PATH));
        Assert.IsNotNull(dialogObject, "Could not load the SC_LoadSongDialog!");
        // Get the dialog component.
        SC_LoadSongDialog dialog = dialogObject.GetComponent<
      SC_LoadSongDialog>();
        // Put the dialog at the right place in the hierarchy.
        dialog.transform.SetParent(transform);
        // Add the listener.
        dialog.SongSelected.AddListener(OnLoadSong);
    }
OnModifyNote()
void SongCreationManager.OnModifyNote ()
Modifies a note in the Song.
See also
Song::ReplaceNote
Definition at line 535 of file SongCreationManager.cs.
References Music.CreateNote(), Music.DrumToString(), SC_NoteDisplayPanel.GetNoteIndex(), SongCreationManager.SongCreationSelectionContainer.GetSelected(), SC_PitchSelectionContainer.GetSelectedPitches(), SC_NoteDisplayContainer.GetSprites(), Music.NoteToString(), SongCreationManager.OnCreateNote(), Song.ReplaceNote(), SC_PitchSelectionContainer.ResetPitches(), SC_NoteDisplayPanel.SetDrums(), SC_NoteDisplayPanel.SetLengthImage(), SC_NoteDisplayPanel.SetOffset(), SC_NoteDisplayPanel.SetOffsetImage(), SC_NoteDisplayPanel.SetPitches(), SC_NoteDisplayPanel.SetVelocity(), and SC_NoteDisplayPanel.StopEditing().
Referenced by SongCreationManager.OnEditEvent().
    {
        // Make sure that we're actually editing a note.
        if(mEditing)
        {
            // Sanity check.
            if(mEditPanel == null)
            {
                Assert.IsNotNull(mEditPanel, "Tried to modify a note, but the note panel in the
       song creator was null!");
                return;
            }
            // Get the pitches
            Music.PITCH[] pitches = mPitchSelector.
      GetSelectedPitches();
            // Get the drums
            Music.PITCH[] drums = mDrumSelector.
      GetSelectedPitches();
            // Make sure that some pitches or drums are actually selected.
            if(pitches != null || drums != null)
            {
                // Get the index of the note in the song and the images for the length/offset.
                int index = mEditPanel.GetNoteIndex();
                Sprite[] images = mNoteDisplay.GetSprites();
                // Convert the selected pitches from the drum selector into actual drum hits.
                Music.DRUM[] Hits = null;
                if(drums != null)
                {
                    Hits = new Music.DRUM[drums.Length];
                    for(int i = 0; i < drums.Length; i++)
                    {
                        Hits[i] = (Music.DRUM)drums[i];
                    }
                }
                // Set the values of the note struct.
                Music.NOTE_LENGTH length = Music.
      NOTE_LENGTH.NONE;
                Music.NOTE_LENGTH offset = mOffsetPanel.
      GetSelected();
                int pitchVelocity = 0;
                int drumVelocity = 0;
                // Update the velocity for the pitches and drums if needed.
                if(pitches != null)
                {
                    pitchVelocity = (int)mVelocitySlider.value;
                    length = mLengthPanel.GetSelected();
                }
                if(drums != null)
                {
                    drumVelocity = (int)mVelocitySlider.value;
                }
                // Replace the note in the song with the modified note.
                mSong.ReplaceNote(Music.CreateNote(pitchVelocity, length,
      pitches, drumVelocity, Hits, offset), index);
                // Get the string of pitches for the modified note.
                string pitchString = "None";
                if(pitches != null)
                {
                    pitchString = "";
                    for(int i = 0; i < pitches.Length; i++)
                    {
                        if(pitches[i] == Music.PITCH.REST)
                        {
                            pitchString += "Rest ";
                        }
                        else
                        {
                            pitchString += (Music.NoteToString(pitches[i]) + " ");
                        }
                    }
                }
                // Get the string of drums for the modified note.
                string drumString = "None";
                if(Hits != null)
                {
                    drumString = "";
                    foreach(Music.DRUM drum in Hits)
                    {
                        drumString += Music.DrumToString(drum) + " ";
                    }
                }
                // Update the panel representing the note.
                mEditPanel.SetDrums(drumString);
                mEditPanel.SetPitches(pitchString);
                mEditPanel.SetLengthImage(images[(int)length]);
                mEditPanel.SetOffsetImage(images[(int)offset]);
                mEditPanel.SetOffset(offset);
                mEditPanel.SetVelocity(mVelocitySlider.value.ToString(
      ));
                // Mark that the panel is no longer being edited.
                mEditPanel.StopEditing();
                // Update the new note button so that it shows that we're no longer editing a note.
                mNewNoteButton.transform.GetChild(0).GetComponent<Text>().text = "Insert
       Note";
                mNewNoteButton.onClick.RemoveListener(
      OnModifyNote);
                mNewNoteButton.onClick.AddListener(OnCreateNote);
                // Reset the variables related to editing a note.
                mEditPanel = null;
                mEditing = false;
                // Reset the pitch selections.
                mPitchSelector.ResetPitches();
                mDrumSelector.ResetPitches();
            }
        }
    }
OnPlaySong()
void SongCreationManager.OnPlaySong ()
Plays the Song being created.
See also
VirtualInstrumentManager::PlaySongEvent
Definition at line 653 of file SongCreationManager.cs.
References VirtualInstrumentManager.PlaySong.
Referenced by SongCreationManager.Awake().
    {
        mVIM.PlaySong.Invoke(mSong);
    }
OnRemoveNote()
void SongCreationManager.OnRemoveNote (int aIndex)
Removes a note from the Song being created.
Parameters
in aIndex The index of the note to remove in the Song being created.
See also
Song::OnRemoveNote
Definition at line 664 of file SongCreationManager.cs.
References Song.GetNumNotes(), and Song.RemoveNote().
    {
        if(mSong.GetNumNotes() > 0)
        {
            mSong.RemoveNote(aIndex);
        }
    }
OnSaveSong()
void SongCreationManager.OnSaveSong ()
Saves the Song to a file.
This function adds the song to the Song Manager and also saves the Song. to a file.
See also
Song::WriteSongToFile
Definition at line 680 of file SongCreationManager.cs.
References SongManagerClass.AddSong(), Song.GetAllNotes(), Song.GetSongType(), SongCreationManager.mLastLength, Song.ReplaceNote(), VirtualInstrumentManager.SongManager, and Song.WriteSongToFile().
Referenced by SongCreationManager.Awake().
    {
        // Special handling to make drum loops loop properly. The first hit has an initial offset
        // equal to the length used to create the last note.
        if(mSong.GetSongType() == Song.SongType.DrumLoop)
        {
            Music.CombinedNote firstNote = mSong.
      GetAllNotes()[0];
            firstNote.OffsetFromPrevNote = mLastLength;
            mSong.ReplaceNote(firstNote, 0);
        }
        mVIM.SongManager.AddSong(mSong);
        mSong.WriteSongToFile();
    }
OnVelocityChange()
void SongCreationManager.OnVelocityChange (float aVelocity)
Handles a change in the velocity for a note in the Song being created.
Parameters
in aVelocity The new velocity.
See also
SongCreationManager::mVelocitySlider
Definition at line 700 of file SongCreationManager.cs.
Referenced by SongCreationManager.Awake().
    {
        // Update the text of the velocity slider's label.
        mVelocitySlider.transform.GetChild(3).GetComponent<Text>().text = "Velocity: " +
      aVelocity.ToString();
    }
UnloadSongCreationInterface()
void SongCreationManager.UnloadSongCreationInterface ()
Goes back to the AudioTestingInterface scene.
Definition at line 709 of file SongCreationManager.cs.
Referenced by SongCreationManager.Awake().
    {
        SceneManager.UnloadSceneAsync("SongCreationInterfaceScene");
    }