Unity Functions
Modules
Public Functions
Functions
void SC_NoteDisplayPanel.Awake ()
Initializes the SC_NoteDisplayPanel by getting references to its child objects and adding event handlers.
Sprite SC_NoteDisplayPanel.GetLengthImage ()
Gets the image used to represent the length of the note.
SC_MeasureDisplayPanel SC_NoteDisplayPanel.GetMeasurePanel ()
Gets the measure panel that is managing this panel.
int SC_NoteDisplayPanel.GetNoteIndex ()
Gets the index for this note.
Music.NOTE_LENGTH SC_NoteDisplayPanel.GetOffset ()
Gets the offset of this note.
void SC_NoteDisplayPanel.SetDrums (string aDrumString)
Sets the drum string for the note.
void SC_NoteDisplayPanel.SetLengthImage (Sprite aImage)
Sets the image used to represent the length of the note.
void SC_NoteDisplayPanel.SetOffset (Music.NOTE_LENGTH aOffset)
Sets the offset of the note being displayed.
void SC_NoteDisplayPanel.SetOffsetImage (Sprite aImage)
Sets the image used to represent the offset of the note being displayed.
void SC_NoteDisplayPanel.SetParentContainer (SC_MeasureDisplayPanel aParent)
Sets the parent container.
void SC_NoteDisplayPanel.SetNoteIndex (int aIndex)
Sets the index for this note in the Song.
void SC_NoteDisplayPanel.SetPitches (string aPitchString)
Sets the string that represents the pitches in the note being displayed.
void SC_NoteDisplayPanel.SetVelocity (string aVelocityString)
void SC_NoteDisplayPanel.StopEditing ()
Sets that we're no longer editing the note that this panel represents.
Detailed Description
Functions that are called automatically by Unity.
Function Documentation
Awake()
void SC_NoteDisplayPanel.Awake () [private]
Initializes the SC_NoteDisplayPanel by getting references to its child objects and adding event handlers.
Definition at line 50 of file SC_NoteDisplayPanel.cs.
References SC_NoteDisplayPanel.OnRemoveButtonClicked(), and SC_NoteDisplayPanel.TriggerEditEvent().
    {
        // Set the parent handler.
        mSongCreationHandler = GameObject.Find("SongCreationCanvas").GetComponent<
      SongCreationManager>();
        // Set up the OnClick trigger.
        mEditTrigger = gameObject.AddComponent<EventTrigger>();
        EventTrigger.Entry click = new EventTrigger.Entry();
        click.eventID = EventTriggerType.PointerClick;
        click.callback.AddListener((data) => { TriggerEditEvent((PointerEventData)data
      ); });
        mEditTrigger.triggers.Add(click);
        // Setup the children objects.
        mLengthImage = gameObject.transform.GetChild(3).GetChild(1).GetComponent<Image>();
        mOffsetImage = gameObject.transform.GetChild(2).GetChild(1).GetComponent<Image>();
        mPitches = gameObject.transform.GetChild(1).GetChild(0).GetComponent<Text>();
        mVelocity = gameObject.transform.GetChild(4).GetChild(0).GetComponent<Text>();
        mRemoveNoteButton = gameObject.transform.GetChild(0).gameObject.GetComponent<
      Button>();
        mRemoveNoteButton.onClick.AddListener(OnRemoveButtonClicked);
        mDrums = gameObject.transform.GetChild(5).GetChild(0).GetComponent<Text>();
    }
GetLengthImage()
Sprite SC_NoteDisplayPanel.GetLengthImage ()
Gets the image used to represent the length of the note.
Returns
The image used to represent the length of the note.
Definition at line 82 of file SC_NoteDisplayPanel.cs.
    {
        return mLengthImage.sprite;
    }
GetMeasurePanel()
SC_MeasureDisplayPanel SC_NoteDisplayPanel.GetMeasurePanel ()
Gets the measure panel that is managing this panel.
Returns
The parent measure panel.
Definition at line 91 of file SC_NoteDisplayPanel.cs.
References SC_NoteDisplayPanel.mParent.
    {
        return mParent;
    }
GetNoteIndex()
int SC_NoteDisplayPanel.GetNoteIndex ()
Gets the index for this note.
Returns
The index of the note in the Song
Definition at line 100 of file SC_NoteDisplayPanel.cs.
References SC_NoteDisplayPanel.mNoteIndex.
Referenced by SongCreationManager.OnEditEvent(), and SongCreationManager.OnModifyNote().
    {
        return mNoteIndex;
    }
GetOffset()
Music.NOTE_LENGTH SC_NoteDisplayPanel.GetOffset ()
Gets the offset of this note.
Returns
The length of time between the previous note and this one.
Definition at line 109 of file SC_NoteDisplayPanel.cs.
References SC_NoteDisplayPanel.mOffset.
Referenced by SC_MeasureDisplayPanel.OnRemoveNote().
    {
        return mOffset;
    }
SetDrums()
void SC_NoteDisplayPanel.SetDrums (string aDrumString)
Sets the drum string for the note.
Parameters
in aDrumString A string representing the drums of the note.
Definition at line 118 of file SC_NoteDisplayPanel.cs.
Referenced by SC_MeasureDisplayPanel.AddNote(), and SongCreationManager.OnModifyNote().
    {
        mDrums.text = aDrumString;
    }
SetLengthImage()
void SC_NoteDisplayPanel.SetLengthImage (Sprite aImage)
Sets the image used to represent the length of the note.
Parameters
in aImage The image representing the length of the note.
Definition at line 127 of file SC_NoteDisplayPanel.cs.
Referenced by SC_MeasureDisplayPanel.AddNote(), and SongCreationManager.OnModifyNote().
    {
        if(aImage == null)
        {
            mLengthImage.color = new Color32(255, 255, 255, 0);
        }
        else
        {
            mLengthImage.sprite = aImage;
            mLengthImage.color = new Color32(255, 255, 255, 255);
        }
    }
SetNoteIndex()
void SC_NoteDisplayPanel.SetNoteIndex (int aIndex)
Sets the index for this note in the Song.
Parameters
in aIndex The index of the note in the Song.
Definition at line 182 of file SC_NoteDisplayPanel.cs.
Referenced by SC_MeasureDisplayPanel.AddNote(), and SC_NoteDisplayPanel.OnRemoveButtonClicked().
    {
        mNoteIndex = aIndex;
    }
SetOffset()
void SC_NoteDisplayPanel.SetOffset (Music.NOTE_LENGTH aOffset)
Sets the offset of the note being displayed.
Parameters
in aOffset The offset from the previous note.
Definition at line 144 of file SC_NoteDisplayPanel.cs.
References SC_NoteDisplayPanel.mOffset.
Referenced by SC_MeasureDisplayPanel.AddNote(), and SongCreationManager.OnModifyNote().
    {
        mOffset = aOffset;
    }
SetOffsetImage()
void SC_NoteDisplayPanel.SetOffsetImage (Sprite aImage)
Sets the image used to represent the offset of the note being displayed.
Parameters
in aImage The image representing the offset of the note being displayed.
Definition at line 153 of file SC_NoteDisplayPanel.cs.
Referenced by SC_MeasureDisplayPanel.AddNote(), and SongCreationManager.OnModifyNote().
    {
        if(aImage == null)
        {
            mOffsetImage.color = new Color32(255, 255, 255, 0);
        }
        else
        {
            mOffsetImage.sprite = aImage;
            mOffsetImage.color = new Color32(255, 255, 255, 255);
        }
    }
SetParentContainer()
void SC_NoteDisplayPanel.SetParentContainer (SC_MeasureDisplayPanel aParent)
Sets the parent container.
Parameters
in aParent The parent container.
See also
MeasureDisplayPanel::mNotes
Definition at line 173 of file SC_NoteDisplayPanel.cs.
Referenced by SC_MeasureDisplayPanel.AddNote().
    {
        mParent = aParent;
    }
SetPitches()
void SC_NoteDisplayPanel.SetPitches (string aPitchString)
Sets the string that represents the pitches in the note being displayed.
Parameters
in aPitchString The string representing the pitches in the note being displayed.
Definition at line 191 of file SC_NoteDisplayPanel.cs.
Referenced by SC_MeasureDisplayPanel.AddNote(), and SongCreationManager.OnModifyNote().
    {
        mPitches.text = aPitchString;
    }
SetVelocity()
void SC_NoteDisplayPanel.SetVelocity (string aVelocityString)
Sets the string representing the velocity of the note.
Parameters
in aVelocityString The string representing the velocity of the note.
Definition at line 200 of file SC_NoteDisplayPanel.cs.
Referenced by SC_MeasureDisplayPanel.AddNote(), and SongCreationManager.OnModifyNote().
    {
        mVelocity.text = aVelocityString;
    }
StopEditing()
void SC_NoteDisplayPanel.StopEditing ()
Sets that we're no longer editing the note that this panel represents.
Definition at line 208 of file SC_NoteDisplayPanel.cs.
Referenced by SongCreationManager.OnEditEvent(), and SongCreationManager.OnModifyNote().
    {
        // Change the panel background color back to its original color.
        gameObject.GetComponent<Image>().color = new Color32(58, 58, 58, 255);
    }