Private Functions
Functions
void KeyContainer.ClearKeyboard ()
Clears the keyboard.
void KeyContainer.LoadKeys ()
Loads the keys in the container.
Detailed Description
Functions used internally by the KeyContainer
Function Documentation
ClearKeyboard()
void KeyContainer.ClearKeyboard () [private]
Clears the keyboard.
Definition at line 131 of file KeyContainer.cs.
References KeyContainer.mRepresentedPitches.
Referenced by KeyContainer.HandleChangeNoteRangeEvent(), and KeyContainer.HandlePlaySongEvent().
    {
        Assert.IsNotNull(mKeyObjects, "Tried to clear the keyboard, but it was already clear!"
      );
        // Destroy the key objects.
        for(int i = 0; i < mRepresentedPitches.Length; i++)
        {
            DestroyImmediate(mKeyObjects[i], false);
        }
        // Set the array to null.
        mKeyObjects = null;
        // Destroy the key objects.
        for(int i = 0; i < mRepresentedPitches.Length; i++)
        {
            DestroyImmediate(mLessonMarkers[i], false);
        }
        mLessonMarkers = null;
        // Clean up.
        GC.Collect();
        Resources.UnloadUnusedAssets();
    }
LoadKeys()
void KeyContainer.LoadKeys () [private]
Loads the keys in the container.
This function loads each key and sets their position and values.
Definition at line 161 of file KeyContainer.cs.
References BlackKey.BlackKeyPressed, BlackKey.BlackKeyReleased, KeyContainer.HandleBlackKeyPressed(), KeyContainer.HandleBlackKeyReleased(), KeyContainer.HandleWhiteKeyPressed(), KeyContainer.HandleWhiteKeyReleased(), Music.IsPitchABlackKey(), KeyContainer.mRepresentedPitches, KeyContainer.mWhiteKeyWidth, Music.NoteToString(), BlackKey.Pitch, WhiteKey.Pitch, BlackKey.SetParentContainer(), WhiteKey.SetParentContainer(), WhiteKey.WhiteKeyPressed, and WhiteKey.WhiteKeyReleased.
Referenced by KeyContainer.Awake(), KeyContainer.HandleChangeNoteRangeEvent(), and KeyContainer.HandlePlaySongEvent().
    {
        // Destroy the previous keys if needed.
        if(mKeyObjects != null)
        {
           // ClearKeyboard();
        }
        // Load the keys.
        mKeyObjects = new GameObject[mRepresentedPitches.Length];
        mLessonMarkers = new GameObject[mRepresentedPitches.Length];
        Vector3 keyPosition = Vector3.zero;
        int whiteKeyIndex = -1 * (mNumWhiteKeys / 2);
        for(int i = 0; i < mRepresentedPitches.Length; i++)
        {
            // Handle if the key is a black key.
            if(Music.IsPitchABlackKey(mRepresentedPitches[i]))
            {
                // Make an empty black key to help initialize this one.
                BlackKey key = null;
                // Create the black key object.
                mKeyObjects[i] = Instantiate(Resources.Load<GameObject>(
      BLACK_KEY_PATH));
                Assert.IsNotNull(mKeyObjects[i], "Failed to load prefab from " +
      BLACK_KEY_PATH + "!");
                mKeyObjects[i].name = Music.NoteToString(
      mRepresentedPitches[i]) + "Key";
                // Get the black key.
                key = mKeyObjects[i].GetComponent<BlackKey>();
                Assert.IsNotNull(key, "Could not get a reference to the BlackKey script!");
                // Set its pitch.
                key.Pitch = mRepresentedPitches[i];
                // Add listeners to its events.
                key.BlackKeyPressed.AddListener(
      HandleBlackKeyPressed);
                key.BlackKeyReleased.AddListener(
      HandleBlackKeyReleased);
                // Set its position, which is determined by its joint. First, get the spring joint.
                SpringJoint spring = mKeyObjects[i].GetComponent<SpringJoint>();
                Assert.IsNotNull(spring, "Could not get spring joint of black key!");
                // Get the offset position.
                keyPosition = Vector3.zero;
                keyPosition.z += (((float)(whiteKeyIndex - 1) *
      mWhiteKeyWidth) + (mWhiteKeyWidth / 2f));
                // Update the joint's connected anchor.
                spring.autoConfigureConnectedAnchor = false;
                spring.connectedAnchor += keyPosition;
                // Set the new position.
                keyPosition.y = mKeyObjects[i].transform.position.y;
                keyPosition.x = mKeyObjects[i].transform.position.x;
                mKeyObjects[i].transform.position = keyPosition;
                // Put settings back on the spring joint.
                spring.autoConfigureConnectedAnchor = true;
                // Set its place in the hierarchy.
                mKeyObjects[i].transform.SetParent(transform, true);
                Debug.Log("Position of key representing " + Music.
      NoteToString(mRepresentedPitches[i]) + ":" + keyPosition.ToString());
                // Set its parent.
                key.SetParentContainer(this);
            }
            // Handle if the key is a white key.
            else
            {
                // Make an empty black key to help initialize this one.
                WhiteKey key = null;
                // Create the black key object.
                mKeyObjects[i] = Instantiate(Resources.Load<GameObject>(
      WHITE_KEY_PATH));
                Assert.IsNotNull(mKeyObjects[i], "Failed to load prefab from " +
      WHITE_KEY_PATH + "!");
                mKeyObjects[i].name = Music.NoteToString(
      mRepresentedPitches[i]) + "Key";
                // Get the black key.
                key = mKeyObjects[i].GetComponent<WhiteKey>();
                Assert.IsNotNull(key, "Could not get a reference to the BlackKey script!");
                // Set its pitch.
                key.Pitch = mRepresentedPitches[i];
                // Add listeners to its events.
                key.WhiteKeyPressed.AddListener(
      HandleWhiteKeyPressed);
                key.WhiteKeyReleased.AddListener(
      HandleWhiteKeyReleased);
                // Get the hinge joint.
                HingeJoint hinge = mKeyObjects[i].GetComponent<HingeJoint>();
                hinge.autoConfigureConnectedAnchor = false;
                // Get the offset position.
                keyPosition = Vector3.zero;
                keyPosition.z += ((float)whiteKeyIndex * mWhiteKeyWidth);
                // Set the hinge's position.
                hinge.anchor += keyPosition;
                hinge.connectedAnchor += keyPosition;
                // Set the key's position.
                mKeyObjects[i].transform.position += keyPosition;
                hinge.autoConfigureConnectedAnchor = true;
                // Update the index of which white key we're on.
                whiteKeyIndex++;
                // Set its place in the hierarchy.
                mKeyObjects[i].transform.SetParent(transform, true);
                Debug.Log("Position of key representing " + Music.
      NoteToString(mRepresentedPitches[i]) + ":" +
      mKeyObjects[i].transform.position.ToString());
                // Set its parent.
                key.SetParentContainer(this);
            }
            // Load the lesson marker.
            mLessonMarkers[i] = Instantiate(Resources.Load<GameObject>(
      LESSON_MARKER_PATH));
            Assert.IsNotNull(mLessonMarkers[i], "Could not load the lesson marker!");
            // Set the lesson marker position.
            mLessonMarkers[i].transform.SetParent(transform, true);
            keyPosition.y += (mKeyObjects[i].GetComponent<Renderer>().bounds.size.y / 2f) + 0.
      001f;
            keyPosition.x += (mKeyObjects[i].GetComponent<Renderer>().bounds.size.x / 5f);
            mLessonMarkers[i].transform.position = keyPosition;
            mLessonMarkers[i].SetActive(false);
        }
    }