Event Handlers
Functions
void SC_NoteDisplayContainer.HandleFullMeasure (SC_MeasureDisplayPanel aFullMeasure, float aSpillover, int aMelodyVelocity, Music.NOTE_LENGTH aLength, Music.PITCH[] aPitches, int aDrumVelocity, Music.DRUM[] aDrumHits, Music.NOTE_LENGTH aOffsetFromPrevNote)
Handler for when a measure fills up.
void SC_NoteDisplayContainer.HandleMeasureDeleted (SC_MeasureDisplayPanel aMeasure)
Handles when a measure has all of its notes removed by deleting the measure object.
void SC_NoteDisplayContainer.HandleMeasureToggled (SC_MeasureDisplayPanel aMeasure)
Handles when a measure is toggled.
void SC_NoteDisplayContainer.OnRemoveNote ()
Handles when a note is removed by decreasing the count of notes in the song.
Detailed Description
Functions that are called by the SC_NoteDisplayContainer to handle events.
Function Documentation
HandleFullMeasure()
void SC_NoteDisplayContainer.HandleFullMeasure (SC_MeasureDisplayPanel aFullMeasure, float aSpillover, int aMelodyVelocity, Music.NOTE_LENGTH aLength, Music.PITCH [] aPitches, int aDrumVelocity, Music.DRUM [] aDrumHits, Music.NOTE_LENGTH aOffsetFromPrevNote)
Handler for when a measure fills up.
Parameters
in aFullMeasure The measure that filled up.
in aSpillover How much did the new note exceed the limit of the measure.
in aMelodyVelocity The velocity of the pitches in the note.
in aLength The length of the note.
in aPitches The pitches in the note.
in aDrumVelocity The velocity of the drums in the note.
in aDrumHits The drums that are hit for this note.
in aOffsetFromPrevNote The offset from the previous note.
This function creates a new measure and puts the note that couldn't be added to the last measure into the new one.
Definition at line 168 of file SC_NoteDisplayContainer.cs.
References SC_NoteDisplayContainer.HandleMeasureToggled(), and SC_NoteDisplayContainer.mCurrentMeasure.
Referenced by SC_MeasureDisplayPanel.AddNote().
    {
        // Create a new measure toggle.
        GameObject clone = Instantiate(Resources.Load<GameObject>(
      MEASURE_PANEL_PREFAB_PATH));
        Assert.IsNotNull(clone, "Could not load the MeasurePanel prefab!");
        // Add the measure panel to the list.
        mMeasures.Add(clone.AddComponent<SC_MeasureDisplayPanel>());
        // Increase the current measure.
        mCurrentMeasure++;
        // Set the values for the new measure toggle.
        mMeasures[mCurrentMeasure].transform.GetChild(0).GetChild(1).
      GetComponent<Text>().text = "Measure " + (mCurrentMeasure + 1).ToString();
        mMeasures[mCurrentMeasure].transform.SetParent(gameObject.transform);
        mMeasures[mCurrentMeasure].SetParentContainer(this);
        mMeasures[mCurrentMeasure].transform.localScale = Vector3.one;
        mMeasures[mCurrentMeasure].SetToggle(true);
        // Handle Spillover from the previous measure.
        mMeasures[mCurrentMeasure].SetPercentageUsed(0f - aSpillover);
        // Add the note to the new measure.
        mMeasures[mCurrentMeasure].AddNote(mNumNotes, aMelodyVelocity,
      aLength, aPitches, aDrumVelocity, aDrumHits, aOffsetFromPrevNote);
        // Make only the new measure be shown.
        HandleMeasureToggled(mMeasures[
      mCurrentMeasure]);
    }
HandleMeasureDeleted()
void SC_NoteDisplayContainer.HandleMeasureDeleted (SC_MeasureDisplayPanel aMeasure)
Handles when a measure has all of its notes removed by deleting the measure object.
Parameters
in aMeasure The measure that was deleted.
Definition at line 203 of file SC_NoteDisplayContainer.cs.
Referenced by SC_MeasureDisplayPanel.OnRemoveNote().
    {
        // Find the measure that is deleted.
        int index = mMeasures.IndexOf(aMeasure);
        mCurrentMeasure--;
        // Remove the measure and show the previous one if there is one.
        mMeasures.RemoveAt(index);
        if(index > 0)
        {
            mMeasures[index - 1].SetToggle(true);
        }
        // Delete the measure.
        DestroyImmediate(aMeasure.gameObject, false);
    }
HandleMeasureToggled()
void SC_NoteDisplayContainer.HandleMeasureToggled (SC_MeasureDisplayPanel aMeasure)
Handles when a measure is toggled.
Parameters
in aMeasure The measure that was toggled. This function sets only the toggled measure to be shown.
Definition at line 225 of file SC_NoteDisplayContainer.cs.
References SC_MeasureDisplayPanel.SetToggle().
Referenced by SC_NoteDisplayContainer.HandleFullMeasure(), and SC_MeasureDisplayPanel.OnShowToggle().
    {
        // Set that only the toggled measure should be shown.
        foreach(SC_MeasureDisplayPanel measure in
      mMeasures)
        {
            if(aMeasure != measure)
            {
                measure.SetToggle(false);
            }
            else
            {
                measure.SetToggle(true);
            }
        }
    }
OnRemoveNote()
void SC_NoteDisplayContainer.OnRemoveNote ()
Handles when a note is removed by decreasing the count of notes in the song.
See also
SC_MeasureDisplayPanel::RemoveNote
Definition at line 246 of file SC_NoteDisplayContainer.cs.
Referenced by SC_MeasureDisplayPanel.OnRemoveNote().
    {
        mNumNotes--;
    }