Static Functions
Functions
static CombinedNote Music.CreateNote (int aMelodyVelocity, NOTE_LENGTH aLength, PITCH[] aPitches, int aDrumVelocity, DRUM[] aDrumHits, NOTE_LENGTH aOffsetFromPrevNote)
Creates a new CombinedNote struct from the parameters.
static string Music.DrumToString (DRUM aDrum)
Returns a string based on the given DRUM.
static string Music.DrumToString (int aDrumIndex)
Overloaded version of DrumToString(DRUM) that takes an integer instead.
static float Music.GetNoteLengthRelativeToMeasure (NOTE_LENGTH aLength, TimeSignature aTimeSignature)
Gets the percentage that a note length takes up in a measure for the given time signature.
static bool Music.IsPitchABlackKey (int aPitchIndex)
Returns whether or not a note corresponds to a white or black key.
static bool Music.IsPitchABlackKey (PITCH aPitch)
Overloaded function that returns whether or not a note corresponds to a white or black key.
static string Music.NoteToString (PITCH aNoteValue)
Gives a string representing a PITCH.
static string Music.NoteToString (int aNoteValue)
Overloaded function that gives a string representing a pitch. This function takes an integer instead of a PITCH.
static TimeSignature Music.TIME_SIGNATURE_4_4 ()
Returns a 4/4 time signature.
static TimeSignature Music.TIME_SIGNATURE_3_4 ()
Returns a 3/4 time signature.
static TimeSignature Music.TIME_SIGNATURE_6_8 ()
Returns a 6/8 time signature.
Detailed Description
These are functions that can be used to help utilize the enums and structs from the Music class.
Function Documentation
CreateNote()
static CombinedNote Music.CreateNote (int aMelodyVelocity, NOTE_LENGTH aLength, PITCH [] aPitches, int aDrumVelocity, DRUM [] aDrumHits, NOTE_LENGTH aOffsetFromPrevNote) [static]
Creates a new CombinedNote struct from the parameters.
Parameters
in aMelodyVelocity The velocity of the MelodyNote
in aLength The length of the MelodyNote
in aPitches The pitches of the MelodyNote
in aDrumVelocity The velocity of the PercussionNote
in aDrumHits The hits of the PercussionNote
in aOffsetFromPrevNote The offset from the previous CombinedNote.
Definition at line 324 of file Music.cs.
References Music.CombinedNote.Drums, Music.PercussionNote.HasHiHat, Music.PercussionNote.Hits, Music.MelodyNote.Length, Music.CombinedNote.MusicalNote, Music.CombinedNote.OffsetFromPrevNote, Music.MelodyNote.Pitches, Music.MelodyNote.Velocity, and Music.PercussionNote.Velocity.
Referenced by Song.LoadSongFromFile(), SongCreationManager.OnCreateNote(), and SongCreationManager.OnModifyNote().
    {
        // Create the new note struct.
        CombinedNote newNote = new CombinedNote();
        // Set up the melody note.
        newNote.MusicalNote.Velocity = aMelodyVelocity;
        newNote.MusicalNote.Length = aLength;
        newNote.MusicalNote.Pitches = aPitches;
        // Set up the percussion note.
        newNote.Drums.Velocity = aDrumVelocity;
        newNote.Drums.Hits = aDrumHits;
        newNote.Drums.HasHiHat = false;
        if(aDrumHits != null)
        {
            // Check if the new note has any hi hat hits.
            newNote.Drums.HasHiHat = false;
            for(int i = 0; i < aDrumHits.Length; i++)
            {
                if(aDrumHits[i] == Music.DRUM.HIHAT_C ||
                    aDrumHits[i] == Music.DRUM.HIHAT_O ||
                    aDrumHits[i] == Music.DRUM.HIHAT_P)
                {
                    newNote.Drums.HasHiHat = true;
                }
            }
        }
        // Set the offset.
        newNote.OffsetFromPrevNote = aOffsetFromPrevNote;
        // Return the new note.
        return newNote;
    }
DrumToString() [1/2]
static string Music.DrumToString (DRUM aDrum) [static]
Returns a string based on the given DRUM.
Parameters
in aDrum The given DRUM
See also
DRUM_STRING
Definition at line 366 of file Music.cs.
Referenced by SC_MeasureDisplayPanel.AddNote(), DrumKit.CreateFilenames(), SongCreationManager.OnModifyNote(), and SC_PitchSelectionContainer.SetUpAsDrumSelector().
    {
        return DRUM_STRING[(int)aDrum];
    }
DrumToString() [2/2]
static string Music.DrumToString (int aDrumIndex) [static]
Overloaded version of DrumToString(DRUM) that takes an integer instead.
Parameters
in aDrumIndex The index of the drum in the DRUM enum.
See also
DRUM DRUM_STRING
Definition at line 377 of file Music.cs.
    {
        return DRUM_STRING[aDrumIndex];
    }
GetNoteLengthRelativeToMeasure()
static float Music.GetNoteLengthRelativeToMeasure (NOTE_LENGTH aLength, TimeSignature aTimeSignature) [static]
Gets the percentage that a note length takes up in a measure for the given time signature.
Parameters
in aLength the given NOTE_LENGTH that represents the length of a note.
in aTimeSignature The given TimeSignature
Definition at line 387 of file Music.cs.
References Music.TimeSignature.BaseBeat, and Music.TimeSignature.BeatsPerMeasure.
Referenced by SC_MeasureDisplayPanel.AddNote(), and SC_MeasureDisplayPanel.OnRemoveNote().
    {
        // Relate everything to quarter notes.
        float quarterNoteLength = 1f;
        // Get the ratio of quarter note to beat.
        switch(aTimeSignature.BaseBeat)
        {
            case NOTE_LENGTH.E:
                quarterNoteLength *= 2f;
                break;
            default:
                break;
        }
        // Get the percentage that a quarter note takes up in the measure.
        quarterNoteLength /= (float)aTimeSignature.BeatsPerMeasure;
        // Return the percentage that the given note length takes up in a measure.
        switch(aLength)
        {
            case Music.NOTE_LENGTH.T:
                return quarterNoteLength / 8f;
            case Music.NOTE_LENGTH.D_T:
                return 1.5f * quarterNoteLength / 8f;
            case Music.NOTE_LENGTH.S:
                return quarterNoteLength / 4f;
            case Music.NOTE_LENGTH.D_S:
                return 1.5f * quarterNoteLength / 4f;
            case Music.NOTE_LENGTH.E:
                return quarterNoteLength / 2f;
            case Music.NOTE_LENGTH.D_E:
                return 1.5f * quarterNoteLength / 2f;
            case Music.NOTE_LENGTH.Q:
                return quarterNoteLength;
            case Music.NOTE_LENGTH.D_Q:
                return quarterNoteLength * 1.5f;
            case Music.NOTE_LENGTH.H:
                return quarterNoteLength * 2f;
            case Music.NOTE_LENGTH.D_H:
                return quarterNoteLength * 3f;
            case Music.NOTE_LENGTH.W:
                return quarterNoteLength * 4f;
            case Music.NOTE_LENGTH.D_W:
                return quarterNoteLength * 6f;
            default:
                return 0;
        }
    }
IsPitchABlackKey() [1/2]
static bool Music.IsPitchABlackKey (int aPitchIndex) [static]
Returns whether or not a note corresponds to a white or black key.
Parameters
in aPitchIndex The index of the pitch being checked.
Returns
True if the pitch corresponds to a black key. False otherwise.
Definition at line 443 of file Music.cs.
Referenced by KeyContainer.Awake(), KeyContainer.HandleChangeNoteRangeEvent(), KeyContainer.HandlePlaySongEvent(), Music.IsPitchABlackKey(), and KeyContainer.LoadKeys().
    {
        Assert.IsTrue(aPitchIndex >= 0 && aPitchIndex <= MAX_SUPPORTED_NOTES,
            "Tried to find whether a pitch with index " + aPitchIndex.ToString() + " was a black key or
       not, but the pitch was out of range!");
        Assert.IsTrue(aPitchIndex < (int)PITCH.REST, "Tried to see whether a rest note was a black
       key or not!");
        // Get the base pitch (the pitch's place in its octave.)
        int basePitch = aPitchIndex % 12;
        // Check whether the key is a black key or not.
        if(basePitch == 1 || basePitch == 3 || basePitch == 6 || basePitch == 8 || basePitch == 10)
        {
            return true;
        }
        else
        {
            return false;
        }
    }
IsPitchABlackKey() [2/2]
static bool Music.IsPitchABlackKey (PITCH aPitch) [static]
Overloaded function that returns whether or not a note corresponds to a white or black key.
Parameters
in aPitch The pitch being checked.
Returns
True if the pitch corresponds to a black key. False otherwise.
Definition at line 469 of file Music.cs.
References Music.IsPitchABlackKey().
    {
        return IsPitchABlackKey((int)aPitch);
    }
NoteToString() [1/2]
static string Music.NoteToString (PITCH aNoteValue) [static]
Gives a string representing a PITCH.
Parameters
in aNoteValue The PITCH to return a string representation of.
See also
PITCH PITCH_STRING
Definition at line 480 of file Music.cs.
Referenced by SC_MeasureDisplayPanel.AddNote(), Marimba.CreateFilenames(), Piano.CreateFilenames(), WhiteKey.FixedUpdate(), BlackKey.FixedUpdate(), VirtualInstrument.GetAudioDataForPitch(), ATI_NoteRangeSelectionHandler.HandleInstrumentLoaded(), ATI_NoteRangeSelectionHandler.HandleNoteRangeChange(), SC_PitchSelectionContainer.HandlePitchSelection(), VirtualInstrument.LoadAudioClipForPitch(), KeyContainer.LoadKeys(), VirtualInstrumentManager.LoadNoteOutputObjects(), SongCreationManager.OnModifyNote(), VirtualInstrumentManager.OnPlayNoteEvent(), VirtualInstrumentManager.OnReleaseNoteEvent(), and SC_PitchSelectionContainer.SetUpAsPitchSelector().
    {
        return NoteToString((int)aNoteValue);
    }
NoteToString() [2/2]
static string Music.NoteToString (int aNoteValue) [static]
Overloaded function that gives a string representing a pitch. This function takes an integer instead of a PITCH.
Parameters
in aNoteValue The index in the PITCH enum that corresponds to a pitch to return a string representation of.
See also
PITCH PITCH_STRING
Definition at line 491 of file Music.cs.
    {
        int pitchIndex = aNoteValue % 12;
        int octave = aNoteValue / 12;
        return PITCH_STRING[pitchIndex] + octave.ToString();
    }
TIME_SIGNATURE_3_4()
static TimeSignature Music.TIME_SIGNATURE_3_4 () [static]
Returns a 3/4 time signature.
Definition at line 512 of file Music.cs.
References Music.TimeSignature.BaseBeat, and Music.TimeSignature.BeatsPerMeasure.
    {
        TimeSignature returned;
        returned.BeatsPerMeasure = 3;
        returned.BaseBeat = NOTE_LENGTH.Q;
        return returned;
    }
TIME_SIGNATURE_4_4()
static TimeSignature Music.TIME_SIGNATURE_4_4 () [static]
Returns a 4/4 time signature.
Definition at line 501 of file Music.cs.
References Music.TimeSignature.BaseBeat, and Music.TimeSignature.BeatsPerMeasure.
Referenced by SC_MeasureDisplayPanel.AddNote(), SC_MeasureDisplayPanel.OnRemoveNote(), and Song.Song().
    {
        TimeSignature returned;
        returned.BeatsPerMeasure = 4;
        returned.BaseBeat = NOTE_LENGTH.Q;
        return returned;
    }
TIME_SIGNATURE_6_8()
static TimeSignature Music.TIME_SIGNATURE_6_8 () [static]
Returns a 6/8 time signature.
Definition at line 523 of file Music.cs.
References Music.TimeSignature.BaseBeat, and Music.TimeSignature.BeatsPerMeasure.
    {
        TimeSignature returned;
        returned.BeatsPerMeasure = 6;
        returned.BaseBeat = NOTE_LENGTH.E;
        return returned;
    }