Event Handlers
Classes
class SongCreation.PitchSelectionContainer.PitchSelectionTrigger
class SongCreation.SongCreationSelectionContainer.SongCreationSelectionTrigger
Functions
void SongCreation.PitchSelectionContainer.PitchSelectionTrigger.Awake ()
void SongCreation.PitchSelectionContainer.PitchSelectionTrigger.SetHandler (PitchSelectionContainer aHandler)
void SongCreation.PitchSelectionContainer.PitchSelectionTrigger.SetIndex (int aIndex)
void SongCreation.PitchSelectionContainer.PitchSelectionTrigger.SetSelection (bool aSelected)
void SongCreation.PitchSelectionContainer.PitchSelectionTrigger.OnPitchSelected (bool aSelected)
Music.PITCH [] SongCreation.PitchSelectionContainer.GetSelectedPitches ()
void SongCreation.PitchSelectionContainer.ResetPitches ()
void SongCreation.PitchSelectionContainer.SetPitches (Music.PITCH[] aPitches)
Sets the selected pitches.
void SongCreation.PitchSelectionContainer.SetUpDrums ()
void SongCreation.PitchSelectionContainer.SetUpPitches ()
void SongCreation.PitchSelectionContainer.HandlePitchSelection (bool aSelected, int aIndex)
void SongCreation.PitchSelectionContainer.OnRestToggle (bool aOn)
void SongCreation.SongCreationSelectionContainer.SongCreationSelectionTrigger.Awake ()
void SongCreation.SongCreationSelectionContainer.SongCreationSelectionTrigger.SetContainer (SongCreationSelectionContainer aContainer)
void SongCreation.SongCreationSelectionContainer.SongCreationSelectionTrigger.SetSelected (bool aSelected)
void SongCreation.SongCreationSelectionContainer.SongCreationSelectionTrigger.ChangeColor ()
void SongCreation.SongCreationSelectionContainer.SongCreationSelectionTrigger.OnSelected (bool aSelected)
void SongCreation.SongCreationSelectionContainer.Awake ()
Music.NOTE_LENGTH SongCreation.SongCreationSelectionContainer.GetSelected ()
void SongCreation.SongCreationSelectionContainer.SetSelected (Music.NOTE_LENGTH aSelection)
void SongCreation.SongCreationSelectionContainer.HandleToggle (SongCreationSelectionTrigger aTrigger)
void SongCreation.OnBPMChange (float aBPM)
Handles a change in the song's default BPM.
void SongCreation.OnCreateNote ()
Creates a new note in the song.
void SongCreation.OnEditEvent (SC_NoteDisplayPanel aPanel)
Handles when a note panel is selected for editing.
void SongCreation.OnLoadSongButtonClicked ()
Handles the Load Song button being clicked by loading the a song selection dialog.
void SongCreation.OnLoadSong (Song aSong)
Loads a Song into the Song Creation Interface.
void SongCreation.OnModifyNote ()
void SongCreation.OnPlaySong ()
void SongCreation.OnRemoveNote (int aIndex)
void SongCreation.OnSaveSong ()
Saves the song to a file.
void SongCreation.OnVelocityChange (float aVelocity)
void SongCreation.UnloadSongCreationInterface ()
Variables
int SongCreation.PitchSelectionContainer.PitchSelectionTrigger.mIndex = -1
PitchSelectionContainer SongCreation.PitchSelectionContainer.PitchSelectionTrigger.mHandler = null
Toggle SongCreation.PitchSelectionContainer.PitchSelectionTrigger.mToggle
bool SongCreation.PitchSelectionContainer.mRestNote = false
List< int > SongCreation.PitchSelectionContainer.mSelectedPitches = null
PitchSelectionTrigger [] SongCreation.PitchSelectionContainer.mPitchSelectionTriggers = null
Toggle SongCreation.PitchSelectionContainer.mRest = null
Toggle [] SongCreation.PitchSelectionContainer.mPitches = null
bool SongCreation.SongCreationSelectionContainer.SongCreationSelectionTrigger.mSelected = false
SongCreationSelectionContainer SongCreation.SongCreationSelectionContainer.SongCreationSelectionTrigger.mContainer = null
Toggle SongCreation.SongCreationSelectionContainer.SongCreationSelectionTrigger.mToggle = null
int SongCreation.SongCreationSelectionContainer.mSelectedIndex = 0
SongCreationSelectionTrigger [] SongCreation.SongCreationSelectionContainer.mTriggers = null
Detailed Description
These are functions called by the Song Creation Interface to handle events.
Class Documentation
class SongCreation::PitchSelectionContainer::PitchSelectionTrigger
Definition at line 36 of file SongCreation.cs.
Public Member Functions
void SetHandler (PitchSelectionContainer aHandler)
void SetIndex (int aIndex)
void SetSelection (bool aSelected)
void OnPitchSelected (bool aSelected)
Private Member Functions
void Awake ()
Private Attributes
int mIndex = -1
PitchSelectionContainer mHandler = null
Toggle mToggle
class SongCreation::SongCreationSelectionContainer::SongCreationSelectionTrigger
Definition at line 345 of file SongCreation.cs.
Public Member Functions
void SetContainer (SongCreationSelectionContainer aContainer)
void SetSelected (bool aSelected)
void OnSelected (bool aSelected)
Private Member Functions
void Awake ()
void ChangeColor ()
Private Attributes
bool mSelected = false
SongCreationSelectionContainer mContainer = null
Toggle mToggle = null
Function Documentation
Awake() [1/3]
void SongCreation.PitchSelectionContainer.PitchSelectionTrigger.Awake () [private]
Definition at line 48 of file SongCreation.cs.
References SongCreation.PitchSelectionContainer.PitchSelectionTrigger.OnPitchSelected().
            {
                // Get the toggle and add its listener.
                mToggle = gameObject.GetComponent<Toggle>();
                mToggle.onValueChanged.AddListener(OnPitchSelected);
            }
Awake() [2/3]
void SongCreation.SongCreationSelectionContainer.SongCreationSelectionTrigger.Awake () [private]
Definition at line 357 of file SongCreation.cs.
            {
                // Get the toggle and set its listener
                mToggle = gameObject.GetComponent<Toggle>();
                mToggle.onValueChanged.AddListener(OnSelected);
            }
Awake() [3/3]
void SongCreation.SongCreationSelectionContainer.Awake () [private]
Definition at line 441 of file SongCreation.cs.
References SongCreation.SongCreationSelectionContainer.SongCreationSelectionTrigger.SetContainer(), and SongCreation.SongCreationSelectionContainer.SongCreationSelectionTrigger.SetSelected().
        {
            // Set up the triggers.
            mTriggers = new SongCreationSelectionTrigger[13];
            for(int i = 0; i < 13; i++)
            {
                mTriggers[i] = gameObject.transform.GetChild(i + 1).gameObject.AddComponent<
      SongCreationSelectionTrigger>();
                mTriggers[i].SetContainer(this);
                mTriggers[i].SetSelected(false);
            }
            // Set the default selection (Quarter note).
            mTriggers[12].SetSelected(true);
            mSelectedIndex = 12;
        }
ChangeColor()
void SongCreation.SongCreationSelectionContainer.SongCreationSelectionTrigger.ChangeColor () [private]
Definition at line 393 of file SongCreation.cs.
            {
                if(mSelected)
                {
                    mToggle.transform.GetChild(0).GetComponent<Image>().color = new Color32(255,
      255, 255, 118);
                }
                else
                {
                    mToggle.transform.GetChild(0).GetComponent<Image>().color = new Color32(255,
      255, 255, 255);
                }
            }
GetSelected()
Music.NOTE_LENGTH SongCreation.SongCreationSelectionContainer.GetSelected ()
Definition at line 462 of file SongCreation.cs.
Referenced by SongCreation.OnCreateNote(), and SongCreation.OnModifyNote().
        {
            return (Music.NOTE_LENGTH)mSelectedIndex;
        }
GetSelectedPitches()
Music.PITCH [] SongCreation.PitchSelectionContainer.GetSelectedPitches ()
Definition at line 105 of file SongCreation.cs.
Referenced by SongCreation.OnCreateNote(), and SongCreation.OnModifyNote().
        {
            Music.PITCH[] returned = null;
            // If we're currently a rest note, return the rest pitch
            if(mRestNote)
            {
                returned = new Music.PITCH[1];
                returned[0] = Music.PITCH.REST;
            }
            // If there aren't any pitches selected, then return null.
            else if(mSelectedPitches.Count == 0)
            {
                return null;
            }
            // If we're not currently a rest note and some pitches are selected, then return all of the
       selected pitches.
            else
            {
                int index = 0;
                returned = new Music.PITCH[mSelectedPitches.Count];
                foreach(int pitch in mSelectedPitches)
                {
                    returned[index] = (Music.PITCH)mSelectedPitches[index];
                    index++;
                }
            }
            return returned;
        }
HandlePitchSelection()
void SongCreation.PitchSelectionContainer.HandlePitchSelection (bool aSelected, int aIndex)
Definition at line 282 of file SongCreation.cs.
References Music.NoteToString(), and SongCreation.PitchSelectionContainer.PitchSelectionTrigger.SetSelection().
Referenced by SongCreation.PitchSelectionContainer.PitchSelectionTrigger.OnPitchSelected().
        {
            // If this pitch was selected and the note is note currently set to be a rest note,
            // then add it to the list.
            if(aSelected && !mRestNote)
            {
                mSelectedPitches.Add(aIndex);
                foreach(int pitch in mSelectedPitches)
                {
                    Debug.Log(Music.NoteToString(pitch));
                }
            }
            // If the pitch was unselected and the note is not currently set to be a rest note,
            // then remove it from the list.
            else if(!mRestNote)
            {
                mSelectedPitches.Remove(aIndex);
                foreach(int pitch in mSelectedPitches)
                {
                    Debug.Log(Music.NoteToString(pitch));
                }
            }
            // If the pitch was selected and we are currently set to be a rest note, then unselect the
       note.
            else if(aSelected && mRestNote)
            {
                mPitchSelectionTriggers[aIndex].
      SetSelection(false);
            }
        }
HandleToggle()
void SongCreation.SongCreationSelectionContainer.HandleToggle (SongCreationSelectionTrigger aTrigger) [private]
Definition at line 493 of file SongCreation.cs.
References SongCreation.SongCreationSelectionContainer.SongCreationSelectionTrigger.SetSelected().
Referenced by SongCreation.SongCreationSelectionContainer.SongCreationSelectionTrigger.OnSelected().
        {
            // Set all other triggers to unselected.
            for(int i = 0; i < 13; i++)
            {
                if(mTriggers[i] != aTrigger)
                {
                    mTriggers[i].SetSelected(false);
                }
                // Update the current selection.
                else
                {
                    mSelectedIndex = i;
                }
            }
        }
OnBPMChange()
void SongCreation.OnBPMChange (float aBPM)
Handles a change in the song's default BPM.
Parameters
in aBPM The new default BPM.
Gets the value from the BPM slider and sends it to the Song.
Definition at line 617 of file SongCreation.cs.
References Song.SetBPM().
Referenced by SongCreation.Awake().
    {
        // Update the BPM slider's label.
        mBPMSlider.transform.GetChild(3).GetComponent<Text>().text = "Default BPM: " + aBPM.
      ToString();
        // Update the song.
        mSong.SetBPM((int)aBPM);
    }
OnCreateNote()
void SongCreation.OnCreateNote ()
Creates a new note in the song.
Gets the currently selected values from the modules in the scene uses them to create a new note.
The function won't do anything if no pitches or drums are selected.
Definition at line 635 of file SongCreation.cs.
References NoteDisplayContainer.AddNote(), Song.AddNote(), Music.CreateNote(), Song.GetNumNotes(), SongCreation.SongCreationSelectionContainer.GetSelected(), SongCreation.PitchSelectionContainer.GetSelectedPitches(), SongCreation.mLastLength, SongCreation.PitchSelectionContainer.ResetPitches(), and SongCreation.SongCreationSelectionContainer.SetSelected().
Referenced by SongCreation.Awake(), SongCreation.OnEditEvent(), and SongCreation.OnModifyNote().
    {
        // Sanity check.
        if(mEditing)
        {
            Assert.IsFalse(!mEditing, "Tried to create a note in the song creation interface when
       we should have been editing one!");
            return;
        }
        // Get the selected pitches
        Music.PITCH[] pitches = mPitchSelector.
      GetSelectedPitches();
        // Get the selected drums.
        Music.PITCH[] drums = mDrumSelector.
      GetSelectedPitches();
        // Make sure that some pitches or drums are actually selected.
        if(pitches != null || drums != null)
        {
            // Get the offset and velocity.
            Music.NOTE_LENGTH length = Music.NOTE_LENGTH.NONE;
            mLastLength = mLengthPanel.GetSelected();
            Music.NOTE_LENGTH offset = mOffsetPanel.
      GetSelected();
            int pitchVelocity = 0;
            int drumVelocity = 0;
            // If the song doesn't have any notes, then set the offset of the first note to none.
            if(mSong.GetNumNotes() == 0)
            {
                offset = Music.NOTE_LENGTH.NONE;
            }
            // Convert the selected pitches from the drum selector into actual drum hits.
            Music.DRUM[] Hits = null;
            if(drums != null)
            {
                Hits = new Music.DRUM[drums.Length];
                for(int i = 0; i < drums.Length; i++)
                {
                    Hits[i] = (Music.DRUM)drums[i];
                }
            }
            // Update the velocity/length for the pitches and drums if needed.
            if(pitches != null)
            {
                pitchVelocity = (int)mVelocitySlider.value;
                length = mLengthPanel.GetSelected();
            }
            if(drums != null)
            {
                drumVelocity = (int)mVelocitySlider.value;
            }
            // Add the note to the song.
            mSong.AddNote(Music.CreateNote(pitchVelocity, length, pitches,
      drumVelocity, Hits, offset));
            // Add the note to the note display.
            mNoteDisplay.AddNote(pitchVelocity, length, pitches, drumVelocity, Hits,
      offset);
            // Reset the pitches.
            mPitchSelector.ResetPitches();
            mDrumSelector.ResetPitches();
            // Update the selection of the offset panel since most cases will use the previous length.
            mOffsetPanel.SetSelected(mLengthPanel.
      GetSelected());
        }
    }
OnEditEvent()
void SongCreation.OnEditEvent (SC_NoteDisplayPanel aPanel)
Handles when a note panel is selected for editing.
Parameters
in aPanel The panel representing the note that we're editing.
Definition at line 710 of file SongCreation.cs.
References Song.GetNote(), SC_NoteDisplayPanel.GetNoteIndex(), SongCreation.OnCreateNote(), SongCreation.OnModifyNote(), SongCreation.PitchSelectionContainer.ResetPitches(), SongCreation.PitchSelectionContainer.SetPitches(), SongCreation.SongCreationSelectionContainer.SetSelected(), and SC_NoteDisplayPanel.StopEditing().
Referenced by SC_NoteDisplayPanel.TriggerEditEvent().
    {
        // Handle the case where we begin editing a note.
        if(mEditPanel == null || mEditPanel != aPanel)
        {
            // Handle switching from editing one panel to editing a different one.
            if(mEditPanel != null)
            {
                // Stop editing the current note/note panel.
                mEditPanel.StopEditing();
                // Change the note/note panel being edited to the new one.
                mEditPanel = aPanel;
            }
            // Handle when we start editing a panel.
            else
            {
                // Update the new note button to be a modify note button.
                mNewNoteButton.transform.GetChild(0).GetComponent<Text>().text = "Modify
       Note";
                mNewNoteButton.onClick.RemoveListener(
      OnCreateNote);
                mNewNoteButton.onClick.AddListener(OnModifyNote);
                // Set the variables related to editing a note.
                mEditPanel = aPanel;
                mEditing = true;
            }
            // Get the note being modified.
            Music.CombinedNote noteBeingModified = mSong.
      GetNote(aPanel.GetNoteIndex());
            // Set the pitch selector to have the pitches from the note.
            mPitchSelector.SetPitches(noteBeingModified.MusicalNote.Pitches);
            // Set the drum selector to have the drums from the note.
            Music.PITCH[] drumsAsPitches = null;
            if(noteBeingModified.Drums.Hits != null)
            {
                drumsAsPitches = new Music.PITCH[noteBeingModified.Drums.Hits.Length];
                int index = 0;
                foreach(Music.DRUM drum in noteBeingModified.Drums.Hits)
                {
                    drumsAsPitches[index] = (Music.PITCH)drum;
                    index++;
                }
            }
            mDrumSelector.SetPitches(drumsAsPitches);
            mLengthPanel.SetSelected(noteBeingModified.MusicalNote.Length);
            mOffsetPanel.SetSelected(noteBeingModified.OffsetFromPrevNote);
            mVelocitySlider.value = Mathf.Max(noteBeingModified.Drums.Velocity,
      noteBeingModified.MusicalNote.Velocity);
        }
        // Handle the case where we're editing a note/note panel and it calls this
        // event while it's being edited. This means that the edit should be cancelled.
        else
        {
            // Change the new note button back to its original state.
            mNewNoteButton.transform.GetChild(0).GetComponent<Text>().text = "Insert Note";
            mNewNoteButton.onClick.RemoveListener(OnModifyNote);
            mNewNoteButton.onClick.AddListener(OnCreateNote);
            // Mark that the panel is no longer being edited.
            mEditPanel.StopEditing();
            // Reset the variables related to editing a note.
            mLengthPanel.SetSelected(Music.
      NOTE_LENGTH.Q);
            mOffsetPanel.SetSelected(Music.
      NOTE_LENGTH.NONE);
            mVelocitySlider.value = 100;
            mPitchSelector.ResetPitches();
            mDrumSelector.ResetPitches();
            mEditPanel = null;
            mEditing = false;
        }
    }
OnLoadSong()
void SongCreation.OnLoadSong (Song aSong) [private]
Loads a Song into the Song Creation Interface.
Parameters
in aSong The song to load.
Definition at line 806 of file SongCreation.cs.
References NoteDisplayContainer.AddNote(), NoteDisplayContainer.ClearNotes(), and Song.GetNotes().
Referenced by SongCreation.OnLoadSongButtonClicked().
    {
        // Set mSong
        mSong = aSong;
        // Clear the notes.
        mNoteDisplay.ClearNotes();
        // Add the notes of the song to the Note Display Panel.
        List<Music.CombinedNote> notes = mSong.GetNotes();
        foreach(Music.CombinedNote note in notes)
        {
            mNoteDisplay.AddNote(note.MusicalNote.Velocity, note.MusicalNote.Length,
      note.MusicalNote.Pitches, note.Drums.Velocity,
                note.Drums.Hits, note.OffsetFromPrevNote);
        }
    }
OnLoadSongButtonClicked()
void SongCreation.OnLoadSongButtonClicked () [private]
Handles the Load Song button being clicked by loading the a song selection dialog.
Definition at line 786 of file SongCreation.cs.
References SongCreation.OnLoadSong(), and LoadSongDialog.SongSelected.
Referenced by SongCreation.Awake().
    {
        // Load prefab.
        GameObject dialogObject = Instantiate(Resources.Load<GameObject>(
      LOAD_SONG_DIALOG_PATH));
        Assert.IsNotNull(dialogObject, "Could not load the LoadSongDialog!");
        // Get the dialog component.
        LoadSongDialog dialog = dialogObject.GetComponent<
      LoadSongDialog>();
        // Put the dialog at the right place in the hierarchy.
        dialog.transform.SetParent(transform);
        // Add the listener.
        dialog.SongSelected.AddListener(OnLoadSong);
    }
OnModifyNote()
void SongCreation.OnModifyNote ()
Definition at line 824 of file SongCreation.cs.
References Music.CreateNote(), Music.DrumToString(), SC_NoteDisplayPanel.GetNoteIndex(), SongCreation.SongCreationSelectionContainer.GetSelected(), SongCreation.PitchSelectionContainer.GetSelectedPitches(), NoteDisplayContainer.GetSprites(), Music.NoteToString(), SongCreation.OnCreateNote(), Song.ReplaceNote(), SongCreation.PitchSelectionContainer.ResetPitches(), SC_NoteDisplayPanel.SetDrums(), SC_NoteDisplayPanel.SetLengthImage(), SC_NoteDisplayPanel.SetOffset(), SC_NoteDisplayPanel.SetOffsetImage(), SC_NoteDisplayPanel.SetPitches(), SC_NoteDisplayPanel.SetVelocity(), and SC_NoteDisplayPanel.StopEditing().
Referenced by SongCreation.OnEditEvent().
    {
        // Make sure that we're actually editing a note.
        if(mEditing)
        {
            // Sanity check.
            if(mEditPanel == null)
            {
                Assert.IsNotNull(mEditPanel, "Tried to modify a note, but the note panel in the
       song creator was null!");
                return;
            }
            // Get the pitches
            Music.PITCH[] pitches = mPitchSelector.
      GetSelectedPitches();
            // Get the drums
            Music.PITCH[] drums = mDrumSelector.
      GetSelectedPitches();
            // Make sure that some pitches or drums are actually selected.
            if(pitches != null || drums != null)
            {
                // Get the index of the note in the song and the images for the length/offset.
                int index = mEditPanel.GetNoteIndex();
                Sprite[] images = mNoteDisplay.GetSprites();
                // Convert the selected pitches from the drum selector into actual drum hits.
                Music.DRUM[] Hits = null;
                if(drums != null)
                {
                    Hits = new Music.DRUM[drums.Length];
                    for(int i = 0; i < drums.Length; i++)
                    {
                        Hits[i] = (Music.DRUM)drums[i];
                    }
                }
                // Set the values of the note struct.
                Music.NOTE_LENGTH length = Music.
      NOTE_LENGTH.NONE;
                Music.NOTE_LENGTH offset = mOffsetPanel.
      GetSelected();
                int pitchVelocity = 0;
                int drumVelocity = 0;
                // Update the velocity for the pitches and drums if needed.
                if(pitches != null)
                {
                    pitchVelocity = (int)mVelocitySlider.value;
                    length = mLengthPanel.GetSelected();
                }
                if(drums != null)
                {
                    drumVelocity = (int)mVelocitySlider.value;
                }
                // Replace the note in the song with the modified note.
                mSong.ReplaceNote(Music.CreateNote(pitchVelocity, length,
      pitches, drumVelocity, Hits, offset), index);
                // Get the string of pitches for the modified note.
                string pitchString = "None";
                if(pitches != null)
                {
                    pitchString = "";
                    for(int i = 0; i < pitches.Length; i++)
                    {
                        if(pitches[i] == Music.PITCH.REST)
                        {
                            pitchString += "Rest ";
                        }
                        else
                        {
                            pitchString += (Music.NoteToString(pitches[i]) + " ");
                        }
                    }
                }
                // Get the string of drums for the modified note.
                string drumString = "None";
                if(Hits != null)
                {
                    drumString = "";
                    foreach(Music.DRUM drum in Hits)
                    {
                        drumString += Music.DrumToString(drum) + " ";
                    }
                }
                // Update the panel representing the note.
                mEditPanel.SetDrums(drumString);
                mEditPanel.SetPitches(pitchString);
                mEditPanel.SetLengthImage(images[(int)length]);
                mEditPanel.SetOffsetImage(images[(int)offset]);
                mEditPanel.SetOffset(offset);
                mEditPanel.SetVelocity(mVelocitySlider.value.ToString(
      ));
                // Mark that the panel is no longer being edited.
                mEditPanel.StopEditing();
                // Update the new note button so that it shows that we're no longer editing a note.
                mNewNoteButton.transform.GetChild(0).GetComponent<Text>().text = "Insert
       Note";
                mNewNoteButton.onClick.RemoveListener(
      OnModifyNote);
                mNewNoteButton.onClick.AddListener(OnCreateNote);
                // Reset the variables related to editing a note.
                mEditPanel = null;
                mEditing = false;
                // Reset the pitch selections.
                mPitchSelector.ResetPitches();
                mDrumSelector.ResetPitches();
            }
        }
    }
OnPitchSelected()
void SongCreation.PitchSelectionContainer.PitchSelectionTrigger.OnPitchSelected (bool aSelected)
Definition at line 85 of file SongCreation.cs.
References SongCreation.PitchSelectionContainer.HandlePitchSelection().
Referenced by SongCreation.PitchSelectionContainer.PitchSelectionTrigger.Awake(), and SongCreation.PitchSelectionContainer.PitchSelectionTrigger.SetSelection().
            {
                mHandler.HandlePitchSelection(aSelected,
      mIndex);
            }
OnPlaySong()
void SongCreation.OnPlaySong ()
Definition at line 938 of file SongCreation.cs.
References VirtualInstrumentManager.PlaySong.
Referenced by SongCreation.Awake().
    {
        mVIM.PlaySong.Invoke(mSong);
    }
OnRemoveNote()
void SongCreation.OnRemoveNote (int aIndex)
Definition at line 944 of file SongCreation.cs.
References Song.GetNumNotes(), and Song.RemoveNote().
    {
        if(mSong.GetNumNotes() > 0)
        {
            mSong.RemoveNote(aIndex);
        }
    }
OnRestToggle()
void SongCreation.PitchSelectionContainer.OnRestToggle (bool aOn)
Definition at line 313 of file SongCreation.cs.
References SongCreation.PitchSelectionContainer.PitchSelectionTrigger.SetSelection().
Referenced by SongCreation.PitchSelectionContainer.SetUpPitches().
        {
            mRestNote = aOn;
            Debug.Log("Rest toggle: " + aOn);
            // If this note is now a rest note, then make sure that no other pitches are selected.
            if(mRestNote)
            {
                foreach(int pitch in mSelectedPitches)
                {
                    mPitchSelectionTriggers[pitch].
      SetSelection(false);
                }
            }
            // If this note is no longer a rest note, then restore the selected pitches.
            else
            {
                foreach(int pitch in mSelectedPitches)
                {
                    mPitchSelectionTriggers[pitch].
      SetSelection(true);
                }
            }
        }
OnSaveSong()
void SongCreation.OnSaveSong ()
Saves the song to a file.
This function adds the song to the SongManager and also saves the song to a file.
Definition at line 958 of file SongCreation.cs.
References SongManagerClass.AddSong(), Song.GetNotes(), Song.GetSongType(), SongCreation.mLastLength, Song.ReplaceNote(), VirtualInstrumentManager.SongManager, and Song.WriteSongToFile().
Referenced by SongCreation.Awake().
    {
        // Special handling to make drum loops loop properly. The first hit has an initial offset
        // equal to the length used to create the last note.
        if(mSong.GetSongType() == Song.SongType.DrumLoop)
        {
            Music.CombinedNote firstNote = mSong.GetNotes()[0];
            firstNote.OffsetFromPrevNote = mLastLength;
            mSong.ReplaceNote(firstNote, 0);
        }
        mVIM.SongManager.AddSong(mSong);
        mSong.WriteSongToFile();
    }
OnSelected()
void SongCreation.SongCreationSelectionContainer.SongCreationSelectionTrigger.OnSelected (bool aSelected)
Definition at line 411 of file SongCreation.cs.
References SongCreation.SongCreationSelectionContainer.HandleToggle().
            {
                // If this object is now selected, then change the color and send it to the handler.
                if(aSelected)
                {
                    mSelected = aSelected;
                    ChangeColor();
                    mContainer.HandleToggle(this);
                }
                // This object can not be unselected by clicking on it. Set the value back to selected.
                else
                {
                    mToggle.onValueChanged.RemoveListener(OnSelected);
                    mToggle.isOn = true;
                    mToggle.onValueChanged.AddListener(OnSelected);
                }
            }
OnVelocityChange()
void SongCreation.OnVelocityChange (float aVelocity)
Definition at line 974 of file SongCreation.cs.
Referenced by SongCreation.Awake().
    {
        // Update the text of the velocity slider's label.
        mVelocitySlider.transform.GetChild(3).GetComponent<Text>().text = "Velocity: " +
      aVelocity.ToString();
    }
ResetPitches()
void SongCreation.PitchSelectionContainer.ResetPitches ()
Definition at line 135 of file SongCreation.cs.
References SongCreation.PitchSelectionContainer.PitchSelectionTrigger.SetSelection().
Referenced by SongCreation.OnCreateNote(), SongCreation.OnEditEvent(), SongCreation.OnModifyNote(), and SongCreation.PitchSelectionContainer.SetPitches().
        {
            // Reset the child objects.
            foreach(int pitch in mSelectedPitches)
            {
                mPitchSelectionTriggers[pitch].
      SetSelection(false);
            }
            // Update the rest note pitch.
            mRestNote = false;
            // Clear the list.
            mSelectedPitches.Clear();
        }
SetContainer()
void SongCreation.SongCreationSelectionContainer.SongCreationSelectionTrigger.SetContainer (SongCreationSelectionContainer aContainer)
Definition at line 369 of file SongCreation.cs.
Referenced by SongCreation.SongCreationSelectionContainer.Awake().
            {
                mContainer = aContainer;
            }
SetHandler()
void SongCreation.PitchSelectionContainer.PitchSelectionTrigger.SetHandler (PitchSelectionContainer aHandler)
Definition at line 60 of file SongCreation.cs.
Referenced by SongCreation.PitchSelectionContainer.SetUpDrums(), and SongCreation.PitchSelectionContainer.SetUpPitches().
            {
                mHandler = aHandler;
            }
SetIndex()
void SongCreation.PitchSelectionContainer.PitchSelectionTrigger.SetIndex (int aIndex)
Definition at line 66 of file SongCreation.cs.
Referenced by SongCreation.PitchSelectionContainer.SetUpDrums(), and SongCreation.PitchSelectionContainer.SetUpPitches().
            {
                mIndex = aIndex;
            }
SetPitches()
void SongCreation.PitchSelectionContainer.SetPitches (Music.PITCH [] aPitches)
Sets the selected pitches.
Parameters
in aPitches The pitches that should be selected.
Definition at line 155 of file SongCreation.cs.
References SongCreation.PitchSelectionContainer.ResetPitches(), and SongCreation.PitchSelectionContainer.PitchSelectionTrigger.SetSelection().
Referenced by SongCreation.OnEditEvent().
        {
            // Reset the pitches.
            ResetPitches();
            // Make sure that there are pitches to set.
            if(aPitches != null)
            {
                // Set the pitches
                foreach(Music.PITCH pitch in aPitches)
                {
                    if(pitch != Music.PITCH.REST)
                    {
                        mPitchSelectionTriggers[(int)pitch].SetSelection(true);
                        mSelectedPitches.Add((int)pitch);
                    }
                    else
                    {
                        mRestNote = true;
                        mRest.isOn = true;
                    }
                }
            }
        }
SetSelected() [1/2]
void SongCreation.SongCreationSelectionContainer.SongCreationSelectionTrigger.SetSelected (bool aSelected)
Definition at line 375 of file SongCreation.cs.
Referenced by SongCreation.SongCreationSelectionContainer.Awake(), SongCreation.SongCreationSelectionContainer.HandleToggle(), and SongCreation.SongCreationSelectionContainer.SetSelected().
            {
                mSelected = aSelected;
                // Change the color to indicate that this is or isn't the selected object
                ChangeColor();
                // Set the value of the toggle.
                mToggle.onValueChanged.RemoveListener(OnSelected);
                mToggle.isOn = aSelected;
                mToggle.onValueChanged.AddListener(OnSelected);
            }
SetSelected() [2/2]
void SongCreation.SongCreationSelectionContainer.SetSelected (Music.NOTE_LENGTH aSelection)
Definition at line 468 of file SongCreation.cs.
References SongCreation.SongCreationSelectionContainer.SongCreationSelectionTrigger.SetSelected().
Referenced by SongCreation.Awake(), SongCreation.OnCreateNote(), and SongCreation.OnEditEvent().
        {
            // Update the private variable.
            mSelectedIndex = (int)aSelection;
            // Update the child objects.
            for(int i = 0; i < 13; i++)
            {
                if(i != mSelectedIndex)
                {
                    mTriggers[i].SetSelected(false);
                }
                else
                {
                    mTriggers[i].SetSelected(true);
                }
            }
        }
SetSelection()
void SongCreation.PitchSelectionContainer.PitchSelectionTrigger.SetSelection (bool aSelected)
Definition at line 72 of file SongCreation.cs.
References SongCreation.PitchSelectionContainer.PitchSelectionTrigger.OnPitchSelected().
Referenced by SongCreation.PitchSelectionContainer.HandlePitchSelection(), SongCreation.PitchSelectionContainer.OnRestToggle(), SongCreation.PitchSelectionContainer.ResetPitches(), and SongCreation.PitchSelectionContainer.SetPitches().
            {
                // Update the toggle switch.
                mToggle.onValueChanged.RemoveListener(OnPitchSelected);
                mToggle.isOn = aSelected;
                mToggle.onValueChanged.AddListener(OnPitchSelected);
            }
SetUpDrums()
void SongCreation.PitchSelectionContainer.SetUpDrums ()
Definition at line 182 of file SongCreation.cs.
References Music.DrumToString(), Music.MAX_SUPPORTED_DRUMS, SongCreation.PitchSelectionContainer.PitchSelectionTrigger.SetHandler(), and SongCreation.PitchSelectionContainer.PitchSelectionTrigger.SetIndex().
Referenced by SongCreation.Awake().
        {
            // Create the list of selected pitches, the array of toggle switches, and the array of
       triggers.
            mSelectedPitches = new List<int>();
            mPitches = new Toggle[Music.MAX_SUPPORTED_DRUMS];
            mPitchSelectionTriggers = new PitchSelectionTrigger[
      Music.MAX_SUPPORTED_DRUMS];
            // Get the first toggle switch and set its text
            mPitches[0] = gameObject.transform.GetChild(0).GetComponent<Toggle>();
            mPitches[0].transform.GetChild(1).GetComponent<Text>().text = "KICK_1";
            // Set up the first pitch selection trigger.
            mPitchSelectionTriggers[0] = mPitches[0].gameObject.AddComponent<
      PitchSelectionTrigger>();
            mPitchSelectionTriggers[0].SetHandler(this);
            mPitchSelectionTriggers[0].SetIndex(0);
            mPitchSelectionTriggers[0].SetSelection(false);
            // Clone the first pitch object and modify it for each drum.
            for(int i = 1; i < Music.MAX_SUPPORTED_DRUMS; i++)
            {
                // Copy the first drum and set its parent.
                mPitches[i] = Instantiate(mPitches[0]).GetComponent<Toggle>();
                mPitches[i].transform.SetParent(gameObject.transform);
                // Set the copy's text
                mPitches[i].transform.GetChild(1).GetComponent<Text>().text =
      Music.DrumToString(i);
                // Set up the clone's PitchSelectionTrigger.
                mPitchSelectionTriggers[i] = mPitches[i].GetComponent<PitchSelectionTrigger>();
                mPitchSelectionTriggers[i].SetIndex(i);
                mPitchSelectionTriggers[i].SetHandler(this);
            }
            // Make sure that everything is sized appropriately.
            mPitches[0].transform.localScale = mPitches[1].transform.localScale;
        }
SetUpPitches()
void SongCreation.PitchSelectionContainer.SetUpPitches ()
Definition at line 221 of file SongCreation.cs.
References Music.MAX_SUPPORTED_NOTES, Music.NoteToString(), SongCreation.PitchSelectionContainer.OnRestToggle(), SongCreation.PitchSelectionContainer.PitchSelectionTrigger.SetHandler(), and SongCreation.PitchSelectionContainer.PitchSelectionTrigger.SetIndex().
        {
            // Create the list of selected pitches, the array of toggle switches, and the array of
       triggers.
            mSelectedPitches = new List<int>();
            mPitches = new Toggle[Music.MAX_SUPPORTED_NOTES + 1];
            mPitchSelectionTriggers = new PitchSelectionTrigger[
      Music.MAX_SUPPORTED_NOTES + 1];
            // Get the first toggle switch and set its text
            mPitches[0] = gameObject.transform.GetChild(0).GetComponent<Toggle>();
            mPitches[0].transform.GetChild(1).GetComponent<Text>().text = "C0";
            // Set up the first pitch selection trigger.
            mPitchSelectionTriggers[0] = mPitches[0].gameObject.AddComponent<
      PitchSelectionTrigger>();
            mPitchSelectionTriggers[0].SetHandler(this);
            mPitchSelectionTriggers[0].SetIndex(0);
            mPitchSelectionTriggers[0].SetSelection(false);
            // Clone the first pitch object and modify it for each pitch.
            string temp = null;
            for(int i = 1; i < Music.MAX_SUPPORTED_NOTES; i++)
            {
                // Copy the first pitch and set its parent.
                mPitches[i] = Instantiate(mPitches[0]).GetComponent<Toggle>();
                mPitches[i].transform.SetParent(gameObject.transform);
                // Set the copy's text.
                temp = Music.NoteToString(i);
                if(temp.Contains("S"))
                {
                    char[] tempArray = temp.ToCharArray();
                    tempArray[1] = '#';
                    temp = new string(tempArray);
                }
                mPitches[i].transform.GetChild(1).GetComponent<Text>().text = temp;
                // Set up the clone's PitchSelectionTrigger.
                mPitchSelectionTriggers[i] = mPitches[i].GetComponent<PitchSelectionTrigger>();
                mPitchSelectionTriggers[i].SetIndex(i);
                mPitchSelectionTriggers[i].SetHandler(this);
            }
            // Make sure that everything is sized appropriately.
            mPitches[0].transform.localScale = mPitches[1].transform.localScale;
            // Create the rest note selection.
            mRest = Instantiate(mPitches[0]).GetComponent<Toggle>();
            DestroyImmediate(mRest.GetComponent<PitchSelectionTrigger>(), false);
            mRest.transform.SetParent(gameObject.transform);
            mRest.onValueChanged.AddListener(OnRestToggle);
            mRest.transform.GetChild(1).GetComponent<Text>().text = "Rest";
            mRest.transform.localScale = mPitches[1].transform.localScale;
        }
UnloadSongCreationInterface()
void SongCreation.UnloadSongCreationInterface ()
Definition at line 981 of file SongCreation.cs.
Referenced by SongCreation.Awake().
    {
        SceneManager.UnloadSceneAsync("SongCreationInterfaceScene");
    }
Variable Documentation
mContainer
SongCreationSelectionContainer SongCreation.SongCreationSelectionContainer.SongCreationSelectionTrigger.mContainer = null [private]
Definition at line 351 of file SongCreation.cs.
mHandler
PitchSelectionContainer SongCreation.PitchSelectionContainer.PitchSelectionTrigger.mHandler = null [private]
Definition at line 42 of file SongCreation.cs.
mIndex
int SongCreation.PitchSelectionContainer.PitchSelectionTrigger.mIndex = -1 [private]
Definition at line 41 of file SongCreation.cs.
mPitches
Toggle [] SongCreation.PitchSelectionContainer.mPitches = null [private]
Definition at line 98 of file SongCreation.cs.
mPitchSelectionTriggers
PitchSelectionTrigger [] SongCreation.PitchSelectionContainer.mPitchSelectionTriggers = null [private]
Definition at line 96 of file SongCreation.cs.
mRest
Toggle SongCreation.PitchSelectionContainer.mRest = null [private]
Definition at line 97 of file SongCreation.cs.
mRestNote
bool SongCreation.PitchSelectionContainer.mRestNote = false [private]
Definition at line 94 of file SongCreation.cs.
mSelected
bool SongCreation.SongCreationSelectionContainer.SongCreationSelectionTrigger.mSelected = false [private]
Definition at line 350 of file SongCreation.cs.
mSelectedIndex
int SongCreation.SongCreationSelectionContainer.mSelectedIndex = 0 [private]
Definition at line 434 of file SongCreation.cs.
mSelectedPitches
List<int> SongCreation.PitchSelectionContainer.mSelectedPitches = null [private]
Definition at line 95 of file SongCreation.cs.
mToggle [1/2]
Toggle SongCreation.PitchSelectionContainer.PitchSelectionTrigger.mToggle [private]
Definition at line 43 of file SongCreation.cs.
mToggle [2/2]
Toggle SongCreation.SongCreationSelectionContainer.SongCreationSelectionTrigger.mToggle = null [private]
Definition at line 352 of file SongCreation.cs.
mTriggers
SongCreationSelectionTrigger [] SongCreation.SongCreationSelectionContainer.mTriggers = null [private]
Definition at line 435 of file SongCreation.cs.