Private Functions
Functions
void VirtualInstrumentManager.LoadNoteOutputObjects ()
Loads each NoteOutputObject that is used to output the audio.
void VirtualInstrumentManager.SetUpEvents ()
Sets up the events and adds their listeners. Should only be called from VirtualInstrumentManager::Awake().
void VirtualInstrumentManager.SetDefaultValues ()
Sets the default values for the VirtualInstrumentManager. Should only be called from VirtualInstrumentManager::Awake().
Detailed Description
These are functions that the VirtualInstrumentManager uses internally to perform its tasks.
Function Documentation
LoadNoteOutputObjects()
void VirtualInstrumentManager.LoadNoteOutputObjects () [private]
Loads each NoteOutputObject that is used to output the audio.
This function loads a NoteOutputObject for every currently playable note, and uses the loaded VirtualInstrument to set the audio data that they will output.
See also
NoteOutputObject
Definition at line 521 of file VirtualInstrumentManager.cs.
References VirtualInstrument.GetAudioDataForPitch(), VirtualInstrument.GetBuiltInDynamicsThresholds(), VirtualInstrumentManager.mActiveNotes, VirtualInstrumentManager.mMixer, VirtualInstrumentManager.mNumActiveNotes, Music.NoteToString(), NoteOutputObject.SetAudioData(), NoteOutputObject.SetLoop(), and NoteOutputObject.SetVIM().
Referenced by VirtualInstrumentManager.OnChangeNoteRangeEvent(), and VirtualInstrumentManager.OnInstrumentLoaded().
    {
        Assert.IsNotNull(mInstrument, "Tried to load NoteOutputObjects when the instrument was
       null!");
        if(mOutputs == null)
        {
            // Initialize the array of NoteOutputObjects.
            mOutputs = new NoteOutputObject[
      mNumActiveNotes];
            // For each note, clone a NoteOutputObject.
            GameObject clone = null;
            for(int i = 0; i < mNumActiveNotes; i++)
            {
                clone = Instantiate(Resources.Load<GameObject>("Audio/Prefabs/NoteOutputObjectPrefab"))
      ;
                clone.transform.position = transform.position;
                mOutputs[i] = clone.GetComponent<NoteOutputObject>();
                clone = null;
            }
        }
        // Set the audio data of the NoteOutputObject and make sure that they don't loop..
        for(int i = 0; i < mNumActiveNotes; i++)
        {
            mOutputs[i].gameObject.name = Music.NoteToString(
      mActiveNotes[i]) + "NoteOutputObjectContainer";
            mOutputs[i].SetAudioData(mInstrument.
      GetAudioDataForPitch(mActiveNotes[i]), mMixer,
      mInstrument.GetBuiltInDynamicsThresholds());
            mOutputs[i].SetLoop(false);
            mOutputs[i].SetVIM(this);
        }
        // Cleanup.
        GC.Collect();
        Resources.UnloadUnusedAssets();
        // Set that we're ready for note events.
        mReady = true;
        Debug.Log("NoteOutputObjects are loaded");
    }
SetDefaultValues()
void VirtualInstrumentManager.SetDefaultValues () [private]
Sets the default values for the VirtualInstrumentManager. Should only be called from VirtualInstrumentManager::Awake().
Definition at line 606 of file VirtualInstrumentManager.cs.
References VirtualInstrumentManager.DEFAULT_HIGHEST_PITCH, VirtualInstrumentManager.DEFAULT_INSTRUMENT_TYPE, VirtualInstrumentManager.DEFAULT_LOWEST_PITCH, VirtualInstrumentManager.mActiveNotes, VirtualInstrumentManager.mHighestActiveNote, VirtualInstrumentManager.mInstrumentType, VirtualInstrumentManager.mLowestActiveNote, VirtualInstrumentManager.mNumActiveNotes, NoteOutputObject.SetLoop(), NoteOutputObject.SetVIM(), and NoteOutputObject.ShouldNotifyWhenFinished().
Referenced by VirtualInstrumentManager.Awake().
    {
        mMixer = Resources.Load<AudioMixer>("Audio/VirtualInstrument/VirtualInstrumentAudioMixer");
        Assert.IsNotNull(mMixer, "Audio mixer was unable to load!");
        // Set the active notes.
        mLowestActiveNote = DEFAULT_LOWEST_PITCH;
        mHighestActiveNote = DEFAULT_HIGHEST_PITCH;
        mNumActiveNotes = (int)mHighestActiveNote - (int)
      mLowestActiveNote + 1;
        mActiveNotes = new Music.PITCH[mNumActiveNotes];
        for(int i = 0; i < mNumActiveNotes; i++)
        {
            mActiveNotes[i] = (Music.PITCH)(i + (int)
      mLowestActiveNote);
        }
        // Set the instrument type
        mInstrumentType = DEFAULT_INSTRUMENT_TYPE;
        // Initialize the song and drum loop outputs.
        GameObject songOutputContainer = Instantiate(Resources.Load<GameObject>("
      Audio/Prefabs/NoteOutputObjectPrefab"));
        Assert.IsNotNull(songOutputContainer, "Could not load NoteOutputObject prefab!");
        songOutputContainer.name = "Song Output";
        songOutputContainer.transform.position = transform.position;
        mSongOutput = songOutputContainer.GetComponent<
      NoteOutputObject>();
        mSongOutput.SetLoop(false);
        mSongOutput.SetVIM(this);
        mSongOutput.ShouldNotifyWhenFinished(true);
        GameObject drumOutputContainer = Instantiate(Resources.Load<GameObject>("
      Audio/Prefabs/NoteOutputObjectPrefab"));
        Assert.IsNotNull(songOutputContainer, "Could not load NoteOutputObject prefab!");
        drumOutputContainer.name = "Drum Loop Output";
        drumOutputContainer.transform.position = transform.position;
        mDrumLoopOutput = drumOutputContainer.GetComponent<
      NoteOutputObject>();
        mDrumLoopOutput.SetLoop(true);
        mDrumLoopOutput.SetVIM(this);
    }
SetUpEvents()
void VirtualInstrumentManager.SetUpEvents () [private]
Sets up the events and adds their listeners. Should only be called from VirtualInstrumentManager::Awake().
Definition at line 563 of file VirtualInstrumentManager.cs.
References VirtualInstrumentManager.OnChangeInstrumentEvent(), VirtualInstrumentManager.OnChangeNoteRangeEvent(), VirtualInstrumentManager.OnInstrumentLoaded(), VirtualInstrumentManager.OnModifyEchoFilterEvent(), VirtualInstrumentManager.OnModifyReverbFilterEvent(), VirtualInstrumentManager.OnPauseDrumLoopEvent(), VirtualInstrumentManager.OnPauseSongEvent(), VirtualInstrumentManager.OnPlayDrumLoopEvent(), VirtualInstrumentManager.OnPlayNoteEvent(), VirtualInstrumentManager.OnPlaySongEvent(), VirtualInstrumentManager.OnReleaseNoteEvent(), VirtualInstrumentManager.OnResumeDrumLoopEvent(), VirtualInstrumentManager.OnResumeSongEvent(), VirtualInstrumentManager.OnStopDrumLoopEvent(), and VirtualInstrumentManager.OnStopSongEvent().
Referenced by VirtualInstrumentManager.Awake().
    {
        // Initialize the events.
        AudioFinished = new AudioFinishedEvent();
        ChangeNoteRange = new ChangeNoteRangeEvent();
        ChangeInstrument = new ChangeInstrumentEvent();
        InstrumentLoaded = new InstrumentLoadedEvent();
        ModifyEchoFilter = new ModifyEchoFilterEvent();
        ModifyReverbFilter = new ModifyReverbFilterEvent();
        PauseDrumLoop = new PauseDrumLoopEvent();
        PauseSong = new PauseSongEvent();
        PlayDrumLoop = new PlayDrumLoopEvent();
        PlayNote = new PlayNoteEvent();
        PlaySong = new PlaySongEvent();
        ReleaseNote = new ReleaseNoteEvent();
        ResumeDrumLoop = new ResumeDrumLoopEvent();
        ResumeSong = new ResumeSongEvent();
        StopDrumLoop = new StopDrumLoopEvent();
        StopSong = new StopSongEvent();
        // Add their listeners.
        ChangeNoteRange.AddListener(OnChangeNoteRangeEvent);
        ChangeInstrument.AddListener(OnChangeInstrumentEvent);
        InstrumentLoaded.AddListener(OnInstrumentLoaded);
        ModifyEchoFilter.AddListener(OnModifyEchoFilterEvent);
        ModifyReverbFilter.AddListener(
      OnModifyReverbFilterEvent);
        PauseDrumLoop.AddListener(OnPauseDrumLoopEvent);
        PauseSong.AddListener(OnPauseSongEvent);
        PlayDrumLoop.AddListener(OnPlayDrumLoopEvent);
        PlayNote.AddListener(OnPlayNoteEvent);
        PlaySong.AddListener(OnPlaySongEvent);
        ReleaseNote.AddListener(OnReleaseNoteEvent);
        ResumeDrumLoop.AddListener(OnResumeDrumLoopEvent);
        ResumeSong.AddListener(OnResumeSongEvent);
        StopDrumLoop.AddListener(OnStopDrumLoopEvent);
        StopSong.AddListener(OnStopSongEvent);
    }