Unity Functions
Functions
void VirtualInstrumentManager.Awake ()
Called when the object is created. Sets the default values, sets up the events, and begins loading the instrument.
void VirtualInstrumentManager.OnDestroy ()
Destroys the Virtual Instrument Manager.
Detailed Description
These are functions that are built-in to Unity. Since the VirtualInstrumentManager is a Unity GameObject, these are called automatically.
Function Documentation
Awake()
void VirtualInstrumentManager.Awake ()
Called when the object is created. Sets the default values, sets up the events, and begins loading the instrument.
Definition at line 346 of file VirtualInstrumentManager.cs.
References VirtualInstrumentManager.LoadDrumKit(), VirtualInstrumentManager.LoadInstrument(), VirtualInstrumentManager.mInstrumentType, VirtualInstrumentManager.SetDefaultValues(), and VirtualInstrumentManager.SetUpEvents().
    {
        mReady = false;
        #if DEBUG_AUDIO_DIAGNOSTICS
            // Set up the audio diagnostics scene
            GameObject diagnosticsContainer = Instantiate(Resources.Load<GameObject>("
      Audio/Prefabs/AudioDiagnosticsPrefab"));
            Assert.IsNotNull(diagnosticsContainer, "Could not load the diagnostics prefab!");
            mDiagnosticsHandler = diagnosticsContainer.transform.GetChild(0).
      GetComponent<ATI_Diagnostics>();
            Assert.IsNotNull(mDiagnosticsHandler, "Could not get the diagnostics
       handler!");
        #endif
        #if DEBUG_MUSICAL_TYPING
            mMusicalTypingHandler = gameObject.AddComponent<
      MusicalTypingHandler>();
            Assert.IsNotNull(mMusicalTypingHandler, "Could not load Musical Typing!"
      );
        #endif
        // Set up the Song Manager.
        SongManager = new SongManagerClass();
        // Set up the events.
        SetUpEvents();
        // Set default values for the member variables.
        SetDefaultValues();
        // Begin loading the default virtual instrument which is a piano.
        StartCoroutine(LoadInstrument(mInstrumentType, (returned) => {
      mInstrument = returned; }));
        StartCoroutine(LoadDrumKit((returned) => { mDrumKit = returned; }));
    }
OnDestroy()
void VirtualInstrumentManager.OnDestroy () [private]
Destroys the Virtual Instrument Manager.
Definition at line 380 of file VirtualInstrumentManager.cs.
References VirtualInstrumentManager.mNumActiveNotes.
    {
        // Destroy everything created by the VIM.
        if(mDrumLoopOutput != null)
        {
            DestroyImmediate(mDrumLoopOutput.gameObject, false);
            mDrumLoopOutput = null;
        }
        if(mSongOutput != null)
        {
            DestroyImmediate(mSongOutput.gameObject, false);
            mSongOutput = null;
        }
        for(int i = 0; i < mNumActiveNotes; i++)
        {
            if(mOutputs != null && mOutputs[i] != null)
            {
                DestroyImmediate(mOutputs[i].gameObject, false);
                mOutputs[i] = null;
            }
        }
        mOutputs = null;
        #if DEBUG_AUDIO_DIAGNOSTICS
            if(mDiagnosticsHandler != null)
            {
                DestroyImmediate(mDiagnosticsHandler.transform.parent.gameObject, false
       );
                mDiagnosticsHandler = null;
            }
        #endif
        // Clean up
        GC.Collect();
        Resources.UnloadUnusedAssets();
    }