Event Handlers
Functions
void SC_MeasureDisplayPanel.OnShowToggle (bool aShowMeasure)
Handles showing the measure or hiding it.
void SC_MeasureDisplayPanel.OnRemoveNote (SC_NoteDisplayPanel aNoteDisplayPanel)
Removes a note.
Detailed Description
Functions called by the SC_MeasureDisplayPanel in order to handle events.
Function Documentation
OnRemoveNote()
void SC_MeasureDisplayPanel.OnRemoveNote (SC_NoteDisplayPanel aNoteDisplayPanel)
Removes a note.
Parameters
in aNoteDisplayPanel The panel displaying the note to be removed.
Definition at line 232 of file SC_MeasureDisplayPanel.cs.
References Music.GetNoteLengthRelativeToMeasure(), SC_NoteDisplayPanel.GetOffset(), SC_NoteDisplayContainer.HandleMeasureDeleted(), SC_NoteDisplayContainer.OnRemoveNote(), and Music.TIME_SIGNATURE_4_4().
Referenced by SC_NoteDisplayPanel.OnRemoveButtonClicked().
    {
        // If there is more than one note in the measure, then just remove it from the measure.
        if(mNotes.Count > 1)
        {
            // Find the note.
            bool found = false;
            int index = 0;
            while(!found && index < mNotes.Count)
            {
                if(aNoteDisplayPanel == mNotes[index])
                {
                    found = true;
                }
                else
                {
                    index++;
                }
            }
            SC_NoteDisplayPanel temp = mNotes[index];
            // Remove the note from the list.
            mNotes.RemoveAt(index);
            // Update the percentage used.
            mPercentageUsed -= Music.
      GetNoteLengthRelativeToMeasure(temp.GetOffset(),
      Music.TIME_SIGNATURE_4_4());
            // Destroy the note object.
            DestroyImmediate(temp.gameObject, false);
        }
        // If there aren't any notes left, then handle this measure being deleted.
        else
        {
            SC_NoteDisplayPanel temp = mNotes[0];
            mNotes.Clear();
            DestroyImmediate(temp.gameObject, false);
            mParent.HandleMeasureDeleted(this);
        }
        mParent.OnRemoveNote();
    }
OnShowToggle()
void SC_MeasureDisplayPanel.OnShowToggle (bool aShowMeasure)
Handles showing the measure or hiding it.
Parameters
in aShowMeasure True if the measure should be shown. False otherwise.
This just passes it from the toggle switch to the parent's handling function.
Definition at line 223 of file SC_MeasureDisplayPanel.cs.
References SC_NoteDisplayContainer.HandleMeasureToggled().
Referenced by SC_MeasureDisplayPanel.Awake(), and SC_MeasureDisplayPanel.SetToggle().
    {
        mParent.HandleMeasureToggled(this);
    }