Event Handlers
Functions
void SC_NoteDisplayPanel.OnRemoveButtonClicked ()
Handles when the remove button is clicked.
void SC_NoteDisplayPanel.TriggerEditEvent (PointerEventData aPointerData)
Handles clicking on the background panel which means that we're either beginning an edit to this note or cancelling it.
Detailed Description
Functions that are called to handle events.
Function Documentation
OnRemoveButtonClicked()
void SC_NoteDisplayPanel.OnRemoveButtonClicked ()
Handles when the remove button is clicked.
Definition at line 225 of file SC_NoteDisplayPanel.cs.
References SC_NoteDisplayPanel.mNoteIndex, SC_MeasureDisplayPanel.OnRemoveNote(), and SC_NoteDisplayPanel.SetNoteIndex().
Referenced by SC_NoteDisplayPanel.Awake().
    {
        // Set the note index for all notes after this one
        int sib = transform.GetSiblingIndex() + 1;
        int index = mNoteIndex;
        while(sib < transform.parent.childCount)
        {
            if(transform.parent.GetChild(sib).GetComponent<
      SC_NoteDisplayPanel>() != null)
            {
                transform.parent.GetChild(sib).GetComponent<
      SC_NoteDisplayPanel>().SetNoteIndex(index);
                index++;
            }
            sib++;
        }
        // Signal that this note display should be removed.
        mParent.OnRemoveNote(this);
        // Signal that this note should be removed from the song.
        GameObject.Find("SongCreationCanvas").GetComponent<SongCreationManager>().
      OnRemoveNote(mNoteIndex);
    }
TriggerEditEvent()
void SC_NoteDisplayPanel.TriggerEditEvent (PointerEventData aPointerData) [private]
Handles clicking on the background panel which means that we're either beginning an edit to this note or cancelling it.
Parameters
in aPointerData The PointerEventData representing the mouse click.
Definition at line 251 of file SC_NoteDisplayPanel.cs.
References SongCreationManager.OnEditEvent().
Referenced by SC_NoteDisplayPanel.Awake().
    {
        if(aPointerData.button == PointerEventData.InputButton.Left)
        {
            // Change the color of the background panel to show that we're editing the note that it
            // represents.
            gameObject.GetComponent<Image>().color = new Color32(116, 116, 116, 255);
            // Send the event to the song creation handler.
            mSongCreationHandler.OnEditEvent(this);
        }
    }