Public Functions
Functions
void SC_NoteDisplayContainer.AddNote (int aMelodyVelocity, Music.NOTE_LENGTH aLength, Music.PITCH[] aPitches, int aDrumVelocity, Music.DRUM[] aDrumHits, Music.NOTE_LENGTH aOffsetFromPrevNote)
Adds a note to the current measure.
void SC_NoteDisplayContainer.ClearNotes ()
Clears all of the notes.
SC_MeasureDisplayPanel SC_NoteDisplayContainer.GetCurrentMeasureObject ()
Gets the current measure.
Sprite [] SC_NoteDisplayContainer.GetSprites ()
Gets the images used to represent a note's length/offset.
Detailed Description
Functions for other classes to interact with the SC_NoteDisplayContainer.
Function Documentation
AddNote()
void SC_NoteDisplayContainer.AddNote (int aMelodyVelocity, Music.NOTE_LENGTH aLength, Music.PITCH [] aPitches, int aDrumVelocity, Music.DRUM [] aDrumHits, Music.NOTE_LENGTH aOffsetFromPrevNote)
Adds a note to the current measure.
Parameters
in aMelodyVelocity The velocity of the pitches in the note.
in aLength The length of the note.
in aPitches The pitches in the note.
in aDrumVelocity The velocity of the drums in the note.
in aDrumHits The drums that are hit for this note.
in aOffsetFromPrevNote The offset from the previous note.
This function just updates the index of the note in the song and sends it to the current measure for it to handle adding it.
Definition at line 88 of file SC_NoteDisplayContainer.cs.
References SC_NoteDisplayContainer.mCurrentMeasure.
Referenced by SongCreationManager.OnCreateNote(), and SongCreationManager.OnLoadSong().
    {
        // Create a measure if none are present.
        if(mCurrentMeasure == -1)
        {
            GameObject newMeasure = Instantiate(Resources.Load<GameObject>(
      MEASURE_PANEL_PREFAB_PATH));
            Assert.IsNotNull(newMeasure, "Could not load the MeasurePanel prefab!");
            // Add the measure panel to the list.
            mMeasures.Add(newMeasure.AddComponent<
      SC_MeasureDisplayPanel>());
            // Increase the current measure.
            mCurrentMeasure++;
            // Set the values for the new measure toggle.
            mMeasures[mCurrentMeasure].transform.GetChild(0).GetChild(1).
      GetComponent<Text>().text = "Measure " + (mCurrentMeasure + 1).ToString();
            mMeasures[mCurrentMeasure].transform.SetParent(gameObject.transform);
            mMeasures[mCurrentMeasure].SetParentContainer(this);
            mMeasures[mCurrentMeasure].transform.localScale = Vector3.one;
            mMeasures[mCurrentMeasure].SetToggle(true);
        }
        mMeasures[mCurrentMeasure].AddNote(mNumNotes, aMelodyVelocity,
      aLength, aPitches, aDrumVelocity, aDrumHits, aOffsetFromPrevNote);
        mNumNotes++;
    }
ClearNotes()
void SC_NoteDisplayContainer.ClearNotes ()
Clears all of the notes.
Definition at line 116 of file SC_NoteDisplayContainer.cs.
References SC_NoteDisplayContainer.mCurrentMeasure.
Referenced by SongCreationManager.OnLoadSong().
    {
        while(mCurrentMeasure >= 0)
        {
            mMeasures[mCurrentMeasure].ClearMeasure();
            mMeasures.RemoveAt(mCurrentMeasure);
            mCurrentMeasure--;
        }
        mNumNotes = 0;
    }
GetCurrentMeasureObject()
SC_MeasureDisplayPanel SC_NoteDisplayContainer.GetCurrentMeasureObject ()
Gets the current measure.
Returns
The current measure.
Definition at line 131 of file SC_NoteDisplayContainer.cs.
References SC_NoteDisplayContainer.mCurrentMeasure.
    {
        return mMeasures[mCurrentMeasure];
    }
GetSprites()
Sprite [] SC_NoteDisplayContainer.GetSprites ()
Gets the images used to represent a note's length/offset.
Returns
The images used to represent a note's length/offset.
Definition at line 140 of file SC_NoteDisplayContainer.cs.
References SC_NoteDisplayContainer.mSprites.
Referenced by SC_MeasureDisplayPanel.AddNote(), and SongCreationManager.OnModifyNote().
    {
        return mSprites;
    }