Nested Classes
Classes
class SongCreationManager.SongCreationSelectionContainer.SongCreationSelectionTrigger
class SongCreationManager.SongCreationSelectionContainer
Detailed Description
These are classes that are nested inside of the SongCreationManager. They are used only within the Song Creation Interface.
Class Documentation
class SongCreationManager::SongCreationSelectionContainer::SongCreationSelectionTrigger
Definition at line 45 of file SongCreationManager.cs.
Public Member Functions
void SetContainer (SongCreationSelectionContainer aContainer)
void SetSelected (bool aSelected)
void OnSelected (bool aSelected)
Private Member Functions
void Awake ()
void ChangeColor ()
Private Attributes
bool mSelected = false
SongCreationSelectionContainer mContainer = null
Toggle mToggle = null
Member Function Documentation
Awake()
void SongCreationManager.SongCreationSelectionContainer.SongCreationSelectionTrigger.Awake () [private]
Definition at line 57 of file SongCreationManager.cs.
References SongCreationManager.SongCreationSelectionContainer.SongCreationSelectionTrigger.OnSelected().
            {
                // Get the toggle and set its listener
                mToggle = gameObject.GetComponent<Toggle>();
                mToggle.onValueChanged.AddListener(OnSelected);
            }
ChangeColor()
void SongCreationManager.SongCreationSelectionContainer.SongCreationSelectionTrigger.ChangeColor () [private]
Definition at line 93 of file SongCreationManager.cs.
Referenced by SongCreationManager.SongCreationSelectionContainer.SongCreationSelectionTrigger.OnSelected(), and SongCreationManager.SongCreationSelectionContainer.SongCreationSelectionTrigger.SetSelected().
            {
                if(mSelected)
                {
                    mToggle.transform.GetChild(0).GetComponent<Image>().color = new Color32(255,
      255, 255, 118);
                }
                else
                {
                    mToggle.transform.GetChild(0).GetComponent<Image>().color = new Color32(255,
      255, 255, 255);
                }
            }
OnSelected()
void SongCreationManager.SongCreationSelectionContainer.SongCreationSelectionTrigger.OnSelected (bool aSelected)
Definition at line 111 of file SongCreationManager.cs.
References SongCreationManager.SongCreationSelectionContainer.SongCreationSelectionTrigger.ChangeColor(), and SongCreationManager.SongCreationSelectionContainer.HandleToggle().
Referenced by SongCreationManager.SongCreationSelectionContainer.SongCreationSelectionTrigger.Awake(), and SongCreationManager.SongCreationSelectionContainer.SongCreationSelectionTrigger.SetSelected().
            {
                // If this object is now selected, then change the color and send it to the handler.
                if(aSelected)
                {
                    mSelected = aSelected;
                    ChangeColor();
                    mContainer.HandleToggle(this);
                }
                // This object can not be unselected by clicking on it. Set the value back to selected.
                else
                {
                    mToggle.onValueChanged.RemoveListener(OnSelected);
                    mToggle.isOn = true;
                    mToggle.onValueChanged.AddListener(OnSelected);
                }
            }
SetContainer()
void SongCreationManager.SongCreationSelectionContainer.SongCreationSelectionTrigger.SetContainer (SongCreationSelectionContainer aContainer)
Definition at line 69 of file SongCreationManager.cs.
Referenced by SongCreationManager.SongCreationSelectionContainer.Awake().
            {
                mContainer = aContainer;
            }
SetSelected()
void SongCreationManager.SongCreationSelectionContainer.SongCreationSelectionTrigger.SetSelected (bool aSelected)
Definition at line 75 of file SongCreationManager.cs.
References SongCreationManager.SongCreationSelectionContainer.SongCreationSelectionTrigger.ChangeColor(), and SongCreationManager.SongCreationSelectionContainer.SongCreationSelectionTrigger.OnSelected().
Referenced by SongCreationManager.SongCreationSelectionContainer.Awake(), SongCreationManager.SongCreationSelectionContainer.HandleToggle(), and SongCreationManager.SongCreationSelectionContainer.SetSelected().
            {
                mSelected = aSelected;
                // Change the color to indicate that this is or isn't the selected object
                ChangeColor();
                // Set the value of the toggle.
                mToggle.onValueChanged.RemoveListener(OnSelected);
                mToggle.isOn = aSelected;
                mToggle.onValueChanged.AddListener(OnSelected);
            }
Member Data Documentation
mContainer
SongCreationSelectionContainer SongCreationManager.SongCreationSelectionContainer.SongCreationSelectionTrigger.mContainer = null [private]
Definition at line 51 of file SongCreationManager.cs.
mSelected
bool SongCreationManager.SongCreationSelectionContainer.SongCreationSelectionTrigger.mSelected = false [private]
Definition at line 50 of file SongCreationManager.cs.
mToggle
Toggle SongCreationManager.SongCreationSelectionContainer.SongCreationSelectionTrigger.mToggle = null [private]
Definition at line 52 of file SongCreationManager.cs.
class SongCreationManager::SongCreationSelectionContainer
Definition at line 40 of file SongCreationManager.cs.
Public Member Functions
Music.NOTE_LENGTH GetSelected ()
void SetSelected (Music.NOTE_LENGTH aSelection)
Private Member Functions
void Awake ()
void HandleToggle (SongCreationSelectionTrigger aTrigger)
Private Attributes
int mSelectedIndex = 0
SongCreationSelectionTrigger [] mTriggers = null
Member Function Documentation
Awake()
void SongCreationManager.SongCreationSelectionContainer.Awake () [private]
Definition at line 141 of file SongCreationManager.cs.
References SongCreationManager.SongCreationSelectionContainer.SongCreationSelectionTrigger.SetContainer(), and SongCreationManager.SongCreationSelectionContainer.SongCreationSelectionTrigger.SetSelected().
        {
            // Set up the triggers.
            mTriggers = new SongCreationSelectionTrigger[13];
            for(int i = 0; i < 13; i++)
            {
                mTriggers[i] = gameObject.transform.GetChild(i + 1).gameObject.AddComponent<
      SongCreationSelectionTrigger>();
                mTriggers[i].SetContainer(this);
                mTriggers[i].SetSelected(false);
            }
            // Set the default selection (Quarter note).
            mTriggers[12].SetSelected(true);
            mSelectedIndex = 12;
        }
GetSelected()
Music.NOTE_LENGTH SongCreationManager.SongCreationSelectionContainer.GetSelected ()
Definition at line 162 of file SongCreationManager.cs.
References SongCreationManager.SongCreationSelectionContainer.mSelectedIndex.
Referenced by SongCreationManager.OnCreateNote(), and SongCreationManager.OnModifyNote().
        {
            return (Music.NOTE_LENGTH)mSelectedIndex;
        }
HandleToggle()
void SongCreationManager.SongCreationSelectionContainer.HandleToggle (SongCreationSelectionTrigger aTrigger) [private]
Definition at line 193 of file SongCreationManager.cs.
References SongCreationManager.SongCreationSelectionContainer.SongCreationSelectionTrigger.SetSelected().
Referenced by SongCreationManager.SongCreationSelectionContainer.SongCreationSelectionTrigger.OnSelected().
        {
            // Set all other triggers to unselected.
            for(int i = 0; i < 13; i++)
            {
                if(mTriggers[i] != aTrigger)
                {
                    mTriggers[i].SetSelected(false);
                }
                // Update the current selection.
                else
                {
                    mSelectedIndex = i;
                }
            }
        }
SetSelected()
void SongCreationManager.SongCreationSelectionContainer.SetSelected (Music.NOTE_LENGTH aSelection)
Definition at line 168 of file SongCreationManager.cs.
References SongCreationManager.SongCreationSelectionContainer.SongCreationSelectionTrigger.SetSelected().
Referenced by SongCreationManager.Awake(), SongCreationManager.OnCreateNote(), and SongCreationManager.OnEditEvent().
        {
            // Update the private variable.
            mSelectedIndex = (int)aSelection;
            // Update the child objects.
            for(int i = 0; i < 13; i++)
            {
                if(i != mSelectedIndex)
                {
                    mTriggers[i].SetSelected(false);
                }
                else
                {
                    mTriggers[i].SetSelected(true);
                }
            }
        }
Member Data Documentation
mSelectedIndex
int SongCreationManager.SongCreationSelectionContainer.mSelectedIndex = 0 [private]
Definition at line 134 of file SongCreationManager.cs.
Referenced by SongCreationManager.SongCreationSelectionContainer.GetSelected().
mTriggers
SongCreationSelectionTrigger [] SongCreationManager.SongCreationSelectionContainer.mTriggers = null [private]
Definition at line 135 of file SongCreationManager.cs.