Public Functions
Functions
void NoteOutputObject.BeingPlaying (float aVelocityFactor, int aDynamicsIndex, int aStartIndex=0)
Handler for setting the note to be played. Should be called from the manager's PlayNote event.
void NoteOutputObject.BeginRelease ()
Marks that the audio should begin fading out.
bool NoteOutputObject.GetLoop ()
Gets whether or not the audio should loop.
void NoteOutputObject.PauseAudio ()
Pauses the audio.
void NoteOutputObject.ResumeAudio ()
Resumes the audio.
void NoteOutputObject.SetAudioData (float[][] aAudioData, AudioMixer aMixer, int[] aThresholds=null)
Sets the audio data for this object.
void NoteOutputObject.SetLoop (bool aLoop)
Sets whether or not the audio should loop.
void NoteOutputObject.SetVIM (VirtualInstrumentManager aVIM)
Sets the parent VirtualInstrumentManager and sets up diagnostics if needed.
void NoteOutputObject.ShouldNotifyWhenFinished (bool aShouldNotify)
Sets whether or not an others should be notified when the audio has finished playing.
void NoteOutputObject.StopAudio ()
Stops playing the audio.
Detailed Description
These are functions other classes use to interact with the NoteOutputObject.
Function Documentation
BeginRelease()
void NoteOutputObject.BeginRelease ()
Marks that the audio should begin fading out.
This should only be called from the manager's release note event.
Definition at line 136 of file NoteOutputObject.cs.
Referenced by VirtualInstrumentManager.OnReleaseNoteEvent().
    {
        if(mLoaded && mNotePlaying)
        {
            // Set that the note should fade out.
            // Actually processing the fade out will be handled by the onAudioFilterRead function.
            mNoteRelease = true;
        }
    }
BeingPlaying()
void NoteOutputObject.BeingPlaying (float aVelocityFactor, int aDynamicsIndex, int aStartIndex = 0)
Handler for setting the note to be played. Should be called from the manager's PlayNote event.
Parameters
in aVelocityFactor The adjusted velocity of the note to be played. Ranges from 0 (silent) to 1.0 (max volume).
in aDynamicsIndex the index of the built-in dynamics.
in aStartIndex Where the note/song/loop should begin playing. Defaults to 0.
This function signals to OnAudioFilterRead that it should begin playing audio. In order to avoid threading issues, the signalling mechanism functions somewhat like a Moore state machine where it'll have an effect on the next cycle of OnAudioFilterRead.
Definition at line 116 of file NoteOutputObject.cs.
Referenced by VirtualInstrumentManager.OnPlayDrumLoopEvent(), VirtualInstrumentManager.OnPlayNoteEvent(), and VirtualInstrumentManager.OnPlaySongEvent().
    {
        Assert.IsTrue(aVelocityFactor <= 1f, "NoteOutputObject was given a velocity factor greater than 1!
      ");
        if(mLoaded)
        {
            mNewNoteVelocityFactor = aVelocityFactor;
            mNewNoteDynamicsIndex = aDynamicsIndex;
            mNewNoteStartIndex = aStartIndex;
            mNewNote = true;
            mNoteRelease = false;
            mPaused = false;
        }
    }
GetLoop()
bool NoteOutputObject.GetLoop ()
Gets whether or not the audio should loop.
Returns
True if the audio should loop. False otherwise.
Definition at line 150 of file NoteOutputObject.cs.
References NoteOutputObject.mLoop.
    {
        return mLoop;
    }
PauseAudio()
void NoteOutputObject.PauseAudio ()
Pauses the audio.
See also
VirtualInstrumentManager::PauseSongEvent VirtualInstrumentManager::PauseDrumLoopEvent
Definition at line 160 of file NoteOutputObject.cs.
Referenced by VirtualInstrumentManager.OnPauseDrumLoopEvent(), and VirtualInstrumentManager.OnPauseSongEvent().
    {
        mPaused = true;
    }
ResumeAudio()
void NoteOutputObject.ResumeAudio ()
Resumes the audio.
See also
VirtualInstrumentManager::ResumeSongEvent VirtualInstrumentManager::ResumeDrumLoopEvent
Definition at line 170 of file NoteOutputObject.cs.
Referenced by VirtualInstrumentManager.OnResumeDrumLoopEvent(), and VirtualInstrumentManager.OnResumeSongEvent().
    {
        mPaused = false;
        mNotePlaying = true;
    }
SetAudioData()
void NoteOutputObject.SetAudioData (float aAudioData[][], AudioMixer aMixer, int [] aThresholds = null)
Sets the audio data for this object.
Parameters
in aAudioData The raw audio data for each Built-In Dynamic if supported by the instrument. It is just the raw audio data for a single Music::PITCH otherwise.
in aMixer The audio mixer to route the audio output to.
in aThresholds The Built-In Dynamics thresholds if supported by the instrument. Default is null for instruments that don't support Built-In Dynamics.
Definition at line 182 of file NoteOutputObject.cs.
References NoteOutputObject.mNumBuiltInDynamics, and NoteOutputObject.RemoveAudioData().
Referenced by VirtualInstrumentManager.LoadNoteOutputObjects(), VirtualInstrumentManager.OnPlayDrumLoopEvent(), and VirtualInstrumentManager.OnPlaySongEvent().
    {
        mLoaded = false;
        while(mAudioDataBeingUsed) ;
        // Remove any existing audio data.
        RemoveAudioData();
        // Set the values related to built-in dynamics if necessary.
        if(aThresholds != null)
        {
            mNumBuiltInDynamics = aThresholds.Length;
            mBuiltInDynamicsThresholds = new int[
      mNumBuiltInDynamics];
            for(int i = 0; i < aThresholds.Length; i++)
            {
                mBuiltInDynamicsThresholds[i] = aThresholds[i];
            }
        }
        else
        {
            mBuiltInDynamicsThresholds = null;
            mDynamicsIndex = 0;
            mNumBuiltInDynamics = 0;
            mCounter = 0;
        }
        // Set the output mixer.
        mSource.outputAudioMixerGroup = aMixer.FindMatchingGroups("Master")[0];
        // Initialize the audio data array and copy the values from the given parameter.
        // If we don't have to worry about built in dynamics, then use hard-coded indices
        // for the outer array.
        if(mNumBuiltInDynamics == 0)
        {
            mAudioData = new float[1][];
            mAudioData[0] = new float[aAudioData[0].Length];
            mEndSampleIndices = new int[1];
            mEndSampleIndices[0] = aAudioData[0].Length - 1;
            for(int i = 0; i < aAudioData[0].Length; i++)
            {
                mAudioData[0][i] = aAudioData[0][i];
            }
        }
        // If there are built in dynamics, then iterate through each one.
        else
        {
            mAudioData = new float[mNumBuiltInDynamics][];
            mEndSampleIndices = new int[mNumBuiltInDynamics];
            // int bufferLength = 0;
            for(int i = 0; i < mNumBuiltInDynamics; i++)
            {
                mAudioData[i] = new float[aAudioData[i].Length];
                mEndSampleIndices[i] = aAudioData[i].Length - 1;
                for(int j = 0; j < mAudioData[i].Length; j++)
                {
                    mAudioData[i][j] = aAudioData[i][j];
                }
            }
        }
        // Mark that this object is loaded.
        mLoaded = true;
    }
SetLoop()
void NoteOutputObject.SetLoop (bool aLoop)
Sets whether or not the audio should loop.
Parameters
in aLoop Whether or not the audio should loop.
Definition at line 251 of file NoteOutputObject.cs.
Referenced by VirtualInstrumentManager.LoadNoteOutputObjects(), VirtualInstrumentManager.OnPlayDrumLoopEvent(), and VirtualInstrumentManager.SetDefaultValues().
    {
        mLoop = aLoop;
    }
SetVIM()
void NoteOutputObject.SetVIM (VirtualInstrumentManager aVIM)
Sets the parent VirtualInstrumentManager and sets up diagnostics if needed.
Parameters
in aVIM The parent VirtualInstrumentManager.
Definition at line 260 of file NoteOutputObject.cs.
References VirtualInstrumentManager.GetDiagnosticsHandler().
Referenced by VirtualInstrumentManager.LoadNoteOutputObjects(), and VirtualInstrumentManager.SetDefaultValues().
    {
        mVIM = aVIM;
        #if DEBUG_AUDIO_DIAGNOSTICS
            mDiagnosticsHandler = mVIM.
      GetDiagnosticsHandler();
            mReported = false;
        #endif
    }
ShouldNotifyWhenFinished()
void NoteOutputObject.ShouldNotifyWhenFinished (bool aShouldNotify)
Sets whether or not an others should be notified when the audio has finished playing.
Parameters
in aShouldNotify Whether or not others should be notified when the audio has finished playing
Definition at line 273 of file NoteOutputObject.cs.
Referenced by VirtualInstrumentManager.SetDefaultValues().
    {
        mNotifyWhenFinished = aShouldNotify;
    }
StopAudio()
void NoteOutputObject.StopAudio ()
Stops playing the audio.
Definition at line 281 of file NoteOutputObject.cs.
Referenced by VirtualInstrumentManager.OnStopDrumLoopEvent(), and VirtualInstrumentManager.OnStopSongEvent().
    {
        mNotePlaying = false;
        mPaused = false;
    }