Unity Functions
Functions
void KeyContainer.Awake ()
Initializes the KeyContainer and loads each key.
void KeyContainer.Update ()
Detailed Description
Built-in Unity functions that are automatically called.
Function Documentation
Awake()
void KeyContainer.Awake () [private]
Initializes the KeyContainer and loads each key.
Definition at line 64 of file KeyContainer.cs.
References KeyContainer.BLACK_KEY_PATH, Music.IsPitchABlackKey(), KeyContainer.LoadKeys(), KeyContainer.mRepresentedPitches, KeyContainer.NUM_KEYS, and KeyContainer.WHITE_KEY_PATH.
    {
        // Initialize the represented pitches. Default is from C3 to C5.
        mRepresentedPitches = new Music.PITCH[
      NUM_KEYS];
        for(int i = 0; i < NUM_KEYS; i++)
        {
            mRepresentedPitches[i] = (Music.PITCH)((int)
      Music.PITCH.C3 + i);
            if(!Music.IsPitchABlackKey(
      mRepresentedPitches[i]))
            {
                mNumWhiteKeys++;
            }
        }
        // Get the width of each key.
        mWhiteKeyWidth = Resources.Load<GameObject>(
      WHITE_KEY_PATH).GetComponent<Renderer>().bounds.size.z;
        mWhiteKeyWidth += (mWhiteKeyWidth / 10f);
        mBlackKeyWidth = Resources.Load<GameObject>(
      BLACK_KEY_PATH).GetComponent<Renderer>().bounds.size.z;
        Debug.Log("White key width: " + mWhiteKeyWidth.ToString());
        Debug.Log("Black key width: " + mBlackKeyWidth.ToString());
        // Load the keys.
        LoadKeys();
    }
Update()
void KeyContainer.Update () [private]
Definition at line 89 of file KeyContainer.cs.
References VirtualInstrumentManager.ChangeNoteRange, VirtualInstrumentManager.GetMusicalTypingHandler(), KeyContainer.HandleChangeNoteRangeEvent(), KeyContainer.HandlePlaySongEvent(), MusicalTypingHandler.MusicalTypingEnabled, and VirtualInstrumentManager.PlaySong.
    {
        // See if we need to load the audio.
        if(mVIM == null && EnableAudio)
        {
            // Load the prefab
            GameObject temp = Instantiate(Resources.Load<GameObject>(VIM_PATH));
            Assert.IsNotNull(temp, "Failed to load VirtualInstrumentManagerPrefab!");
            // Get the VIM from the prefab.
            temp.name = "VirtualInstrumentManager";
            mVIM = temp.GetComponent<VirtualInstrumentManager>();
            Assert.IsNotNull(mVIM, "Failed to get the VirtualInstrumentManager component!");
            // Add the listener for note range changes.
            mVIM.ChangeNoteRange.AddListener(
      HandleChangeNoteRangeEvent);
            mVIM.PlaySong.AddListener(HandlePlaySongEvent);
            #if DEBUG_MUSICAL_TYPING
                // Disable Musical Typing
                mVIM.GetMusicalTypingHandler().
      MusicalTypingEnabled = false;
            #endif
        }
        // See if we need to unload the audio.
        else if(!EnableAudio && mVIM != null)
        {
            DestroyImmediate(mVIM.gameObject, false);
            mVIM = null;
        }
    }