Implementations of Pure Virtual Functions
Functions
override void Marimba.InitializeBuiltInDynamics ()
Initializes values related to the Built-In Dynamics for this instrument.
override void Marimba.CreateFilenames ()
Creates the filenames of the WAV files used to create the Marimba.
Detailed Description
These are functions from the base class that are given implementations specific to the Marimba.
Function Documentation
CreateFilenames()
override void Marimba.CreateFilenames () [protected], [virtual]
Creates the filenames of the WAV files used to create the Marimba.
The files are stored in `Audio/VirtualInstrument/Marimba/Samples`.
Reimplemented from VirtualInstrument.
Definition at line 79 of file Marimba.cs.
References VirtualInstrument.mFilenames, VirtualInstrument.mFilepath, VirtualInstrument.mHighestSupportedPitch, VirtualInstrument.mLowestSupportedPitch, VirtualInstrument.mNumFiles, and Music.NoteToString().
Referenced by Marimba.Marimba().
    {
        // Set the base filepath and number of files.
        mFilepath = "Audio/VirtualInstrument/Marimba/Samples/";
        mNumFiles = 61;
        // Initialize the array of filenames.
        mFilenames = new string[mNumFiles];
        // Iterate through each dynamics value and create filenames for each supported note.
        int index = 0;
        for(int i = (int)mLowestSupportedPitch; i <= (int)
      mHighestSupportedPitch; i++)
        {
            mFilenames[index] = mFilepath + Music.
      NoteToString(i);
            index++;
        }
    }
InitializeBuiltInDynamics()
override void Marimba.InitializeBuiltInDynamics () [protected], [virtual]
Initializes values related to the Built-In Dynamics for this instrument.
There aren't built-in dynamics for the marimba, so the dynamics and thresholds are set to null.
Reimplemented from VirtualInstrument.
Definition at line 62 of file Marimba.cs.
References VirtualInstrument.mAudioData, Music.MAX_SUPPORTED_NOTES, VirtualInstrument.mBuiltInDynamics, VirtualInstrument.mBuiltInDynamicsThresholds, and VirtualInstrument.mNumBuiltInDynamics.
Referenced by Marimba.Marimba().
    {
        // There are no built-in dynamics for the marimba.
        mNumBuiltInDynamics = 0;
        mBuiltInDynamics = null;
        mBuiltInDynamicsThresholds = null;
        // Allocate the audio data container.
        mAudioData = new float[1][][];
        mAudioData[0] = new float[Music.MAX_SUPPORTED_NOTES][];
    }