Event Handlers
Functions
void VirtualInstrumentManager.OnChangeInstrumentEvent (Music.INSTRUMENT_TYPE aNewInstrumentType)
Called whenever an instrument should be loaded.
void VirtualInstrumentManager.OnChangeNoteRangeEvent (Music.PITCH aNewLowestPitch)
Called whenever the range of active notes should be changed.
void VirtualInstrumentManager.OnInstrumentLoaded ()
Called whenever the instrument has finished loading. It begins loading the NoteOutputObjects.
void VirtualInstrumentManager.OnModifyEchoFilterEvent (EchoFilterParameters aParameters)
Called whenever the echo filter should be modified.
void VirtualInstrumentManager.OnModifyReverbFilterEvent (ReverbFilterParameters aParameters)
Called whenever the reverb filter should be modified.
void VirtualInstrumentManager.OnPauseDrumLoopEvent ()
Handles pausing a drum loop.
void VirtualInstrumentManager.OnPauseSongEvent ()
Handles pausing a song.
void VirtualInstrumentManager.OnPlayDrumLoopEvent (Song aLoop)
Begins playing a drum loop. It creates an array of audio data from each note of the Song and sends it to the right NoteOutputObject.
void VirtualInstrumentManager.OnPlayNoteEvent (Music.PITCH aNoteToPlay, int aVelocity)
Called whenever a note should be played. Uses the appropriate NoteOutputObject to play the note.
void VirtualInstrumentManager.OnPlaySongEvent (Song aSong)
Begins playing a song. It creates an array of audio data from each note of the Song and sends it to the right NoteOutputObject.
void VirtualInstrumentManager.OnReleaseNoteEvent (Music.PITCH aNoteToRelease)
Called whenever a note should be released. Uses the appropriate NoteOutputObject to release the note.
void VirtualInstrumentManager.OnResumeDrumLoopEvent ()
Handles resuming a drum loop.
void VirtualInstrumentManager.OnResumeSongEvent ()
Handles resuming a song.
void VirtualInstrumentManager.OnStopDrumLoopEvent ()
Handles stopping a drum loop.
void VirtualInstrumentManager.OnStopSongEvent ()
Handles stopping a song.
Detailed Description
These are functions that the VirtualInstrumentManager uses to handle invoked events
Function Documentation
OnChangeInstrumentEvent()
void VirtualInstrumentManager.OnChangeInstrumentEvent (Music.INSTRUMENT_TYPE aNewInstrumentType)
Called whenever an instrument should be loaded.
Parameters
in aNewInstrumentType The type of instrument that should be loaded
See also
Music::INSTRUMENT_TYPE VirtualInstrumentManager::ChangeInstrumentEvent
Definition at line 713 of file VirtualInstrumentManager.cs.
References VirtualInstrumentManager.DEFAULT_LOWEST_PITCH, VirtualInstrumentManager.LoadInstrument(), VirtualInstrumentManager.mActiveNotes, VirtualInstrumentManager.mHighestActiveNote, VirtualInstrumentManager.mInstrumentType, VirtualInstrumentManager.mLowestActiveNote, and VirtualInstrumentManager.mNumActiveNotes.
Referenced by VirtualInstrumentManager.SetUpEvents().
    {
        // Mark that we're not ready for note events.
        mReady = false;
        mInstrument = null;
        // Set the instrument type.
        mInstrumentType = aNewInstrumentType;
        // Handle the difference in active notes for a drum kit vs. a normal instrument.
        if(mInstrumentType == Music.INSTRUMENT_TYPE.DRUM_KIT)
        {
            mNumActiveNotes = 18;
        }
        else
        {
            mNumActiveNotes = 24;
        }
        // Destroy the note output objects.
        for(int i = 0; i < mOutputs.Length; i++)
        {
            DestroyImmediate(mOutputs[i], false);
        }
        mOutputs = null;
        // Set default values for the active notes and be sure to account for drums
        if(mInstrumentType == Music.INSTRUMENT_TYPE.DRUM_KIT)
        {
            mLowestActiveNote = Music.PITCH.C0;
        }
        else
        {
            mLowestActiveNote = DEFAULT_LOWEST_PITCH;
        }
        mHighestActiveNote = (Music.PITCH)((int)
      mLowestActiveNote + mNumActiveNotes - 1);
        mActiveNotes = new Music.PITCH[mNumActiveNotes];
        for(int i = 0; i < mNumActiveNotes; i++)
        {
            mActiveNotes[i] = (Music.PITCH)(i + (int)
      mLowestActiveNote);
        }
        // Start a coroutine to load the instrument.
        StartCoroutine(LoadInstrument(mInstrumentType, (returned) => {
      mInstrument = returned; }));
    }
OnChangeNoteRangeEvent()
void VirtualInstrumentManager.OnChangeNoteRangeEvent (Music.PITCH aNewLowestPitch)
Called whenever the range of active notes should be changed.
Parameters
in aNewLowestPitch The lowest pitch in the new range.
See also
Music::PITCH VirtualInstrumentManager::ChangeNoteRangeEvent
Definition at line 766 of file VirtualInstrumentManager.cs.
References VirtualInstrument.IsPitchSupported(), VirtualInstrumentManager.LoadNoteOutputObjects(), VirtualInstrumentManager.mActiveNotes, VirtualInstrumentManager.mHighestActiveNote, VirtualInstrumentManager.mLowestActiveNote, and VirtualInstrumentManager.mNumActiveNotes.
Referenced by VirtualInstrumentManager.SetUpEvents().
    {
        if(mReady)
        {
            mReady = false;
            // Make sure that we can change to the note range given.
            int newHighestIndex = (int)aNewLowestPitch + mNumActiveNotes - 1;
            if(!mInstrument.IsPitchSupported(aNewLowestPitch) || !
      mInstrument.IsPitchSupported((Music.PITCH)newHighestIndex))
            {
                Assert.IsTrue(false, "Tried to change the note range to include notes that aren't
       supported by the instrument!");
                return;
            }
            // Set the active note variables accordingly.
            mLowestActiveNote = aNewLowestPitch;
            mHighestActiveNote = (Music.PITCH)((int)aNewLowestPitch +
      mNumActiveNotes - 1);
            for(int i = 0; i < mNumActiveNotes; i++)
            {
                mActiveNotes[i] = (Music.PITCH)((int)aNewLowestPitch + i);
            }
            // Load the note output objects.
            LoadNoteOutputObjects();
        }
    }
OnInstrumentLoaded()
void VirtualInstrumentManager.OnInstrumentLoaded ()
Called whenever the instrument has finished loading. It begins loading the NoteOutputObjects.
See also
VirtualInstrumentManager::InstrumentLoadedEvent NoteOutputObject
Definition at line 799 of file VirtualInstrumentManager.cs.
References VirtualInstrumentManager.LoadNoteOutputObjects().
Referenced by VirtualInstrumentManager.SetUpEvents().
    {
        Assert.IsNotNull(mInstrument, "OnInstrumentLoaded was called, but the instrument was
       not loaded.");
        LoadNoteOutputObjects();
    }
OnModifyEchoFilterEvent()
void VirtualInstrumentManager.OnModifyEchoFilterEvent (EchoFilterParameters aParameters)
Called whenever the echo filter should be modified.
Parameters
in aParameters The new parameters of the echo filter
See also
VirtualInstrumentManager::ModifyEchoFilterEvent
Definition at line 812 of file VirtualInstrumentManager.cs.
References VirtualInstrumentManager.EchoFilterParameters.Active, VirtualInstrumentManager.EchoFilterParameters.Decay, VirtualInstrumentManager.EchoFilterParameters.Delay, VirtualInstrumentManager.EchoFilterParameters.DryMix, and VirtualInstrumentManager.EchoFilterParameters.WetMix.
Referenced by VirtualInstrumentManager.SetUpEvents().
    {
        // If the filter is active and the parameters are valid, then use the new parameters.
        if(aParameters.Active)
        {
            mMixer.SetFloat("echoDelay", aParameters.Delay);
            mMixer.SetFloat("echoDecay", aParameters.Decay);
            mMixer.SetFloat("echoDryMix", aParameters.DryMix);
            mMixer.SetFloat("echoWetMix", aParameters.WetMix);
        }
        // If the filter is not active, then set values that negate the filter.
        else
        {
            mMixer.SetFloat("echoDelay", 1f);
            mMixer.SetFloat("echoDecay", 0f);
            mMixer.SetFloat("echoDryMix", 100f);
            mMixer.SetFloat("echoWetMix", 0f);
        }
    }
OnModifyReverbFilterEvent()
void VirtualInstrumentManager.OnModifyReverbFilterEvent (ReverbFilterParameters aParameters)
Called whenever the reverb filter should be modified.
Parameters
in aParameters The new parameters of the reverb filter
See also
VirtualInstrumentManager::ModifyReverbFilterEvent
Definition at line 838 of file VirtualInstrumentManager.cs.
References VirtualInstrumentManager.ReverbFilterParameters.Active, VirtualInstrumentManager.ReverbFilterParameters.DecayHFRatio, VirtualInstrumentManager.ReverbFilterParameters.DecayTime, VirtualInstrumentManager.ReverbFilterParameters.Density, VirtualInstrumentManager.ReverbFilterParameters.Diffusion, VirtualInstrumentManager.ReverbFilterParameters.DryLevel, VirtualInstrumentManager.ReverbFilterParameters.HFReference, VirtualInstrumentManager.ReverbFilterParameters.LFReference, VirtualInstrumentManager.ReverbFilterParameters.ReflectDelay, VirtualInstrumentManager.ReverbFilterParameters.Reflections, VirtualInstrumentManager.ReverbFilterParameters.Reverb, VirtualInstrumentManager.ReverbFilterParameters.ReverbDelay, VirtualInstrumentManager.ReverbFilterParameters.Room, VirtualInstrumentManager.ReverbFilterParameters.RoomHF, and VirtualInstrumentManager.ReverbFilterParameters.RoomLF.
Referenced by VirtualInstrumentManager.SetUpEvents().
    {
        if(aParameters.Active)
        {
            mMixer.SetFloat("revDryLevel", aParameters.DryLevel);
            mMixer.SetFloat("revRoom", aParameters.Room);
            mMixer.SetFloat("revRoomHF", aParameters.RoomHF);
            mMixer.SetFloat("revDecayTime", aParameters.DecayTime);
            mMixer.SetFloat("revDecayHFRatio", aParameters.DecayHFRatio);
            mMixer.SetFloat("revReflections", aParameters.Reflections);
            mMixer.SetFloat("revReflectDelay", aParameters.ReflectDelay);
            mMixer.SetFloat("revReverb", aParameters.Reverb);
            mMixer.SetFloat("revReverbDelay", aParameters.ReverbDelay);
            mMixer.SetFloat("revDiffusion", aParameters.Diffusion);
            mMixer.SetFloat("revDensity", aParameters.Density);
            mMixer.SetFloat("revHFReference", aParameters.HFReference);
            mMixer.SetFloat("revRoomLF", aParameters.RoomLF);
            mMixer.SetFloat("revLFReference", aParameters.LFReference);
        }
        else
        {
            mMixer.SetFloat("revDryLevel", 0f);
            mMixer.SetFloat("revRoom", -10000f);
            mMixer.SetFloat("revRoomHF", -10000f);
            mMixer.SetFloat("revDecayTime", 0.1f);
            mMixer.SetFloat("revDecayHFRatio", 0.1f);
            mMixer.SetFloat("revReflections", -10000f);
            mMixer.SetFloat("revReflectDelay", -10000f);
            mMixer.SetFloat("revReverb", -10000f);
            mMixer.SetFloat("revReverbDelay", 0f);
            mMixer.SetFloat("revDiffusion", 0f);
            mMixer.SetFloat("revDensity", 0f);
            mMixer.SetFloat("revHFReference", 20f);
            mMixer.SetFloat("revRoomLF", -10000f);
            mMixer.SetFloat("revLFReference", 20f);
        }
    }
OnPauseDrumLoopEvent()
void VirtualInstrumentManager.OnPauseDrumLoopEvent ()
Handles pausing a drum loop.
Definition at line 879 of file VirtualInstrumentManager.cs.
References NoteOutputObject.PauseAudio().
Referenced by VirtualInstrumentManager.SetUpEvents().
    {
        mDrumLoopOutput.PauseAudio();
    }
OnPauseSongEvent()
void VirtualInstrumentManager.OnPauseSongEvent ()
Handles pausing a song.
Definition at line 887 of file VirtualInstrumentManager.cs.
References NoteOutputObject.PauseAudio().
Referenced by VirtualInstrumentManager.SetUpEvents().
    {
        mSongOutput.PauseAudio();
    }
OnPlayDrumLoopEvent()
void VirtualInstrumentManager.OnPlayDrumLoopEvent (Song aLoop)
Begins playing a drum loop. It creates an array of audio data from each note of the Song and sends it to the right NoteOutputObject.
Parameters
in aLoop The drum loop to play.
This function begins playing drum loops which are handled differently from other songs. Special handling of offsets and the number of waveform samples in the loop is required in order to make the loop as seamless as possible.
Definition at line 901 of file VirtualInstrumentManager.cs.
References NoteOutputObject.BeingPlaying(), VirtualInstrument.GetAdjustedVelocityFactor(), VirtualInstrument.GetAudioDataForPitch(), VirtualInstrument.GetBuiltInDynamicsThresholdIndex(), Song.GetNoteData(), NoteOutputObject.SetAudioData(), NoteOutputObject.SetLoop(), and Song.CombinedNoteData.TotalOffset.
Referenced by VirtualInstrumentManager.SetUpEvents().
    {
        // Get the song's note data.
        Song.CombinedNoteData[] loopNoteData = aLoop.
      GetNoteData();
        // Get the number of notes in the loop.
        int numNotes = loopNoteData.Length;
        // Get the number of waveform samples in the loop.
        int numSamples = loopNoteData[numNotes - 1].TotalOffset;
        // Get the start index for the loop.
        int startIndex = loopNoteData[0].TotalOffset;
        // Allocate a 2-D array for the song's audio data.
        float[][] loopAudioData = new float[1][];
        loopAudioData[0] = new float[numSamples];
        // Make some variables to keep track of the velocity and offset.
        int offset = 0;
        int velocity = 0;
        int velIndex = 0;
        float velFactor = 0f;
        // Iterate through all of the notes.
        for(int i = 0; i < numNotes; i++)
        {
            // In order to loop, the offset for the last note is set to 0.
            if(i == numNotes - 1)
            {
                offset = 0;
            }
            else
            {
                offset = loopNoteData[i].TotalOffset;
            }
            
            // Get the velocity from the note.
            velocity = loopNoteData[i].PercussionData.Velocity;
            // Get the associated dynamics index and velocity factor.
            velIndex = mDrumKit.GetBuiltInDynamicsThresholdIndex(
      velocity);
            velFactor = mDrumKit.GetAdjustedVelocityFactor(velocity);
            // Add the audio data for all of the drums in the note.
            for(int j = 0; j < loopNoteData[i].PercussionData.Hits.Length; j++)
            {
                // Get the audio data for the note.
                float[][] drumAudioData = mDrumKit.GetAudioDataForPitch((
      Music.PITCH)(loopNoteData[i].PercussionData.Hits[j]));
                // Put all of the samples from the drum's audio data into the song audio data.
                int audioDataIndex = 0;
                int loopDataIndex = offset;
                // Account for silencing hi-hats if needed.
                int numSamplesUntilNextHiHat = numSamples;
                if(loopNoteData[i].PercussionData.Hits[j] == Music.DRUM.HIHAT_O)
                {
                    int nextHiHatIndex = i+1;
                    bool nextHiHatFound = false;
                    // Get the next hi hat hit by iterating through the notes.
                    while(nextHiHatIndex != i && !nextHiHatFound)
                    {
                        // Make sure we don't have any index out of bounds errors.
                        if(nextHiHatIndex == numNotes)
                        {
                            nextHiHatIndex = 0;
                        }
                        // See if this note has hi-hat hits. Break the loop if so.
                        if(loopNoteData[nextHiHatIndex].PercussionData.HasHiHat)
                        {
                            nextHiHatFound = true;
                            numSamplesUntilNextHiHat = loopNoteData[nextHiHatIndex].TotalOffset -
      loopNoteData[i].TotalOffset;
                            if(numSamplesUntilNextHiHat < 0)
                            {
                                numSamplesUntilNextHiHat = (-1 * numSamplesUntilNextHiHat) + (numSamples
       - loopNoteData[i].TotalOffset);
                            }
                        }
                        else
                        {
                            // Go to the next note if this note doesn't have any hi-hat hits.
                            nextHiHatIndex++;
                        }
                    }
                }
                // Put the audio data for the drum into the loop.
                while(audioDataIndex < drumAudioData[velIndex].Length && numSamplesUntilNextHiHat > 0)
                {
                    loopAudioData[0][loopDataIndex] += (drumAudioData[velIndex][audioDataIndex] *
      velFactor);
                    loopDataIndex++;
                    // Account for bleeding over into the next loop.
                    if(loopDataIndex >= numSamples)
                    {
                        loopDataIndex = 0;
                    }
                    audioDataIndex++;
                    numSamplesUntilNextHiHat--;
                }
            }
        }
        // Set the song output object's audio data and begin playing the song.
        mDrumLoopOutput.SetAudioData(loopAudioData,
      mMixer, null);
        mDrumLoopOutput.SetLoop(true);
        mDrumLoopOutput.BeingPlaying(1f, 0, startIndex);
    }
OnPlayNoteEvent()
void VirtualInstrumentManager.OnPlayNoteEvent (Music.PITCH aNoteToPlay, int aVelocity)
Called whenever a note should be played. Uses the appropriate NoteOutputObject to play the note.
Parameters
in aNoteToPlay The pitch of the note to play
in aVelocity The velocity at which to play the pitch.
See also
VirtualInstrumentManager::PlayNoteEvent Music::PITCH NoteOutputObject::BeginPlaying
Definition at line 1021 of file VirtualInstrumentManager.cs.
References NoteOutputObject.BeingPlaying(), VirtualInstrument.GetAdjustedVelocityFactor(), VirtualInstrument.GetBuiltInDynamicsThresholdIndex(), VirtualInstrumentManager.mHighestActiveNote, VirtualInstrumentManager.mInstrumentType, VirtualInstrumentManager.mLowestActiveNote, and Music.NoteToString().
Referenced by VirtualInstrumentManager.SetUpEvents().
    {
        if(mReady)
        {
            // Sanity checks.
            Assert.IsTrue((int)aNoteToPlay >= (int)mLowestActiveNote && (int)aNoteToPlay
      <= (int)mHighestActiveNote,
                "Tried to play the note " + Music.NoteToString(aNoteToPlay) + " which is
       not active!");
            Assert.IsTrue(aVelocity <= 100 && aVelocity >= 0,
                "Tried to play a note with a velocity of " + aVelocity.ToString() + " which is not within
       the range from 0 to 100!");
            // Get the note index.
            int noteIndex = (int)aNoteToPlay - (int)mLowestActiveNote;
            // Account for drum kits where we would need to make some outputs silent in some situations.
            // Ex: Playing a closed hi-hat should stop an open hi-hat that is still playing.
            if(mInstrumentType == Music.INSTRUMENT_TYPE.DRUM_KIT)
            {
                switch((Music.DRUM)aNoteToPlay)
                {
                    case Music.DRUM.HIHAT_C:
                        mOutputs[(int)Music.DRUM.HIHAT_O].
      BeingPlaying(0, 0);
                        mOutputs[(int)Music.DRUM.HIHAT_P].
      BeingPlaying(0, 0);
                        break;
                    case Music.DRUM.HIHAT_O:
                        mOutputs[(int)Music.DRUM.HIHAT_C].
      BeingPlaying(0, 0);
                        mOutputs[(int)Music.DRUM.HIHAT_P].
      BeingPlaying(0, 0);
                        break;
                    case Music.DRUM.HIHAT_P:
                        mOutputs[(int)Music.DRUM.HIHAT_C].
      BeingPlaying(0, 0);
                        mOutputs[(int)Music.DRUM.HIHAT_O].
      BeingPlaying(0, 0);
                        break;
                    default:
                        break;
                }
            }
            // Get the built-in dynamics index and the velocity factor.
            int velIndex = mInstrument.
      GetBuiltInDynamicsThresholdIndex(aVelocity);
            float velFactor = mInstrument.GetAdjustedVelocityFactor(
      aVelocity);
            // Begin playing the note.
            mOutputs[noteIndex].BeingPlaying(velFactor, velIndex, 0);
        }
    }
OnPlaySongEvent()
void VirtualInstrumentManager.OnPlaySongEvent (Song aSong)
Begins playing a song. It creates an array of audio data from each note of the Song and sends it to the right NoteOutputObject.
Parameters
in aSong The song to play.
Definition at line 1071 of file VirtualInstrumentManager.cs.
References NoteOutputObject.BeingPlaying(), VirtualInstrument.GetAdjustedVelocityFactor(), VirtualInstrument.GetAudioDataForPitch(), VirtualInstrument.GetBuiltInDynamicsThresholdIndex(), Song.GetNoteData(), Song.GetSongType(), NoteOutputObject.SetAudioData(), and Song.CombinedNoteData.TotalOffset.
Referenced by VirtualInstrumentManager.SetUpEvents().
    {
        // Get the song's note data.
        Song.CombinedNoteData[] songNoteData = aSong.
      GetNoteData();
        // Get the number of notes in the song.
        int numNotes = songNoteData.Length;
        // Get the total number of samples in the song.
        int numSamples = 0;
        if(aSong.GetSongType() != Song.SongType.DrumLoop)
        {
            for(int i = 0; i < numNotes; i++)
            {
                numSamples = Mathf.Max((songNoteData[i].MelodyData.NumSamples + songNoteData[i].
      TotalOffset), numSamples);
            }
        }
        else
        {
            numSamples = 0;
            for(int i = 0; i < songNoteData[numNotes - 1].PercussionData.Hits.Length; i++)
            {
                if(numSamples < (songNoteData[numNotes - 1].TotalOffset +
                    mDrumKit.GetAudioDataForPitch((
      Music.PITCH)(songNoteData[numNotes - 1].PercussionData.Hits[i]))[0].Length))
                {
                    numSamples = songNoteData[numNotes - 1].TotalOffset +
                        mDrumKit.GetAudioDataForPitch((
      Music.PITCH)(songNoteData[numNotes - 1].PercussionData.Hits[i]))[0].Length;
                }
            }
        }
        // Allocate a 2-D array for the song's audio data.
        float[][] songAudioData = new float[1][];
        songAudioData[0] = new float[numSamples];
        // Make some variables to keep track of the velocity and offset.
        int offset = 0;
        int velocity = 0;
        int velIndex = 0;
        float velFactor = 0f;
        // Iterate through all of the notes.
        for(int i = 0; i < numNotes; i++)
        {
            // If the note is a rest, we don't need to worry its pitches. Otherwise, add the note's
       pitches.
            if(songNoteData[i].MelodyData.Pitches != null && songNoteData[i].MelodyData.Pitches[0] !=
      Music.PITCH.REST)
            {
                // Get the offset and velocity from the note.
                offset = songNoteData[i].TotalOffset;
                velocity = songNoteData[i].MelodyData.Velocity;
                // Get the associated dynamics index and velocity factor.
                velIndex = mInstrument.
      GetBuiltInDynamicsThresholdIndex(velocity);
                velFactor = mInstrument.GetAdjustedVelocityFactor(
      velocity);
                // Add the audio data for all of the pitches in the note.
                for(int j = 0; j < songNoteData[i].MelodyData.Pitches.Length; j++)
                {
                    // Get the audio data for the note.
                    float[][] pitchAudioData = mInstrument.
      GetAudioDataForPitch(songNoteData[i].MelodyData.Pitches[j]);
                    // Put all of the samples from the pitch's audio data into the song audio data.
                    int k = 0;
                    while(k < songNoteData[i].MelodyData.NumSamples && k < pitchAudioData[velIndex].Length
       )
                    {
                        songAudioData[0][k + offset] += (pitchAudioData[velIndex][k] * velFactor);
                        k++;
                    }
                    // Adjust for when the note is released.
                    float releaseFactor = velFactor;
                    while(k < pitchAudioData[velIndex].Length && k + offset < numSamples && releaseFactor
       > 0)
                    {
                        songAudioData[0][k + offset] += pitchAudioData[velIndex][k] * releaseFactor;
                        releaseFactor -= (1f / 22500f);
                        k++;
                    }
                    // Cleanup
                    pitchAudioData = null;
                }
            }
            // If the note has drums, then add them.
            if(songNoteData[i].PercussionData.Hits != null)
            {
                // Get the offset and velocity from the note.
                offset = songNoteData[i].TotalOffset;
                velocity = songNoteData[i].PercussionData.Velocity;
                // Get the associated dynamics index and velocity factor.
                velIndex = mDrumKit.GetBuiltInDynamicsThresholdIndex
      (velocity);
                velFactor = mDrumKit.GetAdjustedVelocityFactor(velocity)
      ;
                // Add the audio data for all of the drums in the note.
                for(int j = 0; j < songNoteData[i].PercussionData.Hits.Length; j++)
                {
                    // Get the audio data for the note.
                    float[][] drumAudioData = mDrumKit.
      GetAudioDataForPitch((Music.PITCH)(songNoteData[i].PercussionData.Hits[j])
       );
                    // Put all of the samples from the drum's audio data into the song audio data.
                    int audioDataIndex = 0;
                    int drumDataIndex = offset;
                    // Account for silencing hi-hats if needed.
                    int numSamplesUntilNextHiHat = numSamples;
                    if(songNoteData[i].PercussionData.Hits[j] == Music.
      DRUM.HIHAT_O)
                    {
                        int nextHiHatIndex = i+1;
                        bool nextHiHatFound = false;
                        // Get the next hi hat hit by iterating through the notes.
                        while(nextHiHatIndex != i && !nextHiHatFound)
                        {
                            // Make sure we don't have any index out of bounds errors.
                            if(nextHiHatIndex == numNotes)
                            {
                                nextHiHatIndex = 0;
                            }
                            // See if this note has hi-hat hits. Break the loop if so.
                            if(songNoteData[nextHiHatIndex].PercussionData.HasHiHat)
                            {
                                nextHiHatFound = true;
                                numSamplesUntilNextHiHat = songNoteData[nextHiHatIndex].TotalOffset -
      songNoteData[i].TotalOffset;
                                if(numSamplesUntilNextHiHat < 0)
                                {
                                    numSamplesUntilNextHiHat = (-1 * numSamplesUntilNextHiHat) + (
      numSamples - songNoteData[i].TotalOffset);
                                }
                            }
                            else
                            {
                                // Go to the next note if this note doesn't have any hi-hat hits.
                                nextHiHatIndex++;
                            }
                        }
                    }
                    // Put the audio data for the drum into the song.
                    while(audioDataIndex < drumAudioData[velIndex].Length && numSamplesUntilNextHiHat > 0
      && drumDataIndex < numSamples)
                    {
                        songAudioData[0][drumDataIndex] += (drumAudioData[velIndex][audioDataIndex] *
      velFactor);
                        drumDataIndex++;
                        audioDataIndex++;
                        numSamplesUntilNextHiHat--;
                    }
                    // Cleanup
                    drumAudioData = null;
                }
            }
        }
        // Set the song output object's audio data and begin playing the song.
        mSongOutput.SetAudioData(songAudioData, mMixer, null);
        mSongOutput.BeingPlaying(1f, 0);
        // Cleanup
        songAudioData = null;
        GC.Collect();
    }
OnReleaseNoteEvent()
void VirtualInstrumentManager.OnReleaseNoteEvent (Music.PITCH aNoteToRelease)
Called whenever a note should be released. Uses the appropriate NoteOutputObject to release the note.
Parameters
in aNoteToRelease The pitch of the note to release
See also
VirtualInstrumentManager::PlayNoteEvent Music::PITCH NoteOutputObject::BeginRelease
Definition at line 1243 of file VirtualInstrumentManager.cs.
References NoteOutputObject.BeginRelease(), VirtualInstrumentManager.mHighestActiveNote, VirtualInstrumentManager.mInstrumentType, VirtualInstrumentManager.mLowestActiveNote, and Music.NoteToString().
Referenced by VirtualInstrumentManager.SetUpEvents().
    {
        // Don't account for note releases for drums.
        if(mInstrumentType != Music.INSTRUMENT_TYPE.DRUM_KIT)
        {
            Assert.IsTrue((int)aNoteToRelease >= (int)mLowestActiveNote && (int)
      aNoteToRelease <= (int)mHighestActiveNote,
                "Tried to fade out the note " + Music.NoteToString(aNoteToRelease) + "
       which is not active!");
            int noteIndex = (int)aNoteToRelease - (int)mLowestActiveNote;
            mOutputs[noteIndex].BeginRelease();
        }
    }
OnResumeDrumLoopEvent()
void VirtualInstrumentManager.OnResumeDrumLoopEvent ()
Handles resuming a drum loop.
Definition at line 1258 of file VirtualInstrumentManager.cs.
References NoteOutputObject.ResumeAudio().
Referenced by VirtualInstrumentManager.SetUpEvents().
    {
        mDrumLoopOutput.ResumeAudio();
    }
OnResumeSongEvent()
void VirtualInstrumentManager.OnResumeSongEvent ()
Handles resuming a song.
Definition at line 1266 of file VirtualInstrumentManager.cs.
References NoteOutputObject.ResumeAudio().
Referenced by VirtualInstrumentManager.SetUpEvents().
    {
        mSongOutput.ResumeAudio();
    }
OnStopDrumLoopEvent()
void VirtualInstrumentManager.OnStopDrumLoopEvent ()
Handles stopping a drum loop.
Definition at line 1274 of file VirtualInstrumentManager.cs.
References NoteOutputObject.StopAudio().
Referenced by VirtualInstrumentManager.SetUpEvents().
    {
        mDrumLoopOutput.StopAudio();
    }
OnStopSongEvent()
void VirtualInstrumentManager.OnStopSongEvent ()
Handles stopping a song.
Definition at line 1282 of file VirtualInstrumentManager.cs.
References NoteOutputObject.StopAudio().
Referenced by VirtualInstrumentManager.SetUpEvents().
    {
        mSongOutput.StopAudio();
    }