Public Functions
Functions
int VirtualInstrument.GetBuiltInDynamicsThresholdIndex (int aVelocity)
Gets the index for which sound file to use for a pitch at a given velocity.
int [] VirtualInstrument.GetBuiltInDynamicsThresholds ()
Gets the ranges for which sound file to use for a velocity.
float VirtualInstrument.GetAdjustedVelocityFactor (int aVelocity)
Gets the factor by which a note's waveform is scaled in order to account for velocity.
Music.PITCH VirtualInstrument.GetHighestSupportedPitch ()
Gets the highest pitch that this instrument can play.
Music.PITCH VirtualInstrument.GetLowestSupportedPitch ()
Gets the lowest pitch that this instrument can play.
int VirtualInstrument.GetNumOfSupportedPitches ()
Gets the total number of pitches that this instrument can play.
float [][] VirtualInstrument.GetAudioDataForPitch (Music.PITCH aPitch)
Gets the raw audio data of each built-in dynamics value for a given pitch.
float VirtualInstrument.GetSampleInterval ()
Gets the time interval between waveform samples for this instrument.
int VirtualInstrument.GetSampleRate ()
Gets the sample rate for the wav files used to create the instrument.
bool VirtualInstrument.IsLoaded ()
Gets whether or not the instrument has loaded.
bool VirtualInstrument.IsPitchSupported (Music.PITCH aPitch)
Gets whether or not the instrument can play a specific pitch.
Detailed Description
Functions for other classes (usually the parent manager) to get values from the instrument.
Function Documentation
GetAdjustedVelocityFactor()
float VirtualInstrument.GetAdjustedVelocityFactor (int aVelocity)
Gets the factor by which a note's waveform is scaled in order to account for velocity.
Parameters
in aVelocity The velocity for the note from 0 (silent) to 100 (max volume).
Returns
A float between 0.0 and 1.0 where 0.0 means that the waveform should be made silent and 1.0 means that it should be unaltered.
Instruments without Built-In Dynamics just divide the given velocity by 100, but instruments with Built-in Dynamics map the factor to a ratio involving the Built-In Dynamics thresholds so that the volumes for velocities near a threshold don't have significant differences.
Definition at line 140 of file VirtualInstrument.cs.
Referenced by VirtualInstrumentManager.OnPlayDrumLoopEvent(), VirtualInstrumentManager.OnPlayNoteEvent(), and VirtualInstrumentManager.OnPlaySongEvent().
    {
        int dynamicsIndex = 0;
        float velocityFactor = aVelocity / 100f;
        // Calculate the velocity multiplier. The multiplier is a percentage that is used to adjust the
        // levels of the audio data to modify the output volume.
        // If built-in dynamics are supported, then the velocity multiplier will range from the lower
       threshold divided by the higher threshold to 1.0.
        if(mNumBuiltInDynamics != 0)
        {
            // See which built-in dynamics value we need to use. Start at the top threshold and work down.
            for(int i = mNumBuiltInDynamics - 1; i > -1; i--)
            {
                if(aVelocity <= mBuiltInDynamicsThresholds[i])
                {
                    dynamicsIndex = i;
                }
            }
            // Calculate the velocity factor.
            float inEnd = (float)mBuiltInDynamicsThresholds[dynamicsIndex];
            float outEnd = 1f;
            float inStart = 0f;
            float outStart = 0f;
            if(dynamicsIndex != 0)
            {
                inStart = (float)mBuiltInDynamicsThresholds[dynamicsIndex - 1];
                outStart = (float)mBuiltInDynamicsThresholds[dynamicsIndex - 1] /
       (float)mBuiltInDynamicsThresholds[dynamicsIndex];
            }
            velocityFactor = outStart + (((outEnd - outStart) / (inEnd - inStart)) * ((float)
      aVelocity - inStart));
        }
        // If built-in dynamics are not supported, then just use the given velocity as a percentage.
        return velocityFactor;
    }
GetAudioDataForPitch()
float [][] VirtualInstrument.GetAudioDataForPitch (Music.PITCH aPitch)
Gets the raw audio data of each built-in dynamics value for a given pitch.
Parameters
in aPitch The pitch for which the data is retrieved.
Returns
a 2-D array of floats where the indices correspond to [BuiltInDynamicsIndex][WaveformSample].
The array is retrived by mapping the given pitch to the second index of the mAudioData member.
Definition at line 209 of file VirtualInstrument.cs.
References VirtualInstrument.LoadAudioClipForPitch(), VirtualInstrument.mHighestSupportedPitch, VirtualInstrument.mLowestSupportedPitch, VirtualInstrument.mNumBuiltInDynamics, and Music.NoteToString().
Referenced by VirtualInstrumentManager.LoadNoteOutputObjects(), VirtualInstrumentManager.OnPlayDrumLoopEvent(), and VirtualInstrumentManager.OnPlaySongEvent().
    {
        Assert.IsTrue((int)aPitch >= (int)mLowestSupportedPitch && (int)aPitch <= (
      int)mHighestSupportedPitch,
            "Tried to load the audio data for the note " + Music.
      NoteToString(aPitch) + " which is not a note that is supported by this instrument!");
        Assert.IsNotNull(mAudioData, "Tried to get data from a non-loaded virtual instrument!")
      ;
        // If we need to load the clip, then load it.
        if(mAudioData[0][(int)aPitch] == null)
        {
            LoadAudioClipForPitch(aPitch);
        }
        // Declare the returned array.
        float[][] data = null;
        // If there aren't any built-in dynamics, then use a hard-coded index and copy the data to the
       array from the audio clip.
        if(mNumBuiltInDynamics == 0)
        {
            data = new float[1][];
            int dataLength = mAudioData[0][(int)aPitch].Length;
            data[0] = new float[dataLength];
            for(int i = 0; i < dataLength; i++)
            {
                data[0][i] = mAudioData[0][(int)aPitch][i];
            }
        }
        // If there are built-in dynamics, then get the data from the audio clips for each corresponding
       file.
        else
        {
            data = new float[mNumBuiltInDynamics][];
            int dataLength = 0;
            for(int i = 0; i < mNumBuiltInDynamics; i++)
            {
                dataLength = mAudioData[i][(int)aPitch].Length;
                data[i] = new float[dataLength];
                for(int j = 0; j < dataLength; j++)
                {
                    data[i][j] = mAudioData[i][(int)aPitch][j];
                }
            }
        }
        return data;
    }
GetBuiltInDynamicsThresholdIndex()
int VirtualInstrument.GetBuiltInDynamicsThresholdIndex (int aVelocity)
Gets the index for which sound file to use for a pitch at a given velocity.
Parameters
in aVelocity The given velocity from 0 (silent) to 100 (max volume).
Returns
The index of the sound file to use.
For instruments with Built-In Dynamics (such as the Piano), this function takes a velocity and returns the index of the sound file to use for playing the sound. If a function does not support Built-In Dynamics, this function returns 0.
See also
Built-In Dynamics Thresholds.
Definition at line 98 of file VirtualInstrument.cs.
Referenced by VirtualInstrumentManager.OnPlayDrumLoopEvent(), VirtualInstrumentManager.OnPlayNoteEvent(), and VirtualInstrumentManager.OnPlaySongEvent().
    {
        // If there aren't any built-in dynamics, then just return 0.
        if(mNumBuiltInDynamics == 0)
        {
            return 0;
        }
        // If there are built-in dynamics, then start from the highest and work down to find
        // which one to use.
        else
        {
            int dynamicsIndex = 0;
            for(int i = mNumBuiltInDynamics - 1; i > -1; i--)
            {
                if(aVelocity <= mBuiltInDynamicsThresholds[i])
                {
                    dynamicsIndex = i;
                }
            }
            return dynamicsIndex;
        }
    }
GetBuiltInDynamicsThresholds()
int [] VirtualInstrument.GetBuiltInDynamicsThresholds ()
Gets the ranges for which sound file to use for a velocity.
Returns
If the instrument supports Built-In Dynamics, then return its thresholds. Return null otherwise.
Definition at line 125 of file VirtualInstrument.cs.
References VirtualInstrument.mBuiltInDynamicsThresholds.
Referenced by VirtualInstrumentManager.LoadNoteOutputObjects().
    {
        return mBuiltInDynamicsThresholds;
    }
GetHighestSupportedPitch()
Music.PITCH VirtualInstrument.GetHighestSupportedPitch ()
Gets the highest pitch that this instrument can play.
Returns
The highest pitch that this instrument can play.
Definition at line 179 of file VirtualInstrument.cs.
References VirtualInstrument.mHighestSupportedPitch.
Referenced by VirtualInstrumentManager.GetHighestSupportedNote().
    {
        return mHighestSupportedPitch;
    }
GetLowestSupportedPitch()
Music.PITCH VirtualInstrument.GetLowestSupportedPitch ()
Gets the lowest pitch that this instrument can play.
Returns
The lowest pitch supported by the instrument.
Definition at line 188 of file VirtualInstrument.cs.
References VirtualInstrument.mLowestSupportedPitch.
Referenced by VirtualInstrumentManager.GetLowestSupportedNote().
    {
        return mLowestSupportedPitch;
    }
GetNumOfSupportedPitches()
int VirtualInstrument.GetNumOfSupportedPitches ()
Gets the total number of pitches that this instrument can play.
Returns
The total number of pitches that the instrument can play.
Definition at line 197 of file VirtualInstrument.cs.
References VirtualInstrument.mNumSupportedPitches.
    {
        return mNumSupportedPitches;
    }
GetSampleInterval()
float VirtualInstrument.GetSampleInterval ()
Gets the time interval between waveform samples for this instrument.
Returns
The time interval between waveform samples for this instrument
Definition at line 258 of file VirtualInstrument.cs.
References VirtualInstrument.mSampleInterval.
    {
        return mSampleInterval;
    }
GetSampleRate()
int VirtualInstrument.GetSampleRate ()
Gets the sample rate for the wav files used to create the instrument.
Returns
The sample rate of the wav files used to create the instrument.
Definition at line 267 of file VirtualInstrument.cs.
References VirtualInstrument.mSampleRate.
    {
        return mSampleRate;
    }
IsLoaded()
bool VirtualInstrument.IsLoaded ()
Gets whether or not the instrument has loaded.
Returns
True if the instrument has loaded. False otherwise.
Definition at line 276 of file VirtualInstrument.cs.
References VirtualInstrument.mLoaded.
    {
        return mLoaded;
    }
IsPitchSupported()
bool VirtualInstrument.IsPitchSupported (Music.PITCH aPitch)
Gets whether or not the instrument can play a specific pitch.
Parameters
in aPitch The pitch that is being checked.
Returns
True if the pitch can be played by the instrument. False otherwise.
Definition at line 286 of file VirtualInstrument.cs.
References VirtualInstrument.mHighestSupportedPitch, and VirtualInstrument.mLowestSupportedPitch.
Referenced by VirtualInstrumentManager.OnChangeNoteRangeEvent().
    {
        return ((int)aPitch >= (int)mLowestSupportedPitch && (int)aPitch <= (int)
      mHighestSupportedPitch);
    }