Public Functions
Functions
Music.PITCH [] SC_PitchSelectionContainer.GetSelectedPitches ()
Gets the currently selected pitches/drums.
void SC_PitchSelectionContainer.ResetPitches ()
Resets the selected selected pitches/drums.
void SC_PitchSelectionContainer.SetPitches (Music.PITCH[] aPitches)
Sets the selected pitches/drums.
void SC_PitchSelectionContainer.SetUpAsDrumSelector ()
Sets up this selection container as a selector for drums.
void SC_PitchSelectionContainer.SetUpAsPitchSelector ()
Sets up this selection container as a selector for pitches.
Detailed Description
Functions for other classes to interact with the SC_PitchSelectionContainer
Function Documentation
GetSelectedPitches()
Music.PITCH [] SC_PitchSelectionContainer.GetSelectedPitches ()
Gets the currently selected pitches/drums.
Returns
The currently selected pitches/drums.
Definition at line 47 of file SC_PitchSelectionContainer.cs.
Referenced by SongCreationManager.OnCreateNote(), and SongCreationManager.OnModifyNote().
    {
        Music.PITCH[] returned = null;
        // If we're currently a rest note, return the rest pitch
        if(mRestNote)
        {
            returned = new Music.PITCH[1];
            returned[0] = Music.PITCH.REST;
        }
        // If there aren't any pitches selected, then return null.
        else if(mSelectedPitches.Count == 0)
        {
            return null;
        }
        // If we're not currently a rest note and some pitches are selected, then return all of the
       selected pitches.
        else
        {
            int index = 0;
            returned = new Music.PITCH[mSelectedPitches.Count];
            foreach(int pitch in mSelectedPitches)
            {
                returned[index] = (Music.PITCH)mSelectedPitches[index];
                index++;
            }
        }
        return returned;
    }
ResetPitches()
void SC_PitchSelectionContainer.ResetPitches ()
Resets the selected selected pitches/drums.
Definition at line 79 of file SC_PitchSelectionContainer.cs.
References SC_PitchSelectionTrigger.SetSelection().
Referenced by SongCreationManager.OnCreateNote(), SongCreationManager.OnEditEvent(), SongCreationManager.OnModifyNote(), and SC_PitchSelectionContainer.SetPitches().
    {
        // Reset the child objects.
        foreach(int pitch in mSelectedPitches)
        {
            mPitchSelectionTriggers[pitch].SetSelection(false);
        }
        // Update the rest note pitch.
        mRestNote = false;
        // Clear the list.
        mSelectedPitches.Clear();
    }
SetPitches()
void SC_PitchSelectionContainer.SetPitches (Music.PITCH [] aPitches)
Sets the selected pitches/drums.
Parameters
in aPitches The pitches/drums that should be selected.
Definition at line 99 of file SC_PitchSelectionContainer.cs.
References SC_PitchSelectionContainer.ResetPitches().
Referenced by SongCreationManager.OnEditEvent().
    {
        // Reset the pitches.
        ResetPitches();
        // Make sure that there are pitches to set.
        if(aPitches != null)
        {
            // Set the pitches
            foreach(Music.PITCH pitch in aPitches)
            {
                if(pitch != Music.PITCH.REST)
                {
                    mPitchSelectionTriggers[(int)pitch].SetSelection(true);
                    mSelectedPitches.Add((int)pitch);
                }
                else
                {
                    mRestNote = true;
                    mRest.isOn = true;
                }
            }
        }
    }
SetUpAsDrumSelector()
void SC_PitchSelectionContainer.SetUpAsDrumSelector ()
Sets up this selection container as a selector for drums.
The only difference is the ability to set the selected pitch as a rest note, the number of toggle switches, their text, and the number of triggers.
Definition at line 132 of file SC_PitchSelectionContainer.cs.
References Music.DrumToString(), Music.MAX_SUPPORTED_DRUMS, SC_PitchSelectionTrigger.SetHandler(), and SC_PitchSelectionTrigger.SetIndex().
Referenced by SongCreationManager.Awake().
    {
        // Create the list of selected pitches, the array of toggle switches, and the array of triggers.
        mSelectedPitches = new List<int>();
        mPitches = new Toggle[Music.MAX_SUPPORTED_DRUMS];
        mPitchSelectionTriggers = new
      SC_PitchSelectionTrigger[Music.MAX_SUPPORTED_DRUMS];
        // Get the first toggle switch and set its text
        mPitches[0] = gameObject.transform.GetChild(0).GetComponent<Toggle>();
        mPitches[0].transform.GetChild(1).GetComponent<Text>().text = "KICK_1";
        // Set up the first pitch selection trigger.
        mPitchSelectionTriggers[0] = mPitches[0].gameObject.AddComponent<
      SC_PitchSelectionTrigger>();
        mPitchSelectionTriggers[0].SetHandler(this);
        mPitchSelectionTriggers[0].SetIndex(0);
        mPitchSelectionTriggers[0].SetSelection(false);
        // Clone the first pitch object and modify it for each drum.
        for(int i = 1; i < Music.MAX_SUPPORTED_DRUMS; i++)
        {
            // Copy the first drum and set its parent.
            mPitches[i] = Instantiate(mPitches[0]).GetComponent<Toggle>();
            mPitches[i].transform.SetParent(gameObject.transform);
            // Set the copy's text
            mPitches[i].transform.GetChild(1).GetComponent<Text>().text =
      Music.DrumToString(i);
            // Set up the clone's SC_PitchSelectionTrigger.
            mPitchSelectionTriggers[i] = mPitches[i].GetComponent<
      SC_PitchSelectionTrigger>();
            mPitchSelectionTriggers[i].SetIndex(i);
            mPitchSelectionTriggers[i].SetHandler(this);
        }
        // Make sure that everything is sized appropriately.
        mPitches[0].transform.localScale = mPitches[1].transform.localScale;
    }
SetUpAsPitchSelector()
void SC_PitchSelectionContainer.SetUpAsPitchSelector ()
Sets up this selection container as a selector for pitches.
The only difference is the ability to set the selected pitch as a rest note, the number of toggle switches, their text, and the number of triggers.
Definition at line 177 of file SC_PitchSelectionContainer.cs.
References Music.MAX_SUPPORTED_NOTES, Music.NoteToString(), SC_PitchSelectionContainer.OnRestToggle(), SC_PitchSelectionTrigger.SetHandler(), and SC_PitchSelectionTrigger.SetIndex().
    {
        // Create the list of selected pitches, the array of toggle switches, and the array of triggers.
        mSelectedPitches = new List<int>();
        mPitches = new Toggle[Music.MAX_SUPPORTED_NOTES + 1];
        mPitchSelectionTriggers = new
      SC_PitchSelectionTrigger[Music.MAX_SUPPORTED_NOTES + 1];
        // Get the first toggle switch and set its text
        mPitches[0] = gameObject.transform.GetChild(0).GetComponent<Toggle>();
        mPitches[0].transform.GetChild(1).GetComponent<Text>().text = "C0";
        // Set up the first pitch selection trigger.
        mPitchSelectionTriggers[0] = mPitches[0].gameObject.AddComponent<
      SC_PitchSelectionTrigger>();
        mPitchSelectionTriggers[0].SetHandler(this);
        mPitchSelectionTriggers[0].SetIndex(0);
        mPitchSelectionTriggers[0].SetSelection(false);
        // Clone the first pitch object and modify it for each pitch.
        string temp = null;
        for(int i = 1; i < Music.MAX_SUPPORTED_NOTES; i++)
        {
            // Copy the first pitch and set its parent.
            mPitches[i] = Instantiate(mPitches[0]).GetComponent<Toggle>();
            mPitches[i].transform.SetParent(gameObject.transform);
            // Set the copy's text.
            temp = Music.NoteToString(i);
            if(temp.Contains("S"))
            {
                char[] tempArray = temp.ToCharArray();
                tempArray[1] = '#';
                temp = new string(tempArray);
            }
            mPitches[i].transform.GetChild(1).GetComponent<Text>().text = temp;
            // Set up the clone's SC_PitchSelectionTrigger.
            mPitchSelectionTriggers[i] = mPitches[i].GetComponent<
      SC_PitchSelectionTrigger>();
            mPitchSelectionTriggers[i].SetIndex(i);
            mPitchSelectionTriggers[i].SetHandler(this);
        }
        // Make sure that everything is sized appropriately.
        mPitches[0].transform.localScale = mPitches[1].transform.localScale;
        // Create the rest note selection.
        mRest = Instantiate(mPitches[0]).GetComponent<Toggle>();
        DestroyImmediate(mRest.GetComponent<SC_PitchSelectionTrigger>(),
      false);
        mRest.transform.SetParent(gameObject.transform);
        mRest.onValueChanged.AddListener(OnRestToggle);
        mRest.transform.GetChild(1).GetComponent<Text>().text = "Rest";
        mRest.transform.localScale = mPitches[1].transform.localScale;
    }