Unity Functions
Modules
Event Handlers
Functions
void ATI_Buttons.Awake ()
Gets references to the buttons and adds their listeners. Called when the object is created.
void ATI_Buttons.OnLoadKeyboardSceneButtonClicked ()
Loads the song creation interface scene.
void ATI_Buttons.OnLoadSongCreationButtonClicked ()
Loads the song creation interface scene.
Detailed Description
These are functions automatically called by Unity.
Function Documentation
Awake()
void ATI_Buttons.Awake () [private]
Gets references to the buttons and adds their listeners. Called when the object is created.
Definition at line 35 of file ATI_Buttons.cs.
References ATI_Buttons.OnLoadKeyboardSceneButtonClicked(), and ATI_Buttons.OnLoadSongCreationButtonClicked().
    {
        // Get the buttons.
        mLoadSongCreationButton = transform.GetChild(0).GetComponent<Button>();
        Assert.IsNotNull(mLoadSongCreationButton, "Could not find the button to
       load the Song Creation Interface!");
        mLoadKeyboardSceneButton = transform.GetChild(1).GetComponent<Button>();
        Assert.IsNotNull(mLoadKeyboardSceneButton, "Could not find the button to
       load the Keyboard scene!");
        // Add the listeners.
        mLoadSongCreationButton.onClick.AddListener(
      OnLoadSongCreationButtonClicked);
        mLoadKeyboardSceneButton.onClick.AddListener(
      OnLoadKeyboardSceneButtonClicked);
    }
OnLoadKeyboardSceneButtonClicked()
void ATI_Buttons.OnLoadKeyboardSceneButtonClicked () [private]
Loads the song creation interface scene.
Definition at line 60 of file ATI_Buttons.cs.
Referenced by ATI_Buttons.Awake().
    {
        SceneManager.LoadScene("KeyboardScene", LoadSceneMode.Single);
    }
OnLoadSongCreationButtonClicked()
void ATI_Buttons.OnLoadSongCreationButtonClicked () [private]
Loads the song creation interface scene.
Definition at line 68 of file ATI_Buttons.cs.
Referenced by ATI_Buttons.Awake().
    {
        SceneManager.LoadScene("SongCreationInterfaceScene", LoadSceneMode.Additive);
    }