Musical Typing Event Handlers
Functions
void MusicalTypingHandler.OnMusicalTypingEvent (Event aKeyEvent)
Handler for Musical Typing Events.
Detailed Description
Functions used to handle Musical Typing events.
Function Documentation
OnMusicalTypingEvent()
void MusicalTypingHandler.OnMusicalTypingEvent (Event aKeyEvent) [private]
Handler for Musical Typing Events.
Parameters
in aKeyEvent A GUI keyboard event triggered by a key being pressed or released.
This function sees if a pressed/released key is one that is used for Musical Typing. If so, it simulates a note event based on the pressed/released key.
Definition at line 192 of file MusicalTypingHandler.cs.
References VirtualInstrumentManager.GetActiveNotes(), VirtualInstrumentManager.GetNumActiveNotes(), VirtualInstrumentManager.PlayNote, VirtualInstrumentManager.ReleaseNote, and ATI_Diagnostics.SetInputTime.
Referenced by MusicalTypingHandler.OnGUI().
    {
        // Check if a musical typing key is pressed or released and fire off the
        // corresponding PlayNote or NoteFadeOut event if so. The debug velocity is
        // used for the events.
        int i = 0;
        int numActive = mVIM.GetNumActiveNotes();
        while(MusicalTypingEnabled && i <
      DEBUG_numMusicalTypingKeys && i < numActive)
        {
            // See if the key is a Musical Typing key.
            if(aKeyEvent.keyCode == DEBUG_musicalTypingKeys[i])
            {
                // If the key was pressed, then simulate a NotePlayEvent.
                if(aKeyEvent.type == EventType.KeyDown && !mPressedKeys[i])
                {
                    #if DEBUG_AUDIO_DIAGNOSTICS
                        mDiagnosticsHandler.SetInputTime.Invoke();
                    #endif
                    // Update the pressed keys
                    mPressedKeys[i] = true;
                    // Get the velocity that should be used.
                    int velocity = mKeyVelocities[i];
                    if(RandomizeVelocities)
                    {
                        velocity = UnityEngine.Random.Range(
      mRandomVelocityRange[0], mRandomVelocityRange[1]);
                    }
                    mVIM.PlayNote.Invoke(mVIM.GetActiveNotes()[i], velocity
      );
                }
                // If the key was released, then simulate a ReleaseNoteEvent.
                if(aKeyEvent.type == EventType.KeyUp)
                {
                    // Update the pressed keys
                    mPressedKeys[i] = false;
                    mVIM.ReleaseNote.Invoke(mVIM.
      GetActiveNotes()[i]);
                }
            }
            i++;
        }
    }