Coroutines
Functions
IEnumerator VirtualInstrumentManager.LoadDrumKit (System.Action< VirtualInstrument > aDrumKitCallback)
Coroutine to load the drum kit.
IEnumerator VirtualInstrumentManager.LoadInstrument (Music.INSTRUMENT_TYPE aINSTRUMENT_TYPE, System.Action< VirtualInstrument > aInstrumentCallback)
Coroutine to load an instrument.
Detailed Description
These are functions that are started by the VirtualInstrumentManager which allows it to perform other tasks while waiting.
Function Documentation
LoadDrumKit()
IEnumerator VirtualInstrumentManager.LoadDrumKit (System.Action< VirtualInstrument > aDrumKitCallback) [private]
Coroutine to load the drum kit.
Parameters
out aDrumKitCallback Callback to allow returning the loaded instrument to the calling context.
See also
DrumKit Music::INSTRUMENT_TYPE VirtualInstrumentManager::mDrumKit
Definition at line 657 of file VirtualInstrumentManager.cs.
Referenced by VirtualInstrumentManager.Awake().
    {
        // Load a new instrument
        VirtualInstrument returned = new DrumKit(this);
        // Return the loaded instrument and invoke the instrument's LoadEvent.
        aDrumKitCallback(returned);
        //DrumKitLoaded.Invoke();
        yield return null;
    }
LoadInstrument()
IEnumerator VirtualInstrumentManager.LoadInstrument (Music.INSTRUMENT_TYPE aINSTRUMENT_TYPE, System.Action< VirtualInstrument > aInstrumentCallback) [private]
Coroutine to load an instrument.
Parameters
in aINSTRUMENT_TYPE The type of instrument to load.
out aInstrumentCallback Callback to allow returning the loaded instrument to the calling context.
See also
VirtualInstrument Music::INSTRUMENT_TYPE VirtualInstrumentManager::mInstrument
Definition at line 675 of file VirtualInstrumentManager.cs.
Referenced by VirtualInstrumentManager.Awake(), and VirtualInstrumentManager.OnChangeInstrumentEvent().
    {
        // Load a new instrument
        VirtualInstrument returned = null;
        switch(aINSTRUMENT_TYPE)
        {
            case Music.INSTRUMENT_TYPE.DRUM_KIT:
                returned = new DrumKit(this);
                break;
            case Music.INSTRUMENT_TYPE.MARIMBA:
                returned = new Marimba(this);
                break;
            case Music.INSTRUMENT_TYPE.PIANO:
            default:
                returned = new Piano(this);
                break;
        }
        // Return the loaded instrument and invoke the instrument's LoadEvent.
        aInstrumentCallback(returned);
        InstrumentLoaded.Invoke();
        yield return null;
    }