Public Functions
Functions
void SC_MeasureDisplayPanel.AddNote (int aNoteIndex, int aMelodyVelocity, Music.NOTE_LENGTH aLength, Music.PITCH[] aPitches, int aDrumVelocity, Music.DRUM[] aDrumHits, Music.NOTE_LENGTH aOffsetFromPrevNote)
Adds a note to the list of notes managed by this panel.
void SC_MeasureDisplayPanel.ClearMeasure ()
Clears the notes in the measure and self-destructs.
void SC_MeasureDisplayPanel.SetParentContainer (SC_NoteDisplayContainer aParent)
Sets the parent container.
void SC_MeasureDisplayPanel.SetPercentageUsed (float aPercent)
Sets the percentage of the measure that is filled.
void SC_MeasureDisplayPanel.SetToggle (bool aShowMeasure)
Sets whether or not the measure should be shown.
Detailed Description
Functions for other classes to interact with the SC_MeasureDisplayPanel.
Function Documentation
AddNote()
void SC_MeasureDisplayPanel.AddNote (int aNoteIndex, int aMelodyVelocity, Music.NOTE_LENGTH aLength, Music.PITCH [] aPitches, int aDrumVelocity, Music.DRUM [] aDrumHits, Music.NOTE_LENGTH aOffsetFromPrevNote)
Adds a note to the list of notes managed by this panel.
Parameters
in aNoteIndex The index of the note in the overall Song.
in aMelodyVelocity The velocity of the pitches in the note.
in aLength The length of the note.
in aPitches The pitches in the note.
in aDrumVelocity The velocity of the drums in the note.
in aDrumHits The drums that are hit for this note.
in aOffsetFromPrevNote The offset from the previous note.
This function also creates the SC_NoteDisplayPanel object for the note.
Definition at line 81 of file SC_MeasureDisplayPanel.cs.
References Music.DrumToString(), Music.GetNoteLengthRelativeToMeasure(), SC_NoteDisplayContainer.GetSprites(), SC_NoteDisplayContainer.HandleFullMeasure(), Music.NoteToString(), SC_NoteDisplayPanel.SetDrums(), SC_NoteDisplayPanel.SetLengthImage(), SC_NoteDisplayPanel.SetNoteIndex(), SC_NoteDisplayPanel.SetOffset(), SC_NoteDisplayPanel.SetOffsetImage(), SC_NoteDisplayPanel.SetParentContainer(), SC_NoteDisplayPanel.SetPitches(), SC_NoteDisplayPanel.SetVelocity(), and Music.TIME_SIGNATURE_4_4().
    {
        // Declare variables to help create the note.
        Sprite[] sprites = mParent.GetSprites();
        string pitches = "None";
        string drums = "None";
        // Calculate the percentage used up in the measure.
        float newPercentage = mPercentageUsed + Music.
      GetNoteLengthRelativeToMeasure(aOffsetFromPrevNote,
      Music.TIME_SIGNATURE_4_4());
        // If there is no more room in the measure for this note, then send it back to the parent.
        if(newPercentage >= 1f)
        {
            mParent.HandleFullMeasure(this, newPercentage -
      mPercentageUsed, aMelodyVelocity, aLength, aPitches, aDrumVelocity, aDrumHits,
      aOffsetFromPrevNote);
        }
        // If there is more room, then create the new panel and add it to this measure.
        else
        {
            // Update the percentage used.
            mPercentageUsed = newPercentage;
            // Create a SC_NoteDisplayPanel
            GameObject clone = null;
            clone = Instantiate(Resources.Load<GameObject>(
      NOTE_DISPLAY_PANEL_PATH));
            Assert.IsNotNull(clone, "Could not load SC_NoteDisplayPanel prefab!");
            // Set the values for the note's transform.
            clone.transform.SetParent(transform.parent);
            clone.transform.localScale = Vector3.one;
            // Set the pitch string if needed.
            if(aPitches != null)
            {
                pitches = "";
                for(int i = 0; i < aPitches.Length; i++)
                {
                    if(aPitches[i] == Music.PITCH.REST)
                    {
                        pitches += "Rest ";
                    }
                    else
                    {
                        pitches += (Music.NoteToString(aPitches[i]) + " ");
                    }
                }
            }
            // Set the drum string if needed.
            if(aDrumHits != null)
            {
                drums = "";
                foreach(Music.DRUM drum in aDrumHits)
                {
                    drums += Music.DrumToString(drum) + " ";
                }
            }
            // Initialize the cloned panel.
            SC_NoteDisplayPanel newPanel = clone.AddComponent<
      SC_NoteDisplayPanel>();
            newPanel.SetDrums(drums);
            newPanel.SetPitches(pitches);
            newPanel.SetLengthImage(sprites[(int)aLength]);
            newPanel.SetOffsetImage(sprites[(int)aOffsetFromPrevNote]);
            newPanel.SetOffset(aOffsetFromPrevNote);
            newPanel.SetVelocity(aMelodyVelocity.ToString());
            newPanel.SetParentContainer(this);
            newPanel.SetNoteIndex(aNoteIndex);
            // Add the panel to the list.
            mNotes.Add(newPanel);
        }
    }
ClearMeasure()
void SC_MeasureDisplayPanel.ClearMeasure ()
Clears the notes in the measure and self-destructs.
Definition at line 160 of file SC_MeasureDisplayPanel.cs.
    {
        foreach(SC_NoteDisplayPanel note in mNotes)
        {
            DestroyImmediate(note.gameObject, false);
        }
        DestroyImmediate(gameObject, false);
    }
SetParentContainer()
void SC_MeasureDisplayPanel.SetParentContainer (SC_NoteDisplayContainer aParent)
Sets the parent container.
Parameters
in aParent The parent container.
Definition at line 173 of file SC_MeasureDisplayPanel.cs.
    {
        // Set the parent.
        mParent = aParent;
    }
SetPercentageUsed()
void SC_MeasureDisplayPanel.SetPercentageUsed (float aPercent)
Sets the percentage of the measure that is filled.
Parameters
in aPercent How full the measure is.
See also
Song::GetNoteLengthRelativeToMeasure
Definition at line 185 of file SC_MeasureDisplayPanel.cs.
    {
        mPercentageUsed = aPercent;
    }
SetToggle()
void SC_MeasureDisplayPanel.SetToggle (bool aShowMeasure)
Sets whether or not the measure should be shown.
Parameters
in aShowMeasure True if the measure should be shown. False otherwise.
Definition at line 194 of file SC_MeasureDisplayPanel.cs.
References SC_MeasureDisplayPanel.OnShowToggle().
Referenced by SC_NoteDisplayContainer.HandleMeasureToggled().
    {
        // Show/Hide the notes in the measure depending on the given bool.
        foreach(SC_NoteDisplayPanel note in mNotes)
        {
            note.gameObject.SetActive(aShowMeasure);
        }
        // Update the toggle value.
        mShowMeasureToggle.onValueChanged.RemoveListener(
      OnShowToggle);
        mShowMeasureToggle.isOn = aShowMeasure;
        mShowMeasureToggle.onValueChanged.AddListener(
      OnShowToggle);
    }