Event Handlers
Functions
void KeyContainer.HandleAudioToggle (bool aAudioEnabled)
Allows for other objects to toggle the audio.
void KeyContainer.HandleBlackKeyPressed (BlackKey aBlackKey)
Handles a black key in the container being pressed.
void KeyContainer.HandleBlackKeyReleased (BlackKey aBlackKey)
Handles a black key in the container being released.
void KeyContainer.HandleChangeNoteRangeEvent (Music.PITCH aNewLowestPitch)
Handles a change in the note range.
void KeyContainer.HandleWhiteKeyPressed (WhiteKey aWhiteKey)
Handles a white key in the container being pressed.
void KeyContainer.HandleWhiteKeyReleased (WhiteKey aWhiteKey)
Handles a white key in the container being released.
void KeyContainer.HandlePlaySongEvent (Song aSong)
Handler for when a song begins playing.
IEnumerator KeyContainer.DrawLessonMarker (int aIndex, float aDelay, float aStop)
Handles drawing the lesson markers.
Detailed Description
Functions used internally by the KeyContainer to handle events.
Function Documentation
DrawLessonMarker()
IEnumerator KeyContainer.DrawLessonMarker (int aIndex, float aDelay, float aStop) [private]
Handles drawing the lesson markers.
Parameters
in aIndex The index of the key the draw the marker on.
in aDelay The delay of when to draw the marker.
in aStop How long the marker should be drawn.
Definition at line 453 of file KeyContainer.cs.
Referenced by KeyContainer.HandlePlaySongEvent().
    {
        yield return new WaitForSeconds(aDelay);
        mLessonMarkers[aIndex].SetActive(true);
        yield return new WaitForSeconds(aStop);
        mLessonMarkers[aIndex].SetActive(false);
        yield return null;
    }
HandleAudioToggle()
void KeyContainer.HandleAudioToggle (bool aAudioEnabled)
Allows for other objects to toggle the audio.
Parameters
in aAudioEnabled Whether or not the audio should be enabled.
Definition at line 304 of file KeyContainer.cs.
    {
        EnableAudio = aAudioEnabled;
    }
HandleBlackKeyPressed()
void KeyContainer.HandleBlackKeyPressed (BlackKey aBlackKey) [private]
Handles a black key in the container being pressed.
Parameters
in aBlackKey The black key that was pressed.
Definition at line 313 of file KeyContainer.cs.
References VirtualInstrumentManager.GetDiagnosticsHandler(), BlackKey.Pitch, VirtualInstrumentManager.PlayNote, and ATI_Diagnostics.SetInputTime.
Referenced by KeyContainer.LoadKeys().
    {
        if(EnableAudio && mVIM != null)
        {
            #if DEBUG_AUDIO_DIAGNOSTICS
                mVIM.GetDiagnosticsHandler().
      SetInputTime.Invoke();
            #endif
            mVIM.PlayNote.Invoke(aBlackKey.Pitch, 100);
        }
    }
HandleBlackKeyReleased()
void KeyContainer.HandleBlackKeyReleased (BlackKey aBlackKey) [private]
Handles a black key in the container being released.
Parameters
in aBlackKey The black key that was released.
Definition at line 329 of file KeyContainer.cs.
References BlackKey.Pitch, and VirtualInstrumentManager.ReleaseNote.
Referenced by KeyContainer.LoadKeys().
    {
        if(EnableAudio && mVIM != null)
        {
            mVIM.ReleaseNote.Invoke(aBlackKey.Pitch);
        }
    }
HandleChangeNoteRangeEvent()
void KeyContainer.HandleChangeNoteRangeEvent (Music.PITCH aNewLowestPitch) [private]
Handles a change in the note range.
Parameters
in aNewLowestPitch The lowest pitch of the new range.
Sets the represented pitches and loads a new part of the keyboard for a changed note range.
See also
VirtualInstrumentManager::ChangeNoteRangeEvent Music::PITCH
Definition at line 344 of file KeyContainer.cs.
References KeyContainer.ClearKeyboard(), Music.IsPitchABlackKey(), KeyContainer.LoadKeys(), KeyContainer.mRepresentedPitches, and KeyContainer.NUM_KEYS.
Referenced by KeyContainer.Update().
    {
        // Clear the keyboard.
        ClearKeyboard();
        mNumWhiteKeys = 0;
        // Update the represented pitches.
        for(int i = 0; i < NUM_KEYS; i++)
        {
            mRepresentedPitches[i] = (Music.PITCH)(i + (int)aNewLowestPitch)
      ;
            if(!Music.IsPitchABlackKey(
      mRepresentedPitches[i]))
            {
                mNumWhiteKeys++;
            }
        }
        // Load the keys.
        LoadKeys();
    }
HandlePlaySongEvent()
void KeyContainer.HandlePlaySongEvent (Song aSong) [private]
Handler for when a song begins playing.
Parameters
in aSong The song that began playing.
Definition at line 396 of file KeyContainer.cs.
References KeyContainer.ClearKeyboard(), KeyContainer.DrawLessonMarker(), Song.GetHighestPitch(), Song.GetLowestPitch(), Song.GetNoteData(), Music.IsPitchABlackKey(), KeyContainer.LoadKeys(), KeyContainer.mRepresentedPitches, and VirtualInstrument.SAMPLE_INTERVAL.
Referenced by KeyContainer.Update().
    {
        // Keep track of the current key layout.
        Music.PITCH[] currentLayout = mRepresentedPitches;
        // Get the highest note in the song.
        Music.PITCH highestPitch = aSong.GetHighestPitch();
        // Get the lowest note in the song.
        Music.PITCH lowestPitch = aSong.GetLowestPitch();
        // Get the song data.
        Song.CombinedNoteData[] noteData = aSong.GetNoteData();
        // Clear the keyboard.
        ClearKeyboard();
        // Set the range of keys.
        mRepresentedPitches = null;
        int numPitches = (int)highestPitch - (int)lowestPitch + 1;
        mRepresentedPitches = new Music.PITCH[numPitches];
        mNumWhiteKeys = 0;
        for(int i = 0; i < numPitches; i++)
        {
            mRepresentedPitches[i] = (Music.PITCH)((int)lowestPitch + i);
            if(!Music.IsPitchABlackKey(
      mRepresentedPitches[i]))
            {
                mNumWhiteKeys++;
            }
        }
        // Load the proper keys.
        LoadKeys();
        // Get the sample interval (seconds between waveform samples.)
        float sampInt = VirtualInstrument.SAMPLE_INTERVAL;
        // Draw the lesson markers for each pitch.
        foreach(Song.CombinedNoteData note in noteData)
        {
            if(note.MelodyData.Pitches != null)
            {
                foreach(Music.PITCH pitch in note.MelodyData.Pitches)
                {
                    StartCoroutine(DrawLessonMarker((int)pitch - (int)lowestPitch, (float
      )note.TotalOffset * sampInt, (note.MelodyData.NumSamples * sampInt) - .02f));
                }
            }
        }
    }
HandleWhiteKeyPressed()
void KeyContainer.HandleWhiteKeyPressed (WhiteKey aWhiteKey) [private]
Handles a white key in the container being pressed.
Parameters
in aWhiteKey The white key that was pressed.
Definition at line 368 of file KeyContainer.cs.
References VirtualInstrumentManager.GetDiagnosticsHandler(), WhiteKey.Pitch, VirtualInstrumentManager.PlayNote, and ATI_Diagnostics.SetInputTime.
Referenced by KeyContainer.LoadKeys().
    {
        if(EnableAudio && mVIM != null)
        {
            #if DEBUG_AUDIO_DIAGNOSTICS
                mVIM.GetDiagnosticsHandler().
      SetInputTime.Invoke();
            #endif
            mVIM.PlayNote.Invoke(aWhiteKey.Pitch, 100);
        }
    }
HandleWhiteKeyReleased()
void KeyContainer.HandleWhiteKeyReleased (WhiteKey aWhiteKey) [private]
Handles a white key in the container being released.
Parameters
in aWhiteKey The white key that was released.
Definition at line 384 of file KeyContainer.cs.
References WhiteKey.Pitch, and VirtualInstrumentManager.ReleaseNote.
Referenced by KeyContainer.LoadKeys().
    {
        if(EnableAudio && mVIM != null)
        {
            mVIM.ReleaseNote.Invoke(aWhiteKey.Pitch);
        }
    }