Event Handlers
Functions
void SC_PitchSelectionContainer.HandlePitchSelection (bool aSelected, int aIndex)
void SC_PitchSelectionContainer.OnRestToggle (bool aIsRestNote)
Handles switching between this note being a rest note or not.
Detailed Description
Functions called by the SC_PitchSelectionContainer in response to events.
Function Documentation
HandlePitchSelection()
void SC_PitchSelectionContainer.HandlePitchSelection (bool aSelected, int aIndex)
Handles a pitch being selected.
Parameters
in aSelected True if the pitch/drum is selected. False otherwise.
in aIndex The index of the trigger that was selected/unselected.
Definition at line 244 of file SC_PitchSelectionContainer.cs.
References Music.NoteToString(), and SC_PitchSelectionTrigger.SetSelection().
Referenced by SC_PitchSelectionTrigger.OnPitchSelected().
    {
        // If this pitch was selected and the note is note currently set to be a rest note,
        // then add it to the list.
        if(aSelected && !mRestNote)
        {
            mSelectedPitches.Add(aIndex);
            foreach(int pitch in mSelectedPitches)
            {
                Debug.Log(Music.NoteToString(pitch));
            }
        }
        // If the pitch was unselected and the note is not currently set to be a rest note,
        // then remove it from the list.
        else if(!mRestNote)
        {
            mSelectedPitches.Remove(aIndex);
            foreach(int pitch in mSelectedPitches)
            {
                Debug.Log(Music.NoteToString(pitch));
            }
        }
        // If the pitch was selected and we are currently set to be a rest note, then unselect the note.
        else if(aSelected && mRestNote)
        {
            mPitchSelectionTriggers[aIndex].SetSelection(false);
        }
    }
OnRestToggle()
void SC_PitchSelectionContainer.OnRestToggle (bool aIsRestNote)
Handles switching between this note being a rest note or not.
Parameters
in aIsRestNote True if the note is a rest note. False otherwise.
Definition at line 278 of file SC_PitchSelectionContainer.cs.
References SC_PitchSelectionTrigger.SetSelection().
Referenced by SC_PitchSelectionContainer.SetUpAsPitchSelector().
    {
        mRestNote = aIsRestNote;
        // If this note is now a rest note, then make sure that no other pitches are selected.
        if(mRestNote)
        {
            foreach(int pitch in mSelectedPitches)
            {
                mPitchSelectionTriggers[pitch].
      SetSelection(false);
            }
        }
        // If this note is no longer a rest note, then restore the selected pitches.
        else
        {
            foreach(int pitch in mSelectedPitches)
            {
                mPitchSelectionTriggers[pitch].
      SetSelection(true);
            }
        }
    }