Implemented Virtual Functions
Functions
override void DrumKit.InitializeBuiltInDynamics ()
Initializes values related to the Built-In Dynamics for this instrument.
override void DrumKit.CreateFilenames ()
Creates the filenames for each drum wav file.
Detailed Description
Functions from the base class that are implemented specifically for DrumKits
Function Documentation
CreateFilenames()
override void DrumKit.CreateFilenames () [protected], [virtual]
Creates the filenames for each drum wav file.
The files are stored in `Resources/Audio/VirtualInstrument/DrumKit/Samples`.
Reimplemented from VirtualInstrument.
Definition at line 83 of file DrumKit.cs.
References Music.DrumToString(), VirtualInstrument.mFilenames, VirtualInstrument.mFilepath, VirtualInstrument.mHighestSupportedPitch, VirtualInstrument.mLowestSupportedPitch, and VirtualInstrument.mNumFiles.
Referenced by DrumKit.DrumKit().
    {
        // Set the base filepath and number of files.
        mFilepath = "Audio/VirtualInstrument/DrumKit/Samples/";
        mNumFiles = 18;
        // Initialize the array of filenames.
        mFilenames = new string[mNumFiles];
        // Iterate through each dynamics value and create filenames for each supported note.
        int index = 0;
        for(int i = (int)mLowestSupportedPitch; i <= (int)
      mHighestSupportedPitch; i++)
        {
            mFilenames[index] = mFilepath + Music.
      DrumToString(i);
            index++;
        }
    }
InitializeBuiltInDynamics()
override void DrumKit.InitializeBuiltInDynamics () [protected], [virtual]
Initializes values related to the Built-In Dynamics for this instrument.
Note
There are (currently) no Built-In Dynamics for the DrumKit. This just sets the variables such that other functions will know that it is not supported.
Reimplemented from VirtualInstrument.
Definition at line 66 of file DrumKit.cs.
References VirtualInstrument.mAudioData, Music.MAX_SUPPORTED_DRUMS, VirtualInstrument.mBuiltInDynamics, VirtualInstrument.mBuiltInDynamicsThresholds, and VirtualInstrument.mNumBuiltInDynamics.
Referenced by DrumKit.DrumKit().
    {
        // There are no built-in dynamics for the drum kit (yet).
        mNumBuiltInDynamics = 0;
        mBuiltInDynamics = null;
        mBuiltInDynamicsThresholds = null;
        // Allocate the audio data container.
        mAudioData = new float[1][][];
        mAudioData[0] = new float[Music.MAX_SUPPORTED_DRUMS][];
    }