Public Functions
Functions
void SC_PitchSelectionTrigger.SetHandler (SC_PitchSelectionContainer aHandler)
Sets the parent handler.
void SC_PitchSelectionTrigger.SetIndex (int aIndex)
Sets the index of this trigger in the parent handler.
void SC_PitchSelectionTrigger.SetSelection (bool aSelected)
Sets whether or not this trigger is selected.
Detailed Description
These are functions that allow other classes to interact with the SC_PitchSelectionTrigger.
Function Documentation
SetHandler()
void SC_PitchSelectionTrigger.SetHandler (SC_PitchSelectionContainer aHandler)
Sets the parent handler.
Parameters
in aHandler The parent handler.
Definition at line 57 of file SC_PitchSelectionTrigger.cs.
Referenced by SC_PitchSelectionContainer.SetUpAsDrumSelector(), and SC_PitchSelectionContainer.SetUpAsPitchSelector().
    {
        mHandler = aHandler;
    }
SetIndex()
void SC_PitchSelectionTrigger.SetIndex (int aIndex)
Sets the index of this trigger in the parent handler.
Parameters
in aIndex The index of this trigger in the parent handler.
Definition at line 66 of file SC_PitchSelectionTrigger.cs.
Referenced by SC_PitchSelectionContainer.SetUpAsDrumSelector(), and SC_PitchSelectionContainer.SetUpAsPitchSelector().
    {
        mIndex = aIndex;
    }
SetSelection()
void SC_PitchSelectionTrigger.SetSelection (bool aSelected)
Sets whether or not this trigger is selected.
Parameters
in aSelected True if the trigger is selected. False otherwise.
Definition at line 75 of file SC_PitchSelectionTrigger.cs.
References SC_PitchSelectionTrigger.OnPitchSelected().
Referenced by SC_PitchSelectionContainer.HandlePitchSelection(), SC_PitchSelectionContainer.OnRestToggle(), and SC_PitchSelectionContainer.ResetPitches().
    {
        // Update the toggle switch.
        mToggle.onValueChanged.RemoveListener(OnPitchSelected);
        mToggle.isOn = aSelected;
        mToggle.onValueChanged.AddListener(OnPitchSelected);
    }