Protected Functions
Functions
void VirtualInstrument.LoadAudioClipForPitch (Music.PITCH aPitch)
Loads all the audio clips associated with a pitch.
void VirtualInstrument.LoadAudioClips ()
Loads the audio clips for the instrument. VirtualInstrument::CreateFilenames must be called prior to this function in order to actually find the files.
Detailed Description
Functions that are used by the subclasses.
Function Documentation
LoadAudioClipForPitch()
void VirtualInstrument.LoadAudioClipForPitch (Music.PITCH aPitch) [protected]
Loads all the audio clips associated with a pitch.
Parameters
in aPitch The pitch to load the audio clips for.
Definition at line 304 of file VirtualInstrument.cs.
References VirtualInstrument.mHighestSupportedPitch, VirtualInstrument.mLowestSupportedPitch, VirtualInstrument.mNumBuiltInDynamics, VirtualInstrument.mNumSupportedPitches, VirtualInstrument.NormalizeAudioClipsForPitch(), and Music.NoteToString().
Referenced by VirtualInstrument.GetAudioDataForPitch().
    {
        Assert.IsTrue(aPitch >= mLowestSupportedPitch && aPitch <=
      mHighestSupportedPitch,
            "Tried to load the pitch " + Music.NoteToString(aPitch) + ", but that's out
       of the instrument's range from " +
            Music.NoteToString(mLowestSupportedPitch) + " to " +
      Music.NoteToString(mHighestSupportedPitch));
        // Get the file index.
        int fileIndex = (int)aPitch - (int)mLowestSupportedPitch;
        
        // Get the audio clips for the pitch.
        AudioClip[] clips = null;
        // If Built-In Dynamics are not supported, then just get the one clip.
        if(mNumBuiltInDynamics == 0)
        {
            // Get the audio file.
            clips = new AudioClip[1];
            clips[0] = Resources.Load<AudioClip>(mFilenames[fileIndex]);
            Assert.IsNotNull(clips[0], "Failed to load audioclip from file " +
      mFilenames[fileIndex]);
            // Load the audio data.
            clips[0].LoadAudioData();
            // Normalize the clip.
            NormalizeAudioClipsForPitch(aPitch, clips);
        }
        // If Built-In Dynamics are supported, then get all of the associated clips.
        else
        {
            // Allocate space for the clips.
            clips = new AudioClip[mNumBuiltInDynamics];
            // Load the clips.
            for(int i = 0; i < mNumBuiltInDynamics; i++)
            {
                // Load the wav file.
                clips[i] = Resources.Load<AudioClip>(mFilenames[fileIndex]);
                Assert.IsNotNull(clips[0], "Failed to load audioclip from file " +
      mFilenames[fileIndex]);
                // Load the audio data into the AudioClip.
                clips[i].LoadAudioData();
                // Go to the next file.
                fileIndex += mNumSupportedPitches;
            }
            // Normalize the clips.
            NormalizeAudioClipsForPitch(aPitch, clips);
        }
        // Clean up.
        clips = null;
        Resources.UnloadUnusedAssets();
        GC.Collect();
    }
LoadAudioClips()
void VirtualInstrument.LoadAudioClips () [protected]
Loads the audio clips for the instrument. VirtualInstrument::CreateFilenames must be called prior to this function in order to actually find the files.
This function handles the loading of the audio clips, getting their audio data, and passing the audio data to VirtualInstrument::NormalizeAudioClips().
Definition at line 366 of file VirtualInstrument.cs.
References Music.MAX_SUPPORTED_DRUMS, Music.MAX_SUPPORTED_NOTES, VirtualInstrument.mHighestSupportedPitch, VirtualInstrument.mLowestSupportedPitch, VirtualInstrument.mNumBuiltInDynamics, and VirtualInstrument.NormalizeAudioClips().
    {
        // Initialize index variables so that all of the files can be iterated through and appropriately
        // assigned to an array of audio clips.
        int index = (int)mLowestSupportedPitch;
        int fileIndex = 0;
        AudioClip[][] audioClips = null;
        // If there aren't any built-in dynamics, then use a hard-coded index of 0 for the outer array.
        if(mNumBuiltInDynamics == 0)
        {
            // Initialize the array of audio clips. In order to account for instruments differing in the
       range of notes
            // that they support, the inner audio clip array is set to have an element for every possible
       note. Unsupported
            // notes will have null audio clips at their indices. Drum kits will not have to worry about
       this.
            audioClips = new AudioClip[1][];
            if(mIsDrum)
            {
                audioClips[0] = new AudioClip[Music.MAX_SUPPORTED_DRUMS];
            }
            else
            {
                audioClips[0] = new AudioClip[Music.MAX_SUPPORTED_NOTES];
            }
            // The indices of the loaded audio clips are mapped to their corresponding note.
            while(index <= (int)mHighestSupportedPitch)
            {
                // Load the audio clip into the audio clip array.
                audioClips[0][index] = Resources.Load<AudioClip>(mFilenames[fileIndex]);
                Assert.IsNotNull(audioClips[0][index], "Failed to load audioclip from file " +
      mFilenames[fileIndex]);
                // Load the audio data for the audio clip
                audioClips[0][index].LoadAudioData();
                // Increment the index variables.
                index++;
                fileIndex++;
                Assert.IsTrue(fileIndex <= mNumFiles, "Tried to load more files than were
       available. Recheck how many files are availabled for the virtual instrument");
            }
        }
        // If built-in dynamics are available for this instrument, then load audio clips for each built-in
       dynamics value.
        else
        {
            // Initializ the outer array of audio clips
            audioClips = new AudioClip[mNumBuiltInDynamics][];
            // Iterate through each outer array.
            for(int i = 0; i < mNumBuiltInDynamics; i++)
            {
                // Initialize the inner array of audio clips. In order to account for instruments differing
       in the range of notes
                // that they support, the inner audio clip array is set to have an element for every
       possible note. Unsupported
                // notes will have null audio clips at their indices. Drum kits will not have to worry
       about this.
                if(mIsDrum)
                {
                    audioClips[i] = new AudioClip[Music.MAX_SUPPORTED_DRUMS];
                }
                else
                {
                    audioClips[i] = new AudioClip[Music.MAX_SUPPORTED_NOTES];
                }
                // The indices of the loaded audio clips are mapped to their corresponding note.
                while(index <= (int)mHighestSupportedPitch)
                {
                    // Load the audio clip into the audio clip array.
                    audioClips[i][index] = Resources.Load<AudioClip>(mFilenames[fileIndex]);
                    Assert.IsNotNull(audioClips[0][index], "Failed to load audioclip from file " +
      mFilenames[fileIndex]);
                    // Load the audio data for the audio clip
                    audioClips[i][index].LoadAudioData();
                    // Increment the index variables.
                    index++;
                    fileIndex++;
                    Assert.IsTrue(fileIndex <= mNumFiles, "Tried to load more files than were
       available. Recheck how many files are availabled for the piano virtual instrument");
                }
                // Reset the note index when going to the next outer array.
                index = (int)mLowestSupportedPitch;
            }
        }
        // Normalize the audio clips.
        NormalizeAudioClips(audioClips);
        // Get rid of unused assets.
        audioClips = null;
        Resources.UnloadUnusedAssets();
        GC.Collect();
    }