Public Functions
Functions
Music.PITCH [] VirtualInstrumentManager.GetActiveNotes ()
Gets the array of active notes.
ATI_Diagnostics VirtualInstrumentManager.GetDiagnosticsHandler ()
Gets the audio diagnostics handler.
Music.PITCH VirtualInstrumentManager.GetHighestActiveNote ()
Gets the highest active note.
Music.PITCH VirtualInstrumentManager.GetHighestSupportedNote ()
Gets the highest note that is supported by the loaded instrument.
VirtualInstrument VirtualInstrumentManager.GetInstrument ()
Gets the loaded VirtualInstrument.
Music.PITCH VirtualInstrumentManager.GetLowestActiveNote ()
Gets the lowest active note.
Music.PITCH VirtualInstrumentManager.GetLowestSupportedNote ()
Gets the lowest note that is supported by the loaded instrument.
MusicalTypingHandler VirtualInstrumentManager.GetMusicalTypingHandler ()
int VirtualInstrumentManager.GetNumActiveNotes ()
Gets the number of notes that currently can be played.
Detailed Description
These are functions that allow other classes to retrieve information from the VirtualInstrumentManager
Function Documentation
GetActiveNotes()
Music.PITCH [] VirtualInstrumentManager.GetActiveNotes ()
Gets the array of active notes.
Returns
The array of active notes.
Definition at line 431 of file VirtualInstrumentManager.cs.
References VirtualInstrumentManager.mActiveNotes.
Referenced by MusicalTypingHandler.OnMusicalTypingEvent().
    {
        return mActiveNotes;
    }
GetDiagnosticsHandler()
ATI_Diagnostics VirtualInstrumentManager.GetDiagnosticsHandler ()
Gets the audio diagnostics handler.
Returns
The audio diagnostics handler.
Definition at line 441 of file VirtualInstrumentManager.cs.
References VirtualInstrumentManager.mDiagnosticsHandler.
Referenced by KeyContainer.HandleBlackKeyPressed(), KeyContainer.HandleWhiteKeyPressed(), MusicalTypingHandler.SetMusicalTypingVariables(), and NoteOutputObject.SetVIM().
        {
            return mDiagnosticsHandler;
        }
GetHighestActiveNote()
Music.PITCH VirtualInstrumentManager.GetHighestActiveNote ()
Gets the highest active note.
Definition at line 450 of file VirtualInstrumentManager.cs.
References VirtualInstrumentManager.mHighestActiveNote.
    {
        return mHighestActiveNote;
    }
GetHighestSupportedNote()
Music.PITCH VirtualInstrumentManager.GetHighestSupportedNote ()
Gets the highest note that is supported by the loaded instrument.
Definition at line 458 of file VirtualInstrumentManager.cs.
References VirtualInstrument.GetHighestSupportedPitch().
Referenced by ATI_NoteRangeSelectionHandler.HandleInstrumentLoaded().
    {
        return mInstrument.GetHighestSupportedPitch();
    }
GetInstrument()
VirtualInstrument VirtualInstrumentManager.GetInstrument ()
Gets the loaded VirtualInstrument.
Definition at line 466 of file VirtualInstrumentManager.cs.
References VirtualInstrumentManager.mInstrument.
    {
        return mInstrument;
    }
GetLowestActiveNote()
Music.PITCH VirtualInstrumentManager.GetLowestActiveNote ()
Gets the lowest active note.
Definition at line 474 of file VirtualInstrumentManager.cs.
References VirtualInstrumentManager.mLowestActiveNote.
Referenced by ATI_NoteRangeSelectionHandler.HandleInstrumentLoaded().
    {
        return mLowestActiveNote;
    }
GetLowestSupportedNote()
Music.PITCH VirtualInstrumentManager.GetLowestSupportedNote ()
Gets the lowest note that is supported by the loaded instrument.
Definition at line 482 of file VirtualInstrumentManager.cs.
References VirtualInstrument.GetLowestSupportedPitch().
Referenced by ATI_NoteRangeSelectionHandler.HandleInstrumentLoaded().
    {
        return mInstrument.GetLowestSupportedPitch();
    }
GetMusicalTypingHandler()
MusicalTypingHandler VirtualInstrumentManager.GetMusicalTypingHandler ()
Gets the Musical Typing Handler.
Returns
The Musical Typing Handler.
Definition at line 491 of file VirtualInstrumentManager.cs.
References VirtualInstrumentManager.mMusicalTypingHandler.
Referenced by ATI_VelocityHandler.HandleMusicalTypingKeyVelocityChange(), ATI_VelocityHandler.RandomizeKeyVelocities(), and KeyContainer.Update().
        {
            return mMusicalTypingHandler;
        }
GetNumActiveNotes()
int VirtualInstrumentManager.GetNumActiveNotes ()
Gets the number of notes that currently can be played.
Definition at line 500 of file VirtualInstrumentManager.cs.
References VirtualInstrumentManager.mNumActiveNotes.
Referenced by ATI_NoteRangeSelectionHandler.HandleInstrumentLoaded(), ATI_NoteRangeSelectionHandler.HandleNoteRangeChange(), and MusicalTypingHandler.OnMusicalTypingEvent().
    {
        return mNumActiveNotes;
    }