Public Functions
Functions
void SongManagerClass.AddSong (Song aSong)
Adds a Song to the SongManager.
List< string > SongManagerClass.GetCombinedSongNames ()
Gets the names of the loaded songs that have both percussion and melody.
List< Song > SongManagerClass.GetCombinedSongs ()
Gets the loaded songs that have both percussion and melody.
List< string > SongManagerClass.GetDrumLoopNames ()
Gets the names of the loaded drum loops.
List< Song > SongManagerClass.GetDrumLoops ()
Gets the loaded drum loops.
List< string > SongManagerClass.GetMelodyNames ()
Gets the names of the loaded melodies.
List< Song > SongManagerClass.GetMelodies ()
Gets the loaded melodies.
int SongManagerClass.GetNumberOfCombinedSongs ()
Gets the number of loaded Songs that have both drums and melody.
int SongManagerClass.GetNumberOfDrumLoops ()
Gets the number of loaded drum loops.
int SongManagerClass.GetNumberOfMelodies ()
Gets the number of loaded melodies.
Song SongManagerClass.GetSongByName (string aSongName)
Gets a specific Song.
List< string > SongManagerClass.GetSongNames ()
Gets the names of the loaded Songs.
List< Song > SongManagerClass.GetSongs ()
Gets all of the Songs.
Detailed Description
Functions that allow other classes to interact with the SongManagerClass.
Function Documentation
AddSong()
void SongManagerClass.AddSong (Song aSong)
Adds a Song to the SongManager.
Parameters
in aSong A new Song.
Definition at line 64 of file SongManagerClass.cs.
References Song.GetName(), and Song.GetSongType().
Referenced by SongCreationManager.OnSaveSong().
    {
        // Sanity Check
        Assert.IsNotNull(aSong, "Tried to add a song that didn't exist!");
        // Create the song entry.
        switch(aSong.GetSongType())
        {
            case Song.SongType.Melody:
                mMelodies.Add(aSong.GetName(), aSong);
                break;
            case Song.SongType.DrumLoop:
                mDrumLoops.Add(aSong.GetName(), aSong);
                mNumDrumLoops++;
                break;
            case Song.SongType.CombinedMelodyAndPercussion:
                mCombinedSongs.Add(aSong.GetName(), aSong);
                mNumCombinedSongs++;
                break;
        }
    }
GetCombinedSongNames()
List<string> SongManagerClass.GetCombinedSongNames ()
Gets the names of the loaded songs that have both percussion and melody.
Returns
A list of the names of the loaded songs that have both percussion and melody.
Definition at line 90 of file SongManagerClass.cs.
    {
        List<string> loopNames = new List<string>();
        foreach(string name in mCombinedSongs.Keys)
        {
            loopNames.Add(name);
        }
        return loopNames;
    }
GetCombinedSongs()
List<Song> SongManagerClass.GetCombinedSongs ()
Gets the loaded songs that have both percussion and melody.
Returns
A list of the loaded songs that have both percussion and melody.
Definition at line 105 of file SongManagerClass.cs.
    {
        List<Song> returned = new List<Song>();
        foreach(Song loop in mCombinedSongs.Values)
        {
            returned.Add(loop);
        }
        return returned;
    }
GetDrumLoopNames()
List<string> SongManagerClass.GetDrumLoopNames ()
Gets the names of the loaded drum loops.
Returns
A list of the names of the loaded drum loops.
Definition at line 121 of file SongManagerClass.cs.
    {
        List<string> loopNames = new List<string>();
        foreach(string name in mDrumLoops.Keys)
        {
            loopNames.Add(name);
        }
        return loopNames;
    }
GetDrumLoops()
List<Song> SongManagerClass.GetDrumLoops ()
Gets the loaded drum loops.
Returns
A list of the loaded drum loops.
Definition at line 136 of file SongManagerClass.cs.
    {
        List<Song> returned = new List<Song>();
        foreach(Song loop in mDrumLoops.Values)
        {
            returned.Add(loop);
        }
        return returned;
    }
GetMelodies()
List<Song> SongManagerClass.GetMelodies ()
Gets the loaded melodies.
Returns
A list of the loaded melodies.
Definition at line 167 of file SongManagerClass.cs.
    {
        List<Song> returned = new List<Song>();
        foreach(Song loop in mMelodies.Values)
        {
            returned.Add(loop);
        }
        return returned;
    }
GetMelodyNames()
List<string> SongManagerClass.GetMelodyNames ()
Gets the names of the loaded melodies.
Returns
A list of the names of the loaded melodies.
Definition at line 152 of file SongManagerClass.cs.
    {
        List<string> loopNames = new List<string>();
        foreach(string name in mMelodies.Keys)
        {
            loopNames.Add(name);
        }
        return loopNames;
    }
GetNumberOfCombinedSongs()
int SongManagerClass.GetNumberOfCombinedSongs ()
Gets the number of loaded Songs that have both drums and melody.
Returns
The number of loaded songs that have both drums and melody.
Definition at line 183 of file SongManagerClass.cs.
References SongManagerClass.mNumCombinedSongs.
    {
        return mNumCombinedSongs;
    }
GetNumberOfDrumLoops()
int SongManagerClass.GetNumberOfDrumLoops ()
Gets the number of loaded drum loops.
Returns
The number of loaded drum loops.
Definition at line 192 of file SongManagerClass.cs.
References SongManagerClass.mNumDrumLoops.
    {
        return mNumDrumLoops;
    }
GetNumberOfMelodies()
int SongManagerClass.GetNumberOfMelodies ()
Gets the number of loaded melodies.
Returns
The number of loaded melodies.
Definition at line 201 of file SongManagerClass.cs.
References SongManagerClass.mNumMelodies.
    {
        return mNumMelodies;
    }
GetSongByName()
Song SongManagerClass.GetSongByName (string aSongName)
Gets a specific Song.
Parameters
in aSongName The name of the Song to get.
Returns
The Song with the given name.
Note
Asserts if the name is not found, or returns null if compiled as a non-development build.
Definition at line 213 of file SongManagerClass.cs.
Referenced by ATI_DiagnosticsDemoSongHandler.LoadDemoSong(), ATI_DemoSongButtonHandler.LoadDemoSong(), and SC_LoadSongDialog.OnSongSelected().
    {
        // Sanity Check
        Assert.IsTrue(mMelodies.ContainsKey(aSongName) || mDrumLoops.ContainsKey(
      aSongName) || mCombinedSongs.ContainsKey(aSongName),
            "Tried to get the song " + aSongName + " which does not exist!");
        // Get the song.
        if(mCombinedSongs.ContainsKey(aSongName))
        {
            return mCombinedSongs[aSongName];
        }
        else if(mDrumLoops.ContainsKey(aSongName))
        {
            return mDrumLoops[aSongName];
        }
        else if(mMelodies.ContainsKey(aSongName))
        {
            return mMelodies[aSongName];
        }
        else
        {
            return null;
        }
    }
GetSongNames()
List<string> SongManagerClass.GetSongNames ()
Gets the names of the loaded Songs.
Returns
A list of all of the Songs\' names.
Definition at line 242 of file SongManagerClass.cs.
Referenced by SC_LoadSongDialog.Awake().
    {
        // Initialize the returned list.
        List<string> returned = new List<string>();
        // Get the song names.
        Dictionary<string,Song>.KeyCollection combinedSongNames = mCombinedSongs.Keys;
        Dictionary<string,Song>.KeyCollection drumLoopNames = mDrumLoops.Keys;
        Dictionary<string,Song>.KeyCollection melodyNames = mMelodies.Keys;
        // Get the combined song names.
        foreach(string name in combinedSongNames)
        {
            returned.Add(name);
        }
        // Get all of the drum loop names.
        foreach(string name in drumLoopNames)
        {
            returned.Add(name);
        }
        // Get the melody names.
        foreach(string name in melodyNames)
        {
            returned.Add(name);
        }
        // Return the list of song names.
        return returned;
    }
GetSongs()
List<Song> SongManagerClass.GetSongs ()
Gets all of the Songs.
Returns
A list of all of the loaded Songs.
Definition at line 278 of file SongManagerClass.cs.
Referenced by SC_LoadSongDialog.Awake().
    {
        List<Song> returned = new List<Song>();
        // Get the songs.
        Dictionary<string,Song>.ValueCollection combinedSongs = mCombinedSongs.Values;
        Dictionary<string,Song>.ValueCollection drumLoops = mDrumLoops.Values;
        Dictionary<string,Song>.ValueCollection melodies = mMelodies.Values;
        // Get the combined songs.
        foreach(Song song in combinedSongs)
        {
            returned.Add(song);
        }
        // Get all of the drum loops
        foreach(Song song in drumLoops)
        {
            returned.Add(song);
        }
        // Get the all of the melodies.
        foreach(Song song in melodies)
        {
            returned.Add(song);
        }
        // Return the songs.
        return returned;
    }