Event Handlers
Functions
void SC_PitchSelectionTrigger.OnPitchSelected (bool aSelected)
Handles when a the trigger is selected via the associated toggle switch by passing the event to the parent handler.
Detailed Description
These are functions that are called by the SC_PitchSelectionTrigger in response to events.
Function Documentation
OnPitchSelected()
void SC_PitchSelectionTrigger.OnPitchSelected (bool aSelected)
Handles when a the trigger is selected via the associated toggle switch by passing the event to the parent handler.
Parameters
in aSelected True if the trigger was selected. False otherwise.
Definition at line 95 of file SC_PitchSelectionTrigger.cs.
References SC_PitchSelectionContainer.HandlePitchSelection().
Referenced by SC_PitchSelectionTrigger.Awake(), and SC_PitchSelectionTrigger.SetSelection().
    {
        mHandler.HandlePitchSelection(aSelected,
      mIndex);
    }