Event Handlers
Functions
void SC_LoadSongDialog.OnSongSelected (int aIndex)
Gets the selected Song from the song manager.
void SC_LoadSongDialog.OnCancelButtonClicked ()
Handles the Cancel button being clicked with self-destruction.
void SC_LoadSongDialog.OnLoadButtonClicked ()
Handles the Load button being clicked by invoking the SongSelectedEvent and destroying itself.
Detailed Description
These are functions called by the SC_LoadSongDialog to handle events.
Function Documentation
OnCancelButtonClicked()
void SC_LoadSongDialog.OnCancelButtonClicked () [private]
Handles the Cancel button being clicked with self-destruction.
Definition at line 111 of file SC_LoadSongDialog.cs.
Referenced by SC_LoadSongDialog.Awake().
    {
        DestroyImmediate(gameObject, false);
    }
OnLoadButtonClicked()
void SC_LoadSongDialog.OnLoadButtonClicked () [private]
Handles the Load button being clicked by invoking the SongSelectedEvent and destroying itself.
Definition at line 119 of file SC_LoadSongDialog.cs.
Referenced by SC_LoadSongDialog.Awake().
    {
        SongSelected.Invoke(mSelectedSong);
        DestroyImmediate(gameObject, false);
    }
OnSongSelected()
void SC_LoadSongDialog.OnSongSelected (int aIndex) [private]
Gets the selected Song from the song manager.
Parameters
in aIndex The index of the selected song.
Definition at line 103 of file SC_LoadSongDialog.cs.
References SongManagerClass.GetSongByName(), and VirtualInstrumentManager.SongManager.
Referenced by SC_LoadSongDialog.Awake().
    {
        mSelectedSong = mVIM.SongManager.
      GetSongByName(mSongSelectionMenu.options[aIndex].text);
    }