Unity Functions
Functions
void SongCreationManager.Awake ()
Initializes the Song Creation Interface by getting references to all of the modules within the scene.
Detailed Description
These are functions called automatically by Unity.
Function Documentation
Awake()
void SongCreationManager.Awake () [private]
Initializes the Song Creation Interface by getting references to all of the modules within the scene.
Definition at line 250 of file SongCreationManager.cs.
References SongCreationManager.OnBPMChange(), SongCreationManager.OnCreateNote(), SongCreationManager.OnLoadSongButtonClicked(), SongCreationManager.OnPlaySong(), SongCreationManager.OnSaveSong(), SongCreationManager.OnVelocityChange(), Song.SetName(), SongCreationManager.SongCreationSelectionContainer.SetSelected(), SC_PitchSelectionContainer.SetUpAsDrumSelector(), and SongCreationManager.UnloadSongCreationInterface().
    {
        // Initialize the song.
        mSong = new Song();
        // Get the virtual instrument manager.
        mVIM = GameObject.Find("VirtualInstrumentManager").GetComponent<
      VirtualInstrumentManager>();
        // Set up the container for showing the song's notes.
        mNoteDisplay = gameObject.transform.GetChild(1).GetChild(0).GetChild(0).
      gameObject.AddComponent<SC_NoteDisplayContainer>();
        // Set up the container for selecting pitches.
        mPitchSelector = gameObject.transform.GetChild(2).GetChild(0).GetChild(0).
      gameObject.AddComponent<SC_PitchSelectionContainer>();
        mPitchSelector.SetUpAsPitchSelector();
        // Set up the panels for choosing a note's length and offset.
        mLengthPanel = gameObject.transform.GetChild(3).gameObject.AddComponent<
      SongCreationSelectionContainer>();
        mLengthPanel.SetSelected(Music.NOTE_LENGTH.Q);
        mOffsetPanel = gameObject.transform.GetChild(4).gameObject.AddComponent<
      SongCreationSelectionContainer>();
        // Set up the slider for the note's velocity.
        mVelocitySlider = gameObject.transform.GetChild(5).GetChild(0).GetComponent<
      Slider>();
        mVelocitySlider.onValueChanged.AddListener(OnVelocityChange);
        // Set up the slider for the song's default BPM.
        mBPMSlider = gameObject.transform.GetChild(5).GetChild(1).GetComponent<Slider>();
        mBPMSlider.onValueChanged.AddListener(OnBPMChange);
        // Set up the input field for naming the song.
        mSongNameInputField = gameObject.transform.GetChild(6).gameObject.GetComponent
      <InputField>();
        mSongNameInputField.onEndEdit.AddListener(mSong.
      SetName);
        // Set up the buttons.
        mNewNoteButton = gameObject.transform.GetChild(7).gameObject.GetComponent<Button>()
      ;
        mNewNoteButton.onClick.AddListener(OnCreateNote);
        mResetPitchesButton = gameObject.transform.GetChild(8).GetComponent<Button>();
        mResetPitchesButton.onClick.AddListener(mPitchSelector.ResetPitches);
        mSaveSongButton = gameObject.transform.GetChild(9).gameObject.GetComponent<Button>
      ();
        mSaveSongButton.onClick.AddListener(OnSaveSong);
        mPlaySongButton = gameObject.transform.GetChild(10).GetComponent<Button>();
        mPlaySongButton.onClick.AddListener(OnPlaySong);
        mATIButton = gameObject.transform.GetChild(11).GetComponent<Button>();
        mATIButton.onClick.AddListener(UnloadSongCreationInterface);
        mLoadSongButton = transform.GetChild(13).GetComponent<Button>();
        mLoadSongButton.onClick.AddListener(
      OnLoadSongButtonClicked);
        // Set up the drum selector.
        mDrumSelector = gameObject.transform.GetChild(12).GetChild(0).GetChild(0).
      gameObject.AddComponent<SC_PitchSelectionContainer>();
        mDrumSelector.SetUpAsDrumSelector();
    }