Implemented Virtual Functions
Functions
override void Piano.InitializeBuiltInDynamics ()
Initializes values related to the Built-In Dynamics for this instrument and allocates the audio data container. The Piano samples are available in three separate dynamics :
 pp: pianissimo (Very Soft) for velocities from 0 to 50.
 mf: mezzo-forte (Half-loud) for velocities from 51 to 75.
 ff: fortissimo (Very Loud) for velocities from 76 to 100.
override void Piano.CreateFilenames ()
Creates the filenames from which to load the wav files.
Detailed Description
Implementations of pure virtual functions from the base class.
Function Documentation
CreateFilenames()
override void Piano.CreateFilenames () [protected], [virtual]
Creates the filenames from which to load the wav files.
An example filename would be:
 `Resources/Audio/VirtualInstrument/Piano/Samples/ff/C4ff`
Reimplemented from VirtualInstrument.
Definition at line 120 of file Piano.cs.
References VirtualInstrument.mBuiltInDynamics, VirtualInstrument.mFilenames, VirtualInstrument.mFilepath, VirtualInstrument.mHighestSupportedPitch, VirtualInstrument.mLowestSupportedPitch, VirtualInstrument.mNumBuiltInDynamics, VirtualInstrument.mNumFiles, and Music.NoteToString().
Referenced by Piano.Piano().
    {
        // Set the base filepath and number of files.
        mFilepath = "Audio/VirtualInstrument/Piano/Samples/";
        mNumFiles = 258;
        // Initialize the array of filenames.
        mFilenames = new string[mNumFiles];
        // Iterate through each dynamics value and create filenames for each supported note.
        int index = 0;
        for(int i = 0; i < mNumBuiltInDynamics; i++)
        {
            for(int j = (int)mLowestSupportedPitch; j <= (int)
      mHighestSupportedPitch; j++)
            {
                mFilenames[index] = mFilepath +
      mBuiltInDynamics[i] + "/" + Music.NoteToString(j) +
      mBuiltInDynamics[i];
                index++;
            }
        }
    }
InitializeBuiltInDynamics()
override void Piano.InitializeBuiltInDynamics () [protected], [virtual]
Initializes values related to the Built-In Dynamics for this instrument and allocates the audio data container. The Piano samples are available in three separate dynamics :
 pp: pianissimo (Very Soft) for velocities from 0 to 50.
 mf: mezzo-forte (Half-loud) for velocities from 51 to 75.
 ff: fortissimo (Very Loud) for velocities from 76 to 100.
Reimplemented from VirtualInstrument.
Definition at line 86 of file Piano.cs.
References VirtualInstrument.mAudioData, Music.MAX_SUPPORTED_NOTES, VirtualInstrument.mBuiltInDynamics, VirtualInstrument.mBuiltInDynamicsThresholds, and VirtualInstrument.mNumBuiltInDynamics.
Referenced by Piano.Piano().
    {
        // Set the number of Built-In Dynamics.
        mNumBuiltInDynamics = 3;
        // Set up the strings for creating the filenames.
        mBuiltInDynamics = new string[mNumBuiltInDynamics];
        mBuiltInDynamics[0] = "pp";
        mBuiltInDynamics[1] = "mf";
        mBuiltInDynamics[2] = "ff";
        mBuiltInDynamicsThresholds = new int[
      mNumBuiltInDynamics];
        // Velocities between 0 & 50 will play the pianissimo samples.
        // Velocities between 51 & 75 will play the mezzoforte samples.
        // Velocities between 75 & 100 will play the fortissimo samples.
        mBuiltInDynamicsThresholds[0] = 50;
        mBuiltInDynamicsThresholds[1] = 75;
        mBuiltInDynamicsThresholds[2] = 100;
        // Allocate the audio data.
        mAudioData = new float[mNumBuiltInDynamics][][];
        for(int i = 0; i < mNumBuiltInDynamics; i++)
        {
            mAudioData[i] = new float[Music.MAX_SUPPORTED_NOTES][];
        }
    }