Public Functions
Functions
void Song.AddNote (Music.CombinedNote aNewNote)
Adds a note to the Song.
int Song.GetBPM ()
Gets the BPM of the song.
Music.PITCH Song.GetHighestPitch ()
Gets the highest pitch in the song.
Music.PITCH Song.GetLowestPitch ()
Gets the lowest pitch in the song.
string Song.GetName ()
Gets the name of the song.
Music.CombinedNote Song.GetNote (int aIndex)
Gets a note in the Song.
CombinedNoteData [] Song.GetNoteData ()
Converts the notes in the song to NoteData.
List< Music.CombinedNote > Song.GetAllNotes ()
Returns a list of the notes in the Song.
int Song.GetNumNotes ()
Gets the number of notes in the Song.
SongType Song.GetSongType ()
Gets the type of song that the Song is.
Music.TimeSignature Song.GetTimeSignature ()
Gets the time signature of the Song.
void Song.RemoveNote (int aIndex)
Removes a note from the song.
void Song.ReplaceNote (Music.CombinedNote aNote, int aIndex)
Replaces a note at a given index.
void Song.SetBPM (int aBPM)
Sets the default BPM of the Song.
void Song.SetBPM (float aBPM)
Sets the default BPM of the Song.
void Song.SetName (string aSongName)
Sets the name of the Song.
void Song.SetTimeSignature (Music.TimeSignature aTimeSignature)
Sets the time signature of the Song.
void Song.WriteSongToFile ()
Writes the song to a file. The file will be stored in StreamingAssets/Songs/.
Detailed Description
Functions that allow other classes to interact with the Song.
Function Documentation
AddNote()
void Song.AddNote (Music.CombinedNote aNewNote)
Adds a note to the Song.
Parameters
in aNewNote The note to add.
Definition at line 153 of file Song.cs.
References Song.mHighestPitch, Song.mLowestPitch, Song.mNotes, and Song.UpdateSongType().
Referenced by Song.LoadSongFromFile(), and SongCreationManager.OnCreateNote().
    {
        // Update the number of musical notes in the song if needed.
        if(aNewNote.MusicalNote.Pitches != null)
        {
            mNumMusicalNotes++;
            for(int i = 0; i < aNewNote.MusicalNote.Pitches.Length; i++)
            {
                // Update the highest pitch.
                if(aNewNote.MusicalNote.Pitches[i] != Music.PITCH.REST &&
      mHighestPitch < aNewNote.MusicalNote.Pitches[i])
                {
                    mHighestPitch = aNewNote.MusicalNote.Pitches[i];
                }
                // Update the lowest pitch.
                if(aNewNote.MusicalNote.Pitches[i] != Music.PITCH.REST &&
      mLowestPitch > aNewNote.MusicalNote.Pitches[i])
                {
                    mLowestPitch = aNewNote.MusicalNote.Pitches[i];
                }
            }
        }
        // Update the number of notes with drum hits in the song if needed.
        if(aNewNote.Drums.Hits != null)
        {
            mNumDrumNotes++;
        }
        // Add the note to the list.
        mNotes.Add(aNewNote);
        // Update the song type.
        UpdateSongType();
    }
GetAllNotes()
List<Music.CombinedNote> Song.GetAllNotes ()
Returns a list of the notes in the Song.
Returns
A list of the notes in the Song.
Definition at line 294 of file Song.cs.
References Song.mNotes.
Referenced by SongCreationManager.OnLoadSong(), and SongCreationManager.OnSaveSong().
    {
        return mNotes;
    }
GetBPM()
int Song.GetBPM ()
Gets the BPM of the song.
Returns
The BPM of the song as an integer.
Definition at line 194 of file Song.cs.
References Song.mBPM.
Referenced by ATI_DiagnosticsDemoSongHandler.LoadDemoSong(), ATI_DemoSongButtonHandler.LoadDemoSong(), ATI_DiagnosticsDemoSongHandler.Start(), and ATI_DemoSongButtonHandler.Start().
    {
        return mBPM;
    }
GetHighestPitch()
Music.PITCH Song.GetHighestPitch ()
Gets the highest pitch in the song.
Returns
The highest pitch in the song
Definition at line 203 of file Song.cs.
References Song.mHighestPitch.
Referenced by KeyContainer.HandlePlaySongEvent().
    {
        Assert.IsTrue(mType != SongType.Empty && mType !=
      SongType.DrumLoop,
            "Tried to get information about pitches in a song that had no pitches!");
        return mHighestPitch;
    }
GetLowestPitch()
Music.PITCH Song.GetLowestPitch ()
Gets the lowest pitch in the song.
Returns
The lowest pitch in the song
Definition at line 215 of file Song.cs.
References Song.mLowestPitch.
Referenced by KeyContainer.HandlePlaySongEvent().
    {
        Assert.IsTrue(mType != SongType.Empty && mType !=
      SongType.DrumLoop,
            "Tried to get information about pitches in a song that had no pitches!");
        return mLowestPitch;
    }
GetName()
string Song.GetName ()
Gets the name of the song.
Returns
The name of the song as a string.
Definition at line 227 of file Song.cs.
References Song.mName.
Referenced by SongManagerClass.AddSong(), and SongManagerClass.LoadSongs().
    {
        return mName;
    }
GetNote()
Music.CombinedNote Song.GetNote (int aIndex)
Gets a note in the Song.
Parameters
in aIndex The index of the note in the song.
Returns
The note at the specified index in the song.
Definition at line 237 of file Song.cs.
References Song.mNotes.
Referenced by SongCreationManager.OnEditEvent().
    {
        Assert.IsTrue(mNotes.Count > 0, "Tried to get a note from an empty song!");
        return mNotes[aIndex];
    }
GetNoteData()
CombinedNoteData [] Song.GetNoteData ()
Converts the notes in the song to NoteData.
Returns
An array of note data representing the notes in the Song.
This function is used to convert the Song's abstract information which is based around musical notation into specific information that can be used to map it to audio data and waveform samples.
See also
VirtualInstrumentManager::OnPlaySongEvent VirtualInstrumentManager::OnPlayDrumLoopEvent NoteOutputObject::OnAudioFilterRead
Definition at line 253 of file Song.cs.
References Song.GetNoteLengthInSamples(), Song.PercussionData.HasHiHat, Song.PercussionData.Hits, Song.CombinedNoteData.MelodyData, Song.mNotes, Song.mTimeSignature, Song.MelodyNoteData.NumSamples, Song.CombinedNoteData.PercussionData, Song.MelodyNoteData.Pitches, Song.CombinedNoteData.TotalOffset, Song.PercussionData.Velocity, and Song.MelodyNoteData.Velocity.
Referenced by KeyContainer.HandlePlaySongEvent(), VirtualInstrumentManager.OnPlayDrumLoopEvent(), and VirtualInstrumentManager.OnPlaySongEvent().
    {
        // Allocate the returned array.
        CombinedNoteData[] returned = new CombinedNoteData[mNotes.Count];
        // Set up variables to keep track of a note's number of samples and total offset.
        int offset = 0;
        int numSamp = 0;
        // Iterate through each note in the list.
        int index = 0;
        foreach(Music.CombinedNote note in mNotes)
        {
            // Get the number of samples and the total offset for the note.
            numSamp = GetNoteLengthInSamples(mBPM, 44100, note.MusicalNote.
      Length, mTimeSignature);
            offset += GetNoteLengthInSamples(mBPM, 44100, note.
      OffsetFromPrevNote, mTimeSignature);
            // Set the values for the NoteData's MelodyData.
            returned[index].MelodyData.NumSamples = numSamp;
            returned[index].MelodyData.Pitches = note.MusicalNote.Pitches;
            returned[index].MelodyData.Velocity = note.MusicalNote.Velocity;
            // Set the values for the NoteData's PercussionData.
            returned[index].PercussionData.Velocity = note.Drums.Velocity;
            returned[index].PercussionData.Hits = note.Drums.Hits;
            returned[index].PercussionData.HasHiHat = note.Drums.HasHiHat;
            // Set the offset for the NoteData.
            returned[index].TotalOffset = offset;
            // Go to the next note.
            index++;
        }
        return returned;
    }
GetNumNotes()
int Song.GetNumNotes ()
Gets the number of notes in the Song.
Returns
The number of notes in the Song.
Definition at line 303 of file Song.cs.
References Song.mNotes.
Referenced by SongCreationManager.OnCreateNote(), and SongCreationManager.OnRemoveNote().
    {
        return mNotes.Count;
    }
GetSongType()
SongType Song.GetSongType ()
Gets the type of song that the Song is.
Returns
The type of song that the Song is.
Definition at line 312 of file Song.cs.
References Song.mType.
Referenced by SongManagerClass.AddSong(), VirtualInstrumentManager.OnPlaySongEvent(), and SongCreationManager.OnSaveSong().
    {
        return mType;
    }
GetTimeSignature()
Music.TimeSignature Song.GetTimeSignature ()
Gets the time signature of the Song.
Returns
The time signature of the Song.
Definition at line 321 of file Song.cs.
References Song.mTimeSignature.
    {
        return mTimeSignature;
    }
RemoveNote()
void Song.RemoveNote (int aIndex)
Removes a note from the song.
Parameters
in aIndex The index of the note to remove.
Definition at line 330 of file Song.cs.
References Song.mHighestPitch, Song.mLowestPitch, Song.mNotes, Song.SearchForHighestPitch(), Song.SearchForLowestPitch(), and Song.UpdateSongType().
Referenced by SongCreationManager.OnRemoveNote().
    {
        Assert.IsTrue(aIndex < mNotes.Count,
            "Tried to remove a note at the index " + aIndex.ToString() + " from a song with only " +
      mNotes.Count.ToString() + " notes in it!");
        // Get the note to be removed.
        Music.CombinedNote removedNote = mNotes[aIndex];
        // Remove the note.
        mNotes.RemoveAt(aIndex);
        // Update information about the pitches in the song..
        if(removedNote.MusicalNote.Pitches != null)
        {
            // Decrease the number of musical notes.
            mNumMusicalNotes--;
            // See if we need to set a new highest/lowest pitch.
            foreach(Music.PITCH pitch in removedNote.MusicalNote.Pitches)
            {
                if(pitch != Music.PITCH.REST && pitch ==
      mHighestPitch)
                {
                    mHighestPitch = Music.PITCH.C0;
                    SearchForHighestPitch();
                }
                if(pitch != Music.PITCH.REST && pitch == mLowestPitch)
                {
                    mLowestPitch = Music.PITCH.B9;
                    SearchForLowestPitch();
                }
            }
        }
        // Update information about the drums in the song.
        if(removedNote.Drums.Hits != null)
        {
            mNumDrumNotes--;
        }
        // Update the song type.
        UpdateSongType();
        // Clean up.
        GC.Collect();
        Resources.UnloadUnusedAssets();
    }
ReplaceNote()
void Song.ReplaceNote (Music.CombinedNote aNote, int aIndex)
Replaces a note at a given index.
Parameters
in aNote The note that will be put into the song at the given index.
in aIndex The index of the place to insert the note.
Definition at line 382 of file Song.cs.
References Song.mHighestPitch, Song.mLowestPitch, Song.mNotes, Song.SearchForHighestPitch(), Song.SearchForLowestPitch(), and Song.UpdateSongType().
Referenced by SongCreationManager.OnModifyNote(), and SongCreationManager.OnSaveSong().
    {
        Assert.IsTrue(aIndex < mNotes.Count,
             "Tried to replace a note at the index " + aIndex.ToString() + " for a song with only " +
      mNotes.Count.ToString() + " notes in it!");
        // Get the replaced note.
        Music.CombinedNote replacedNote = mNotes[aIndex];
        // Replace the note.
        mNotes[aIndex] = aNote;
        // See if we need to update the highest/lowest pitch.
        if(replacedNote.MusicalNote.Pitches != null)
        {
            // Decrease the number of musical notes.
            mNumMusicalNotes--;
            // See if we need to set a new highest/lowest pitch.
            foreach(Music.PITCH pitch in replacedNote.MusicalNote.Pitches)
            {
                if(pitch != Music.PITCH.REST && pitch ==
      mHighestPitch)
                {
                    mHighestPitch = Music.PITCH.C0;
                    SearchForHighestPitch();
                }
                if(pitch != Music.PITCH.REST && pitch == mLowestPitch)
                {
                    mLowestPitch = Music.PITCH.B9;
                    SearchForLowestPitch();
                }
            }
        }
        // Account for changes in the number of musical notes and drum notes in the song.
        if(replacedNote.MusicalNote.Pitches != null && aNote.MusicalNote.Pitches == null)
        {
            mNumMusicalNotes--;
        }
        if(replacedNote.Drums.Hits != null && aNote.Drums.Hits == null)
        {
            mNumDrumNotes--;
        }
        // Update the song type.
        UpdateSongType();
    }
SetBPM() [1/2]
void Song.SetBPM (int aBPM)
Sets the default BPM of the Song.
Parameters
in aBPM The new default BPM of the Song.
Definition at line 433 of file Song.cs.
Referenced by ATI_DiagnosticsDemoSongHandler.ChangeBPM(), ATI_DemoSongButtonHandler.ChangeBPM(), and SongCreationManager.OnBPMChange().
    {
        mBPM = aBPM;
    }
SetBPM() [2/2]
void Song.SetBPM (float aBPM)
Sets the default BPM of the Song.
Parameters
in aBPM The new default BPM of the Song.
Definition at line 442 of file Song.cs.
    {
        mBPM = (int)aBPM;
    }
SetName()
void Song.SetName (string aSongName)
Sets the name of the Song.
Parameters
in aSongName The name of the Song.
Definition at line 451 of file Song.cs.
Referenced by SongCreationManager.Awake().
    {
        mName = aSongName;
    }
SetTimeSignature()
void Song.SetTimeSignature (Music.TimeSignature aTimeSignature)
Sets the time signature of the Song.
Parameters
in aTimeSignature The time signature of the Song.
Definition at line 460 of file Song.cs.
References Song.mTimeSignature.
    {
        mTimeSignature.BeatsPerMeasure = aTimeSignature.BeatsPerMeasure;
        mTimeSignature.BaseBeat = aTimeSignature.BaseBeat;
    }
WriteSongToFile()
void Song.WriteSongToFile ()
Writes the song to a file. The file will be stored in StreamingAssets/Songs/.
See also
Song File Format
Definition at line 470 of file Song.cs.
References Song.mName, Song.mNotes, Song.mTimeSignature, and Song.SONG_FILE_PATH.
Referenced by SongCreationManager.OnSaveSong().
    {
        // Set up the filepath.
        string filepath = SONG_FILE_PATH;
        switch(mType)
        {
            case SongType.DrumLoop:
                filepath += "DRUMLOOP_" + mName + ".song";
                break;
            case SongType.Melody:
                filepath += "MELODY_" + mName + ".song";
                break;
            case SongType.CombinedMelodyAndPercussion:
                filepath += "SONG_" + mName + ".song";
                break;
            default:
                break;
        }
        // Set an array for the contents of the file
        string[] contents = new string[mNotes.Count + 2];
        // Put the name of the song in first line to be saved.
        contents[0] = mName;
        // Put the song type, default BPM and the time signature values in the second line to be saved.
        contents[1] = ((int)mType).ToString() + ";" + mBPM.ToString() + ";" +
            mTimeSignature.BeatsPerMeasure.ToString() + ";" + ((int)
      mTimeSignature.BaseBeat).ToString();
        // Put all the notes into the lines from line 3 to line [numNotes].
        for(int i = 0; i < mNotes.Count; i++)
        {
            // Set up the note string.
            contents[i + 2] = "";
            // If pitches exist for the song, then add them.
            if(mType != SongType.DrumLoop)
            {
                // Add the pitches if they exist for this note.
                if(mNotes[i].MusicalNote.Pitches != null)
                {
                    // Add the pitches to the string
                    for(int j = 0; j < mNotes[i].MusicalNote.Pitches.Length; j++)
                    {
                        contents[i + 2] += ((int)mNotes[i].MusicalNote.Pitches[j]).ToString();
                        // If this is not the last pitch of the note, then add a comma
                        if(j + 1 != mNotes[i].MusicalNote.Pitches.Length)
                        {
                            contents[i + 2] += ",";
                        }
                        // If this is the last pitch of the note, then add a bar or a semicolon depending
       on if there are drums.
                        else
                        {
                            if(mType == SongType.CombinedMelodyAndPercussion)
                            {
                                contents[i + 2] += "|";
                            }
                            else
                            {
                                contents[i + 2] += ";";
                            }
                        }
                    }
                }
                // If pitches don't exist for the note, then put null.
                else
                {
                    contents[i + 2] += "null|";
                }
            }
            // If drums exist for the song, then add them.
            if(mType != SongType.Melody)
            {
                // If there are drums for this note, then add them.
                if(mNotes[i].Drums.Hits != null)
                {
                    // Add the drums to the string
                    for(int j = 0; j < mNotes[i].Drums.Hits.Length; j++)
                    {
                        contents[i + 2] += ((int)mNotes[i].Drums.Hits[j]).ToString();
                        // If this is not the last drum hit of the note, then add a comma
                        if(j + 1 != mNotes[i].Drums.Hits.Length)
                        {
                            contents[i + 2] += ",";
                        }
                        // If this is the last pitch of the note, then add a semicolon.
                        else
                        {
                            contents[i + 2] += ";";
                        }
                    }
                }
            }
            // If the song is not a drum loop, then add the note length.
            if(mType != SongType.DrumLoop)
            {
                contents[i + 2] += (((int)mNotes[i].MusicalNote.Length).ToString() + ";");
            }
            // Add the offset from the previous note.
            contents[i + 2] += (((int)mNotes[i].OffsetFromPrevNote).ToString() + ";");
            // If the song is not a drum loop, then add the musical note velocity.
            if(mType != SongType.DrumLoop)
            {
                contents[i + 2] += mNotes[i].MusicalNote.Velocity.ToString();
            }
            // Put a bar if both drums and pitches exist for the song.
            if(mType == SongType.CombinedMelodyAndPercussion)
            {
                contents[i + 2] += "|";
            }
            // If the song has drums, then put the velocity for the drums for this note.
            if(mType != SongType.Melody)
            {
                contents[i + 2] += mNotes[i].Drums.Velocity;
            }
        }
        // Write the contents to the file.
        System.IO.File.WriteAllLines(filepath, contents);
    }