var annotated_dup =
[
    [ "ATI", "class_a_t_i.html", "class_a_t_i" ],
    [ "ATI_Buttons", "class_a_t_i___buttons.html", "class_a_t_i___buttons" ],
    [ "ATI_DemoSongButtonHandler", "class_a_t_i___demo_song_button_handler.html", "class_a_t_i___demo_song_button_handler" ],
    [ "ATI_Diagnostics", "group___audio_testing.html#class_a_t_i___diagnostics", "group___audio_testing_class_a_t_i___diagnostics" ],
    [ "ATI_DiagnosticsDemoSongHandler", "class_a_t_i___diagnostics_demo_song_handler.html", "class_a_t_i___diagnostics_demo_song_handler" ],
    [ "ATI_EchoFilterHandler", "class_a_t_i___echo_filter_handler.html", "class_a_t_i___echo_filter_handler" ],
    [ "ATI_InstrumentSelectionHandler", "class_a_t_i___instrument_selection_handler.html", "class_a_t_i___instrument_selection_handler" ],
    [ "ATI_NoteRangeSelectionHandler", "class_a_t_i___note_range_selection_handler.html", "class_a_t_i___note_range_selection_handler" ],
    [ "ATI_ReverbFilterHandler", "class_a_t_i___reverb_filter_handler.html", "class_a_t_i___reverb_filter_handler" ],
    [ "ATI_VelocityHandler", "class_a_t_i___velocity_handler.html", "class_a_t_i___velocity_handler" ],
    [ "BlackKey", "class_black_key.html", "class_black_key" ],
    [ "DebugUI", "class_debug_u_i.html", "class_debug_u_i" ],
    [ "DrumKit", "class_drum_kit.html", "class_drum_kit" ],
    [ "KeyContainer", "class_key_container.html", "class_key_container" ],
    [ "Marimba", "class_marimba.html", "class_marimba" ],
    [ "Music", "class_music.html", "class_music" ],
    [ "MusicalTypingHandler", "class_musical_typing_handler.html", "class_musical_typing_handler" ],
    [ "NoteOutputObject", "class_note_output_object.html", "class_note_output_object" ],
    [ "Piano", "class_piano.html", "class_piano" ],
    [ "SC_LoadSongDialog", "class_s_c___load_song_dialog.html", "class_s_c___load_song_dialog" ],
    [ "SC_MeasureDisplayPanel", "class_s_c___measure_display_panel.html", "class_s_c___measure_display_panel" ],
    [ "SC_NoteDisplayContainer", "class_s_c___note_display_container.html", "class_s_c___note_display_container" ],
    [ "SC_NoteDisplayPanel", "class_s_c___note_display_panel.html", "class_s_c___note_display_panel" ],
    [ "SC_PitchSelectionContainer", "class_s_c___pitch_selection_container.html", "class_s_c___pitch_selection_container" ],
    [ "SC_PitchSelectionTrigger", "class_s_c___pitch_selection_trigger.html", "class_s_c___pitch_selection_trigger" ],
    [ "Song", "class_song.html", "class_song" ],
    [ "SongCreationManager", "class_song_creation_manager.html", "class_song_creation_manager" ],
    [ "SongManagerClass", "class_song_manager_class.html", "class_song_manager_class" ],
    [ "VirtualInstrument", "class_virtual_instrument.html", "class_virtual_instrument" ],
    [ "VirtualInstrumentManager", "class_virtual_instrument_manager.html", "class_virtual_instrument_manager" ],
    [ "WhiteKey", "class_white_key.html", "class_white_key" ]
];